### ISSUE TITLE
overlapping chunks

### ISSUE THREAD

**Issue by alek0991** [odelaneau/GLIMPSE#10]
Hi, 
I have encountered cases where chunks are overlapping and ligate raises the following error:
`ERROR: Overlap between chunk specific variants`

Here I have copied the overlapping chunks. Note that the end position of ORG(ID=30) and start position for ORG(ID=31) are the same (108317601, highlighted). As a result, the BUF tag is set to 0 for variants with position 108317601 in both imputed vcf files which leads to the error. You can see corresponding chunk file and vcf files below. 

#### Chunk file (only two rows):

**ID**|**CHROM**|**IRG**|**ORG**|**A**|**B**
:-----:|:-----:|:-----:|:-----:|:-----:|:-----:
30|2|2:104492814-108517646|2:104692886-**108317601**|3624716|110112
31|2|2:108117598-110528936|2:**108317601**-110328253|2010653|55056

#### The imputed vcf (ID=30):
**#CHROM**|**POS**|**ID**|**REF**|**ALT**|**QUAL**|**FILTER**|**INFO**|**FORMAT**|**SAMPLE**
:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:
2|108317601|.|G|A|.|.|RAF=0.000199681;AF=0;INFO=1;BUF=0|GT:DS:GP:HS|0/0:0:1,0,0:0
2|108317601|.|GC|G|.|.|RAF=0.245607;AF=0.466671;INFO=0.875;BUF=0|GT:DS:GP:HS|0/1:0.933:0.067,0.933,0:284073

#### The imputed vcf (ID=31):
**#CHROM**|**POS**|**ID**|**REF**|**ALT**|**QUAL**|**FILTER**|**INFO**|**FORMAT**|**SAMPLE**
:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:
2|108317601|.|G|A|.|.|RAF=0.000199681;AF=0;INFO=1;BUF=0|GT:DS:GP:HS|0/0:0:1,0,0:0
2|108317601|.|GC|G|.|.|RAF=0.245607;AF=0.450344;INFO=0.819;BUF=0|GT:DS:GP:HS|0/1:0.901:0.099,0.9,0:354985

**Comment by SimoneRubinacci** [comment]
Hi Ali,

Yes, it's a small bug that very recently we found as well. Will definitively fix it very soon (hopefully during the weekend), in the meanting, a very simple fix is just to change one of the two chunks to avoid the overlap, and re-run the chunk like:

#### Chunk file (only two rows):

**ID**|**CHROM**|**IRG**|**ORG**|**A**|**B**
:-----:|:-----:|:-----:|:-----:|:-----:|:-----:
30|2|2:104492814-108517646|2:104692886-**108317601**|3624716|110112
31|2|2:108117598-110528936|2:**108317602**-110328253|2010653|55056

Thank you for your message, will close the issue when we'll commit the bugfix.

Best wishes,
Simone

**Comment by SimoneRubinacci** [comment]
Hi Ali,

Are you using a version of the code only requiring a single input file or two (--input / --reference)?
Because in the current version of the code (that uses only --input) I can't replicate the error. In the case you still get the error for the most recent version of the code, can you please share with me the sites.vcf.gz file you are using and the exact GLIMPSE_chunk command line?

**Comment by dtaliun** [comment]
> Hi Ali,
> 
> Are you using a version of the code only requiring a single input file or two (--input / --reference)?
> Because in the current version of the code (that uses only --input) I can't replicate the error. In the case you still get the error for the most recent version of the code, can you please share with me the sites.vcf.gz file you are using and the exact GLIMPSE_chunk command line?

I have the same error while using --input and --reference together.

**Comment by alek0991** [comment]
> Hi Ali,
> 
> Are you using a version of the code only requiring a single input file or two (--input / --reference)?
> Because in the current version of the code (that uses only --input) I can't replicate the error. In the case you still get the error for the most recent version of the code, can you please share with me the sites.vcf.gz file you are using and the exact GLIMPSE_chunk command line?

**Comment by alek0991** [comment]
Hi Simone, 
I have been using the older one. However, I get identical result with the new one. Following is the command for the latest version:

`GLIMPSE_chunk --input mpileup.bcf --region 2 --window-size 2000000 --buffer-size 200000 --output chunk_new.txt`

Please use [this link](http://genomebrowser-uploads.hms.harvard.edu/data/aa681/misc/debug.tar) to download the files and then run `tar -xvf debug.tar` to extract them.

Thanks,
Ali

**Comment by SimoneRubinacci** [comment]
Thank you for this, it really useful.

This happened because in your file in that "problematic" position you had multiple records sharing the same POS (e.g. you can run bcftools view -r 2:108317600-108317602 mpileup.bcf).
I've added a check for this. Should be hopefully all fixed now.

**Comment by dtaliun** [comment]
> Thank you for this, it was really useful.
> 
> This happened because in your file in that "problematic" position you had multiple records sharing the same POS (e.g. you can run `bcftools view -r 2:108317600-108317602 mpileup.bcf`).
> I've added a check for this. Should be hopefully all fixed now.
> 
> Best,
> 
> Simone

Hi Simone,

Thanks for fixing the issue. Could you please give details on how multi-allelic variants with the same position, especially indels, should be represented in VCF for GLIMPSE (both study and reference)? When using other software, multi-allelic variants are sometimes required to be split into multiple records in VCF. Is this the case for GLIMPSE as well or multi-allelic variants should be dropped completely?

**Comment by SimoneRubinacci** [comment]
Hi @dtaliun and @alek0991 
Just a clarification, if you call genotype likelihoods using **bcftools**, please avoid including indels and focus only on SNPs. 

_GLIMPSE is able to impute indels_, however **the quality of the GLs given by bcftools is extremely low at indels**, and this problem would influence imputation accuracy of the SNPs as well. We are currently testing other GL calling methods that are better suited to call indels and will keep you posted (will probably edit the tutorial as well).

Regarding variants sharing the same position, it's again dependent on the quality of the likelihoods. I am not sure bcftools does a good job there. For now, I would drop them, or carefully check the quality of the GLs given by your calling method.

We are working on it.

Best wishes,

Simone

**Comment by alek0991** [comment]
Hi @SimoneRubinacci 

Thank you for the clarification. I've noticed this issue and consequently I ignore the bcftools genotype likelihood estimation for indels. However, I only use SNPs genotype likelihood estimations to impute both SNPs and indels.  Do you think this is also problematic? 

Best,
Ali
