### ISSUE TITLE
Error when running GLIMPSE_concordance module in "Tutorial" folder

### ISSUE THREAD

**Issue by shafayetrahat** [odelaneau/GLIMPSE#102]
-  when running  ./step8_script_concordance.sh in "Tutorial" folder, the error below shows,
 `` ValueError: The number of FixLocator locations (10), usually from a call to set_ticks, does not match the number of ticklabels (14)``
- Possible reason: mismatch in the length of  "mybins" and "labels" lists; which ended up error in line 37 of plot/concordance_plot.py

**Comment by srubinacci** [comment]
Hi,
Thanks  for reporting this. I just merged your pull request. 
Best,

Simone
