### ISSUE TITLE
How to get GLIMPSE to impute indels?

### ISSUE THREAD

**Issue by njbernstein** [odelaneau/GLIMPSE#104]
Hi there,

I have a reference imputation panel with indels, but followed the tutorial so created a sites.tsv and site.vcf without those indels but the reference panel still has them. I thought GLIMPSE would be able to impute indels even I dont call indels with my variant caller (bcftools) as suggested in the documentation. Is there a partciular invocation needed to force impute indels?

**Comment by srubinacci** [comment]
Hi,
imputing indels requires special care, as the low imputation accuracy using indels can propagate to neighbouring SNPs. Therefore  we indeed do not use indels in the standard pipeline.

The way I impute indels with GLIMPSE is to compute likelihoods only at SNPS (as in the tutorial), and then adding the option "--impute-reference-only-variants" for GLIMPSE_phase. In this way, if the reference panel contains indels, these are imputed, but without considering gentoype likelihoods as emission probability at indels. Basically we perform standard imputation at those sites, so errors do not propagate.

Let me know if this works for you.

**Comment by njbernstein** [comment]
This worked for me to phase chunks but I got an error during ligation:
```
Ligating chunks
  * Create all file descriptors
  * Extract sample IDs
  * FPLOIDY = 2 [Only diploid samples in the region]
  * Checking samples and FPLOIDY consistency across all input files
  * Samples overlap and FPLOIDY are consistent across files.
  * #samples = 1 [0 haploids/ 1 diploid]
  * #main_iterations = 10

Chunk 1 from position [10397]

Chunk 2 from position [1786326]
  * #switches=5

Chunk 3 from position [3110297]
  * #switches=6

Chunk 4 from position [4442645]
  * #switches=5

Chunk 5 from position [5914739]
  * #switches=7

[31mERROR: [0mOverlap between buffer-specific variants
```

I'm guessing the chunk function needs to now you are imputing variants not in your sites vcf. I'll try that

**Comment by njbernstein** [comment]
Yes that was the issue

**Comment by srubinacci** [comment]
Indeed. Also, the ligate program might not expect indel input and sometimes could cause problems. if you are running into the same problem again, let me know, I can help by quickly modifying the ligate tool.
