### ISSUE TITLE
Description of concordence algorithm

### ISSUE THREAD

**Issue by shafayetrahat** [odelaneau/GLIMPSE#105]
- The concordance algorithm isn't sufficiently clear to understand. Is the concordance defined here is the ratio of imputed genotype and true genotype? Can you describe it elaborately?
- There is no documentation of concordance tools. Can you add the documentation?

**Comment by srubinacci** [comment]
Hi,
The concordance tool is indeed not well documented, but we mention what the program does our paper. We use the program to compute the concordace/discordace rate between imputed and true genotypes, r^2 correlation, calibration and other similar metrics.
The program is mainly for our internal use, and we are not planning to write a tutorial for this version. For this reason we added self-explanatory headers in the output files, similarly to bcftools stats. We will write a tutorial documenting the tool for the next major release.

Hope this helps,

Simone

**Comment by shafayetrahat** [comment]
Thanks for the answer. Eagerly waiting to see the new features in the next major release. :+1: :+1: :+1: :+1: :+1: :+1:

**Comment by srubinacci** [comment]
Glad it helped. Let me know if you have specific questions regarding the tool.
