### ISSUE TITLE
Glimpse in nf-core

### ISSUE THREAD

**Issue by LouisLeNezet** [odelaneau/GLIMPSE#106]
Hi,

I would like to add Glimpse to the nf-core modules.
I'm currently working with Glimpse and nextflow, and I think the community will benefit to have your work available on nf-core.
Could we discuss about it ?

Thanks,
Louis Le Nézet

**Comment by srubinacci** [comment]
Hi Louis,
Sure, I would be very happy if you want to contribute developing an the open-source nf-core pipeline, I will definitively support it and advertise it.
Feel free to send me an email.

Best wishes,

Simone

**Comment by LouisLeNezet** [comment]
Hi,

I'm currently writing the tool GLIMPSE_phase (GLIMPSE_chunk is already available on nf-core) and I have some trouble.
The tool tells me that the number of samples in the reference panel is zero or exclusive sample.
It may come from the data I'm using (I don't have problem when using the one available on your tutorial), but I would like to understand what is this error and how I could solve it.
Could you help me ?

Best regards,
Louis

**Comment by srubinacci** [comment]
Hi Louis,

Yes - GLIMPSE_phase is the core of GLIMPSE. It uses a reference panel of phased haplotypes to impute the data. It is indeed likely that the problem is in the data you are using. Just check your reference panel has many phased samples (e.g. the 1000 Genomes Project data). 
Can you develop your pipeline using the data from the tutorial directly?

Best wishes,
Simone

**Comment by LouisLeNezet** [comment]
Hi,

I though that glimpse could use any kind of vcf from a reference panel.
How could I generate / find such a file ?
I also saw that a gmap is given in the tutorial to glimpse_phase, is it a necessary file or can it be omitted ?

I'm developing my pipeline in nextflow because I want to compare different software, dataset and many individuals.
Therefore nextflow should help me manage all the parallelisation and make the code more easy to maintain.

I still followed the tutorial to learn how glimpse worked. They were some little things that I needed to change to make it work but it did.

**Comment by LouisLeNezet** [comment]
Hi,

Sorry, I missed the step 3.1 when testing, as such the vcf was not prepared as it should. I will test that tomorrow.
I also saw that a gmap is given in the tutorial to glimpse_phase, is it a necessary file or can it be omitted ?

I'm developing my pipeline in nextflow because I want to compare different software, dataset and many individuals.
Therefore nextflow should help me manage all the parallelisation and make the code more easy to maintain.

I still followed the tutorial to learn how glimpse worked. They were some little things that I needed to change to make it work but it did.

**Comment by srubinacci** [comment]
Hi,
Indeed, a reference panel of haplotypes (e.g. 1000GP) is required, while a map is not, but highly recommended when working with human data.  You can find a more detailed description of GLIMPSE_phase in the GLIMPSE paper if the tutorial does not provide enough explanation.

Hope it helps,
Simone
