### ISSUE TITLE
Sample-level concordance r2 output

### ISSUE THREAD

**Issue by renatosantos98** [odelaneau/GLIMPSE#109]
Hello,

I am trying to get a single r2 value across all the MAF bins in a sample when running concordance.

I assume _output.rsquare.spl.txt.gz_ would have this value, but the concordance output files have no headers and contain several different values in them.

What do the values in the output file columns mean? Which one is the r2 for the whole sample?

Best regards,
Renato

**Comment by srubinacci** [comment]
Hi Renato, 

the output.rsquare.spl.txt.gz is just for plotting. Look at the output.error.spl.txt.gz for more information, there's a header in that file.

Hope this helps,

Simone

**Comment by renatosantos98** [comment]
Hi Simone,

I found it on the file you mentioned.

Many thanks for your help.

Best,
Renato
