### ISSUE TITLE
why the step8 cause core dumped error?

### ISSUE THREAD

**Issue by zhen0001** [odelaneau/GLIMPSE#111]
Hi Odelaneau,

I am running the tutorial example. In the final step, as step 8,  did not work. 
Do you know what is the error? 

[GLIMPSE] Validate imputed data
  * Author        : Simone RUBINACCI & Olivier DELANEAU, University of Lausanne
  * Contact       : simone.rubinacci@unil.ch & olivier.delaneau@unil.ch
  * Version       : 1.1.1
  * Run date      : 31/10/2022 - 22:04:44

Files are listed in [concordance.lst]
Parameters:
  * Output  : GLIMPSE_concordance/output
  * Seed    : 15052011
  * #Threads   : 4
  * MinPROB : 0.9999
  * MinDP   : 8
  * Using INFO/AF_nfe tag for allele frequency bins.
  * #bins   : 9

Initializing engine based on allele frequency bins:
  * Probs >= 0.9999
  * Depth >= 8
  * #AF bins = 8
  * AF bins [0 0.001 0.002 0.005 0.01 0.05 0.1 0.2 0.5]

Reading list of input files in [concordance.lst]
step8_script_concordance.sh: line 5: 40052 Segmentation fault      (core dumped) ./bin/GLIMPSE_concordance --input concordance.lst --minDP 8 --output GLIMPSE_concordance/output --minPROB 0.9999 --bins 0.00000 0.00100 0.00200 0.00500 0.01000 0.05000 0.10000 0.20000 0.50000 --af-tag AF_nfe --thread 4
Traceback (most recent call last):
  File "/crex/proj/uppstore2017145/V3/users/chen/bin/GLIMPSE/tutorial/plot/./concordance_plot.py", line 18, in <module>
    with gzip.open('../GLIMPSE_concordance/output.rsquare.grp.txt.gz','rt') as csvfile:
  File "/sw/comp/python/3.9.5/rackham/lib/python3.9/gzip.py", line 58, in open
    binary_file = GzipFile(filename, gz_mode, compresslevel)
  File "/sw/comp/python/3.9.5/rackham/lib/python3.9/gzip.py", line 173, in __init__
    fileobj = self.myfileobj = builtins.open(filename, mode or 'rb')
FileNotFoundError: [Errno 2] No such file or directory: '../GLIMPSE_concordance/output.rsquare.grp.txt.gz'

**Comment by srubinacci** [comment]
Hi,

It seems like the error is that the file `../GLIMPSE_concordance/output.rsquare.grp.txt.gz` does not exists. Just look at your script and maybe modify this relative path?

**Comment by zhen0001** [comment]
Yes, you are right. The file doesn't exist because it did not produce any file called output.rsquare.grp.txt.gz. so I am not sure where is wrong before plot.

**Comment by zhen0001** [comment]
Hi Simone,

When I run the step 8 once, it will produce a core.xxx file, such as below:

[zhen0001@rackham2 tutorial]$ strings core.38256
CORE
n.NA12878.chr22.P
CORE
GLIMPSE_concord
./bin/GLIMPSE_concordance --input concordance.lst --minDP 8 --output ./GLIMPSE_
IGISCORE
CORE
ELIFCORE
/crex/proj/uppstore2017145/V3/users/chen/bin/GLIMPSE/concordance/bin/GLIMPSE_concordance
/crex/proj/uppstore2017145/V3/users/chen/bin/GLIMPSE/concordance/bin/GLIMPSE_concordance
/crex/proj/uppstore2017145/V3/users/chen/bin/GLIMPSE/concordance/bin/GLIMPSE_concordance
/usr/lib64/ld-2.17.so
/usr/lib64/ld-2.17.so
/usr/lib64/ld-2.17.so
/usr/lib64/libz.so.1.2.7
/usr/lib64/libz.so.1.2.7
/usr/lib64/libz.so.1.2.7
/usr/lib64/libz.so.1.2.7
/usr/lib64/libpthread-2.17.so
/usr/lib64/libpthread-2.17.so
/usr/lib64/libpthread-2.17.so
/usr/lib64/libpthread-2.17.so
/usr/lib64/libbz2.so.1.0.6
/usr/lib64/libbz2.so.1.0.6
/usr/lib64/libbz2.so.1.0.6
/usr/lib64/libbz2.so.1.0.6
/usr/lib64/liblzma.so.5.2.2
/usr/lib64/liblzma.so.5.2.2
/usr/lib64/liblzma.so.5.2.2
/usr/lib64/liblzma.so.5.2.2
/sw/libs/libcurl/7.45.0/rackham/lib/libcurl.so.4.4.0
/sw/libs/libcurl/7.45.0/rackham/lib/libcurl.so.4.4.0
/sw/libs/libcurl/7.45.0/rackham/lib/libcurl.so.4.4.0
/sw/libs/libcurl/7.45.0/rackham/lib/libcurl.so.4.4.0
/usr/lib64/libcrypto.so.1.0.2k
/usr/lib64/libcrypto.so.1.0.2k
/usr/lib64/libcrypto.so.1.0.2k
/usr/lib64/libcrypto.so.1.0.2k
/sw/comp/gcc/9.3.0_rackham/lib64/libstdc++.so.6.0.28
/sw/comp/gcc/9.3.0_rackham/lib64/libstdc++.so.6.0.28
/sw/comp/gcc/9.3.0_rackham/lib64/libstdc++.so.6.0.28
/sw/comp/gcc/9.3.0_rackham/lib64/libstdc++.so.6.0.28
/usr/lib64/libm-2.17.so
/usr/lib64/libm-2.17.so
/usr/lib64/libm-2.17.so
/usr/lib64/libm-2.17.so
/sw/comp/gcc/9.3.0_rackham/lib64/libgcc_s.so.1
/sw/comp/gcc/9.3.0_rackham/lib64/libgcc_s.so.1
/sw/comp/gcc/9.3.0_rackham/lib64/libgcc_s.so.1
/sw/comp/gcc/9.3.0_rackham/lib64/libgcc_s.so.1
/usr/lib64/libc-2.17.so
/usr/lib64/libc-2.17.so
/usr/lib64/libc-2.17.so
/usr/lib64/libc-2.17.so
/usr/lib64/libssl.so.1.0.2k
/usr/lib64/libssl.so.1.0.2k
/usr/lib64/libssl.so.1.0.2k
/usr/lib64/libssl.so.1.0.2k
/usr/lib64/libdl-2.17.so
/usr/lib64/libdl-2.17.so
/usr/lib64/libdl-2.17.so
/usr/lib64/libdl-2.17.so
/usr/lib64/libgssapi_krb5.so.2.2
/usr/lib64/libgssapi_krb5.so.2.2
/usr/lib64/libgssapi_krb5.so.2.2
/usr/lib64/libgssapi_krb5.so.2.2
/usr/lib64/libkrb5.so.3.3
/usr/lib64/libkrb5.so.3.3
/usr/lib64/libkrb5.so.3.3
/usr/lib64/libkrb5.so.3.3
/usr/lib64/libcom_err.so.2.1
/usr/lib64/libcom_err.so.2.1
/usr/lib64/libcom_err.so.2.1
/usr/lib64/libcom_err.so.2.1
/usr/lib64/libk5crypto.so.3.1
/usr/lib64/libk5crypto.so.3.1
/usr/lib64/libk5crypto.so.3.1
/usr/lib64/libk5crypto.so.3.1
/usr/lib64/libkrb5support.so.0.1
/usr/lib64/libkrb5support.so.0.1
/usr/lib64/libkrb5support.so.0.1
/usr/lib64/libkrb5support.so.0.1
/usr/lib64/libkeyutils.so.1.5
/usr/lib64/libkeyutils.so.1.5
/usr/lib64/libkeyutils.so.1.5
/usr/lib64/libkeyutils.so.1.5
/usr/lib64/libresolv-2.17.so
/usr/lib64/libresolv-2.17.so
/usr/lib64/libresolv-2.17.so
/usr/lib64/libresolv-2.17.so
/usr/lib64/libselinux.so.1
/usr/lib64/libselinux.so.1
/usr/lib64/libselinux.so.1
/usr/lib64/libselinux.so.1
/usr/lib64/libpcre.so.1.2.0
/usr/lib64/libpcre.so.1.2.0
/usr/lib64/libpcre.so.1.2.0
/usr/lib64/libpcre.so.1.2.0
CORE

nce.lst
chr22
dance.lst
f GLIMPSE_validation/EUR.validation.NA12878.chr22.bcf GLIMPSE_ligate/NA12878.chr
LINUX

nce.lst
chr22
dance.lst
f GLIMPSE_validation/EUR.validation.NA12878.chr22.bcf GLIMPSE_ligate/NA12878.chr
/lib64/ld-linux-x86-64.so.2


Any suggestions?
