### ISSUE TITLE
failed to compile

### ISSUE THREAD

**Issue by aheritas** [odelaneau/GLIMPSE#112]
Hi Olivier, 
I am following the instructions at: https://odelaneau.github.io/GLIMPSE/installation.html
I have downloaded and built HTSLib and boost. I have tried editing the specific makefile for GLIMPSE_phase as follows: 

```
desktop: HTSSRC=/data/software/htslib
desktop: HTSLIB_INC=/data/software/htslib
desktop: HTSLIB_LIB=/data/software/htslib/libhts.a
desktop: BOOST_INC=/usr/include
desktop: BOOST_LIB_IO=/data/software/boost_1_73_0/boost/lib/libboost_iostreams.a
desktop: BOOST_LIB_PO=/data/software/boost_1_73_0/boost/lib/libboost_program_options.a
desktop: $(BFILE)
```

The error I am having is: 

```
g++ -std=c++11 -O3 -c src/main.cpp -o obj/main.o -Isrc -I/usr/local/include/htslib -I/usr/include
In file included from src/caller/caller_header.h:27,
                 from src/main.cpp:25:
src/utils/otools.h:50:10: fatal error: htslib/hts.h: No existe el archivo o el directorio
   50 | #include <htslib/hts.h>
      |          ^~~~~~~~~~~~~~
compilation terminated.
make: *** [makefile:84: obj/main.o] Error 1
```
I understand the compiler cannot find hts.h . I realised do not have an `include` subdirectory in my htslib directory, as you state in the tutorial, but I am not sure if this should be located somewhere else. I would appreciate any insights. Thank you. 

Software versions: 
`g++ (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0`
`htslib-1.16`
`boost v1.73.0`

**Comment by srubinacci** [comment]
Hi,

I think you're not compiling the right target. Have you tried to use `make desktop`?
Also, in case, just try to rebuild your HTSlib as indicated by the tutorial: after the make command, it automatically creates the include subfolder.

Let me know how it goes.

Simone

**Comment by aheritas** [comment]
Hi Simone, 
I deleted and did everything as instructed in the installation tutorial, copying and pasting each command and it does not create the include subfolder. [Here](https://github.com/odelaneau/GLIMPSE/files/9939251/tree_server.txt) is a `tree` of the output files and directories. I tried `make desktop` but the same error persists.

I am going to keep trying some other options but I was able to bypass this by running GLIMPSE from a docker image I found. But I do not know if the aforementioned behaviour has already happened to somebody else before.

Thank you!

**Comment by srubinacci** [comment]
I made GLIMPSE available on dockerhub here:
|https://hub.docker.com/r/simrub/glimpse/

**Comment by cassondranewman** [comment]
@srubinacci 
I was having the same issue as @aheritas (see below). I wanted to see if I could change the directory name holding the headers from what it truly is 'htslib' to 'include' to better match documentation. When I ran make, I recieved the same error as before, leading me to believe htslib/hts.h was hard coded. 

So I this time I tried giving the directory underneath the one that holds the headers. This allowed the compilation to get farther along!! However it still failed ultimately (collect2: error: ld returned 1 exit status
make: *** [makefile:153: bin/GLIMPSE2_phase] Error 1). 


In file included from src/io/genotype_writer.h:29,
                 from src/io/genotype_writer.cpp:26:
src/utils/otools.h:54:10: fatal error: htslib/hts.h: No such file or directory
   54 | #include <htslib/hts.h>
      |          ^~~~~~~~~~~~~~
compilation terminated.
