### ISSUE TITLE
Question: WGS data of Epilepsy patients

### ISSUE THREAD

**Issue by robertzeibich** [odelaneau/GLIMPSE#113]
I have downsampled WGS data of Epilepsy patients from 30x to 10x. By just looking at pathogenic and likely pathogenic variants, I noticed a difference of 4 for seed1 and 5 for seed2. The gnomAD scores for these variants is below 0.01. Do you think that I can impute these missing pathogenic and likely pathogenic variants using GLIMPSE? Is there something I need to consider? 

Help would be much appreciated.

**Comment by srubinacci** [comment]
Hi,
Please feel free to reach us using our email addresses. This is usually used to ask assistance with the software.
