### ISSUE TITLE
compiling error boost options in GLIMPSE 2.0

### ISSUE THREAD

**Issue by karinkumar** [odelaneau/GLIMPSE#117]
Hello I am having the same issue as #47 , but with GLIMPSE 2. My error is undefined reference to `boost::program_options::value_semantic_codecvt_helper::parse(boost::any&, std::vector<std::__cxx11::basic_string<char, std::char_traits, std::allocator >, std::allocator<std::__cxx11::basic_string<char, std::char_traits, std::allocator > > > const&, bool) const'``

I checked my boost version and it is 1.65.1 so not sure what the problem is.  I saw a solution to this is Issue #47 which stated that you needed to downgrade from boost 1.76.  However this does not apply to me, and the documentation says boost must be 1.65 or greater. So theoretically, the boost version should not be a problem here.

I am compiling the code and have edited the DESKTOP section of the makefiles accordingly:

```
desktop: HTSSRC=~
desktop: HTSLIB_INC=$(HTSSRC)/htslib
desktop: HTSLIB_LIB=$(HTSSRC)/htslibs/libhts.a
desktop: BOOST_INC=/usr/include
desktop: BOOST_LIB_IO=/usr/lib/x86_64-linux-gnu/libboost_iostreams.a
desktop: BOOST_LIB_PO=/usr/lib/x86_64-linux-gnu/libboost_program_options.a
desktop: BOOST_LIB_SE=/usr/lib/x86_64-linux-gnu/libboost_serialization.a
desktop: $(BFILE)
```

I thought this might solve this issue: ( https://stackoverflow.com/questions/47232220/undefined-boost-reference), but I added this variable: `_GLIBCXX_USE_CXX11_ABI=0 `in the makefile and the issue still remains.

Do you have any suggestions as to how I can fix this?

**Comment by srubinacci** [comment]
Hi,

Thanks for your message.
I reckon that the compilation might be annoying for users, will work on it in the future. For now, I recommend you to follow these instructions: [boost](https://odelaneau.github.io/GLIMPSE/docs/installation/build_from_source/required_libraries#boost) to compile locally boost v1.73.

I just rerun everything on my machine and on an empty docker instance and I was able to compile GLIMPSE2 with no sudo requirements in a couple of minutes. 

You only have to point to the newly created "boost" folder in your makefile. If you installed boost in the folder "/home/user/test", you will have something like:

```
system: HTSSRC=/home/user/test
system: HTSLIB_INC=$(HTSSRC)/htslib_minimal
system: HTSLIB_LIB=$(HTSSRC)/htslib_minimal/libhts.a
system: BOOST_INC=/home/user/test/boost/include/
system: BOOST_LIB_IO=/home/user/test/boost/lib/libboost_iostreams.a
system: BOOST_LIB_PO=/home/user/test/boost/lib/libboost_program_options.a
system: BOOST_LIB_SE=/home/user/test/boost/lib/libboost_serialization.a
system: $(BFILE)
```

Let me know if this works for you. It should take just few minutes.

Will provide a release of GLIMPSE2 later today. I recommend to use the newest release as soon as it's ready.
