### ISSUE TITLE
Test data in nf-core

### ISSUE THREAD

**Issue by LouisLeNezet** [odelaneau/GLIMPSE#118]
Hi !

I'm currently working on the integration of glimpse phase on nf-core.
I have some trouble with the data test set to use.

When I try with partial data (either from the individual or the reference panel), I get the following error:
`ERROR: Number of samples in the reference panel: 0, exclusive samples (not in the target panel): 0`

I'm not quite familiar for the moment with Glimpse, but I checked for the presence of the regions in both files and augmented the window size, but it doesn't seems to work.
Do you have an idea why ?

Thanks

**Comment by srubinacci** [comment]
Hi,

Sorry for the delayed answer. This does not seem a problem of the region, but a problem regarding the number of samples in the files. You might want to check the reference panel you are using, and look at the number of samples in the file (e.g. with bcftools query -l ).
If everything seems fine, I will need you to post the command you use, if possible.

Best

Simone

**Comment by LouisLeNezet** [comment]
Hi,
Thanks for the answer. In fact the problem was coming from the files I was using (no individuals data in it, just a list of variant).

Thanks
