### ISSUE TITLE
Multiple samples by GLIMPSE2

### ISSUE THREAD

**Issue by YuxiaoRuoyao** [odelaneau/GLIMPSE#119]
Hi,

I'm trying to use multiple individuals to do imputation by GLIMPSE2. But I didn't see the corresponding instruction on the tutorial. I know in GLIMPSE1, we could merge the genotype likelihood for multiple individuals. However, GLIMPSE2 does not need the likelihood calculation step anymore and we only need to provide the low-coverage BAM file when running GLIMPSE2_phase. So is there any way to deal with multiple samples by GLMIPSE2?

Thank you so much!!

Best,
Ruoyao

**Comment by srubinacci** [comment]
Hi,

The input options are described here: https://odelaneau.github.io/GLIMPSE/docs/documentation/phase/
In particular GLIMPSE2 has three input options:

1.  --bam-file takes in input a single BAM file,
2.  --bam-list takes in input a list containing one BAM file per line,
3.  --input-gl takes in input the same (single or multi-sample) VCF/BCF file containing genotype likelihoods, same as  in GLIMPSE1.

Indeed, I should probably make this more clear in the tutorial.

For more details regarding how these options work, please refer to the link to the documentation above.
Let me know if you have more questions!

Best,

Simone
