### ISSUE TITLE
Glimpse2 Chunk illegal instruction

### ISSUE THREAD

**Issue by LouisLeNezet** [odelaneau/GLIMPSE#125]
Hi,

I'm starting the integration of Glimpse2 in nf-core.
I'm currently on the chunk module and I get the following error :
`.command.sh: line 8: 29423 Illegal instruction     GLIMPSE2_chunk --sequential --input 1000GP.chr21.noNA12878.s.bcf --region chr21 --threads 2 --output test.txt`
Do you know what is causing this ?

Edit: I tried to reproduce your tutorial, by building from source and the same error occurs `Illegal instruction`

**Comment by YuxiaoRuoyao** [comment]
I also have the same issue. GLIMPSE2_chunk is not the only one which will generate this error. Actually I tried GLIMPSE2_phase and it also had Illegal instruction error. But the error only appeared when trying to submit jobs by slurm script to the cluster. These command can run by normal command line. I'm confused about why this happens

**Comment by LouisLeNezet** [comment]
Hi @YuxiaoRuoyao !
I think I found the problem, at least for my user case.
I was also using slurm while getting this error.
I think the problem is the same as this [issue in SHAPEIT4](https://github.com/odelaneau/shapeit4/issues/28).
As I suggested for slurm, you can add the constraint `--constraint=avx2` when launching srun or sbatch.
I hope it will solve your case.

**Comment by srubinacci** [comment]
Thank you @LouisLeNezet for proposing this solution. 

Just to give a bit of context: indeed GLIMPSE2 uses AVX2 - (FMA - Fused Multiply-Accumulate](https://en.wikipedia.org/wiki/Multiply%E2%80%93accumulate_operation#Fused_multiply.E2.80.93add) operations to speedup HMM model computations. 
For this reason, it is compiled with the "-mavx2 -mfma" flags and needs to be run on relatively new machines (>2013).

AVX2 should be supported by most nodes on the cluster, but indeed, but for old clusters this can be a problem.
The solution proposed by Louis might indeed solve your issue, but it can also be specific to their platform/cluster. Their solution proposes to constrain the execution of GLIMPSE to specific machines that have AVX2 implemented. You can find a slightly more detailed description at this link (for a specific cluster): (LINK)[https://wiki.usask.ca/pages/viewpage.action?pageId=1620607096]

Let me know if this solves your problem!

**Comment by YuxiaoRuoyao** [comment]
Thank you so much @LouisLeNezet @srubinacci !! The avx2 operation also works for me and now it can run smoothly!
