### ISSUE TITLE
Running docker image fails

### ISSUE THREAD

**Issue by leedchou** [odelaneau/GLIMPSE#127]
Hi,

I tried running docker image you provided by a simple command "`docker run -it ghcr.io/odelaneau/glimpse/glimpse:1.0.0 /bin/sh`", however, it failed.

Could you please help me with that issue?

Thanks

**Comment by srubinacci** [comment]
Hi,
indeed. That is an old docker image, github meanwhile changed completely the way they manage docker images and for some reason that image does not work.
However, can you try loading these?

GLIMPSE v1.1.1:
```
wget https://github.com/odelaneau/GLIMPSE/releases/download/v1.1.1/glimpse_v1.1.1-c27e90d_20210521.tar.gz
docker load < glimpse_v1.1.1-c27e90d_20210521.tar.gz
docker run -it glimpse:v1.1.1-c27e90d_20210521
```
Now you should be able to run GLIMPSE1 tools using 'GLIMPSE_[tool name]_v1.1.1' from the docker (e.g. GLIMPSE_phase_v1.1.1)



GLIMPSE v2.0.0:
```
wget https://github.com/odelaneau/GLIMPSE/releases/download/v2.0.0/glimpse_v2.0.0-27-g0919952_20221207.tar.gz
docker load < glimpse_v2.0.0-27-g0919952_20221207.tar.gz
docker run -it glimpse:v2.0.0-27-g0919952_20221207
```
Now you should be able to run GLIMPSE2 tools using 'GLIMPSE2_[tool name]' from the docker (e.g. GLIMPSE2_phase)

Let me know if it works!

**Comment by srubinacci** [comment]
You can also try the new [Dockerhub images](https://hub.docker.com/r/simrub/glimpse/)
