### ISSUE TITLE
Output information: INFO field

### ISSUE THREAD

**Issue by BrianLohman** [odelaneau/GLIMPSE#128]
Hello,

I'm looking for some additional information about the output of GLIMPSE. I see the manuscript for v1 has a section titled "Output Information" that gives some details on the FORMAT field (page 19 of the preprint). However, I don't see anything about the INFO field. Specifically, I'd like to know how the INFO score (INFO/INFO) is calculated. The header reads:
```
##INFO=<ID=INFO,Number=A,Type=Float,Description="IMPUTE info quality score for diploid samples">
```
It's not clear to me how this value is calculated or how it should be interpreted. Any suggestions would be welcome. 

Thanks,

Brian

**Comment by srubinacci** [comment]
Hi,

The INFO score is a measure of imputation accuracy at the variant, introduced in the IMPUTE2 software (from which GLIMPSE somewhat derives). This metric takes values between 0 and 1, and values near 1 indicate that a SNP has been imputed with high certainty. The info metric is often used as a filter to remove poorly imputed SNPs from the association testing results in standard SNP array imputation settings. More information can be found in here (and many other papers actually): https://doi.org/10.1038/nrg2796. Supplementary information S3 might answer the latest part of your question.

**Comment by BrianLohman** [comment]
Hi Simone,

Thanks very much for the clarification and the reference. Much appreciated. 

Cheers,

Brian
