### ISSUE TITLE
ERROR: throwing an instance of boost::archive::archive_exception

### ISSUE THREAD

**Issue by diana13bg** [odelaneau/GLIMPSE#129]
Hi, I am trying to run a WDL on DNAnexus using the docker: glimpse_v2.0.0-27-g0919952_20221207.tar.gz
From the error log I get:
....
Initialisation:
  * Binary reference panel parsing ...
terminate called after throwing an instance of 'boost::archive::archive_exception'
  what():  unsupported version
/home/dnanexus/meta/commandScript: line 17:    31 Aborted                 (core dumped) GLIMPSE2_phase --bam-file [bam] --reference [split/xxx.bin] --output [bam_out] 
.....

Could it be because of missing or old boost package?
Do you know what is causing this?

**Comment by srubinacci** [comment]
Hi,

indeed, it might be a problem of the boost version used in the docker. Other users reported problems with that docker image. I should try to create a new one to see if that fixes the problem. Unfortunately I just relocated to another institution and do not have a proper machine to do it. Will update here as soon as possible. Sorry about that.

**Comment by srubinacci** [comment]
HI @diana13bg 
Can I ask you to use the following docker image (built on the latest commit), to see if it solves the problem?
https://drive.switch.ch/index.php/s/DGW4VBRmqhjwArB

Please re-run split_reference as well so we are ensuring that both programs are running using the same boost library.

Thanks!

**Comment by diana13bg** [comment]
Hi Simone,

This docker is working fine for me.

Thank you,
Diana ILIEV

**Comment by cdquinto** [comment]
Hello, I am getting this error when using the docker container (glimpse_v2.0.0-27-g0919952_20221207.tar.gz). 

Would it be possible to get access to the latest docker image that was shared here : https://drive.switch.ch/index.php/s/DGW4VBRmqhjwArB

Thanks

**Comment by srubinacci** [comment]
Hi,

I have created a pre-release:
https://github.com/odelaneau/GLIMPSE/releases/tag/v2.0.1

You can find a more recent docker image there.

Best,
Simone

**Comment by cdquinto** [comment]
Thank you! I will test it.

**Comment by cdquinto** [comment]
hello again. I am working with exome data (~200K sites) and despite using the new docker image, I am still getting an error when running `GLIMPSE2_split_reference`: 
```
Writing file...
terminate called after throwing an instance of 'boost::archive::archive_exception'
  what():  output stream error
Aborted (core dumped)
```
Could this be due to the size of chunks? I am currently using `--window-count 500 --buffer-count 100`. 

Any help would be appreciated.
