### ISSUE TITLE
rephase errors

### ISSUE THREAD

**Issue by ladand** [odelaneau/GLIMPSE#13]
there are a couple of issues with the rephase:

1)  this file `rephase/src/containers/genotype_set.h`  is missing 
2) `REPHASE_VERSION` is not defined in `GLIMPSE/versions/versions.h` and in the `src/rephaser/rephaser_parameters.cpp`,  the include statement should be changed `#include "../../versions/versions.h"` instead

**Comment by SimoneRubinacci** [comment]
Hi
Soon a new version of several programs will be released. Will take care this, thanks.

Thanks,
Simone

**Comment by odelaneau** [comment]
Just an additional comment: some of the glimpse "modules" are just experimental (e.g. rephase). These are exploratory and currently under development. Any module not described in the documentation should not be used or even compiled.

Best,

Olivier.
