### ISSUE TITLE
GLIMPSE2 avx2 running slow issue

### ISSUE THREAD

**Issue by YuxiaoRuoyao** [odelaneau/GLIMPSE#130]
Hi,

I had the problem for meeting GLIMPSE2 Illegal instruction error before when submitting the slurm file to the cluster. Thanks for your previous advice about adding #SBATCH --constraint=avx2 so that it can run now. 

However, I discovered the time after using avx2 node was much longer than directly ran it by command line. So I tried to ran GLIMPSE2_phase through command line and each chunk took about 20 minutes but by using avx2 node, each chunk took about 2 hours or more. I'm not familiar with the cpu node thing so is this the machine issue? How to make it running faster or at least about 20 minutes for each chunk?

Thank you so much!

**Comment by srubinacci** [comment]
Hi,

Interesting problem. Indeed, AVX2 is implemented on almost every cpu (as it is from more than 10 years ago) and I find it a bit odd that it runs but much slower than expected. Indeed the time you report are in line to non-avx2 vs avx2 code. 

Did you compile the code on your cluster? 
Also, just to try to understand what is happening, have you tried to use "--constraint=avx512" option? (just a bit of context, avx512 is a newer technology, so by doing this we pick only newer nodes).

**Comment by YuxiaoRuoyao** [comment]
Hi,

Thanks for the reply. Yep I have tried avx512 and it's still slower than running in local. I checked the output and I saw the main running time difference is from the HMM imputation part. For instance, by avx512, HMM imputation for one main iteration used 158s but in command line, it only used 42s. So basically it still much slower than non-avx node. 

About the compiling, I'm not so sure the meaning for that. What I have done now is to write the code in a .sh file with some slurm argument (like --constraint, --mem). And then sbatch file to the cluster or directly run this file in local by ./filename

Thank you very much!

**Comment by srubinacci** [comment]
Hi,

Interesting, it really might be the specific CPU of your compute nodes. 
What I was trying to ask is: did you compile the code yourself or did you use a static binary file? Maybe compiling the code on your cluster (maybe optimized with your hardware) might speedup the performance. 

Maybe your IT manager can help compiling GLIMPSE optimised for your platform.

Hope this helps

Simone

**Comment by srubinacci** [comment]
Given no follow-up on this, I close the issue for now. Feel free to reopen.
