### ISSUE TITLE
GLIMPSE_chunk segmentation fault depending of algorithm

### ISSUE THREAD

**Issue by LouisLeNezet** [odelaneau/GLIMPSE#132]
Hi,

When using `GLIMPSE2_chunk` from [bioconda](https://anaconda.org/bioconda/glimpse-bio) on a small region of a chromosome, I run in a segmentation fault.
The problem seems to come from the size of the region.
I tested with different regions size and it worked for 10Mb, 5Mb but not for 2Mb, 3.5Mb, 4Mb.
Is it something expected ?
I thought that reducing the buffer and window would correct that but it doesn't seems to be the case.

It also seems to depend of the algorithm used.
With the same command with a region of 4Mb:
`GLIMPSE2_chunk --input data/panel/1000GP.chr21.noNA12878.s.vcf.gz --output test.txt --[recursive/sequential] --region chr21`
It will work with a recursive algorithm but not the sequential one.

Is their a reason for that ?
Thanks for your insights

Here is the error
```
[GLIMPSE2] Split chromosomes into chunks
  * Authors              : Simone RUBINACCI & Olivier DELANEAU, University of Lausanne
  * Contact              : simone.rubinacci@unil.ch & olivier.delaneau@unil.ch
  * Version              : GLIMPSE2_chunk v2.0.0 / commit = 2.0.0 / release = 2023-01-30
  * Citation             : BiorXiv, (2022). DOI: https://doi.org/10.1101/2022.11.28.518213
  *                      : Nature Genetics 53, 120–126 (2021). DOI: https://doi.org/10.1038/s41588-020-00756-0
  * Run date             : 24/02/2023 - 17:46:39

Files:
  * Input VCF            : [data/panel/1000GP.chr21.noNA12878.s.vcf.gz]
  * Region               : [chr21]
  * Output file          : [test.txt]

Parameters:
  * Sparse MAF           : [0.001]
  * Algorithm            : [Sequential]
  * Recombination rates  : [Constant rate of 1cM/Mb]
  * Min. Window size     : [4cM | 4Mb | 30000 variants]
  * Min. Buffer size     : [0.5cM | 0.5Mb | 3000 variants]

Other parameters
  * Seed                 : [15052011]
  * #Threads             : [1]

Reading input files
  * Input file read      : [data/panel/1000GP.chr21.noNA12878.s.vcf.gz] (21.35s)
  * #variants            : [111565 total | 54311 rare | 57254 common]
  * Genetic map          : [Not provided]
  * Map cM constant      : [1cM=1Mb] (0.00s)
  * Region spans 3999981 bp and 5.00 cM

Splitting data into chunks and writting to [test.txt]
Segmentation fault
```

**Comment by srubinacci** [comment]
Hi,

I think it might be a combination of these options with the small size of your data. Of course a segfault is really uninformative and I should be more careful here, but I am unsure why you are also chunking this small 3Mb region (of 5cM).

Unfortunately, I just relocated and still don't have access to a machine where I can actually fix these issues. I will update you as soon as I am in the condition to look at the code (hopefully next week?).

**Comment by LouisLeNezet** [comment]
Hi,
I needed to test on a really small dataset for nf-core integration.
But as it works on bigger one they shouldn't be any problem.

Thanks

**Comment by srubinacci** [comment]
Hi Louis,
I have just looked at this and now GLIMPSE should handle this case. I've just pushed a fix in the main branch.
There will be a new release with these bugfixes coming up soon. Stay tuned!

**Comment by LouisLeNezet** [comment]
Thanks a lot !
