### ISSUE TITLE
ERROR: No variants to be imputed in files

### ISSUE THREAD

**Issue by chvbs2000** [odelaneau/GLIMPSE#133]
I was trying to impute a multiple-sample VCF file but got this error:

```
[GLIMPSE] Phase and impute low coverage sequencing data
  * Author        : Simone RUBINACCI & Olivier DELANEAU, University of Lausanne
  * Contact       : simone.rubinacci@unil.ch & olivier.delaneau@unil.ch
  * Version       : 1.1.0
  * Run date      : 02/03/2023 - 23:38:35

Parameters:
  * Seed       : 15052011
  * #Threads   : 1
  * #Burnin    : 10
  * #Main      : 10
  * PBWT depth : 2
  * PBWT modulo: 8
  * HMM     : Recombination rates given by genetic map
  * Ploidy     : All samples are diploids in this region
  * Init K     : 1000

Initialization:

Parsing specified genomic regions
  * Input region  [chr22:16050075-18847959]
  * Output region  [chr22:16050075-18647941]
  * #samples = 961 [0 haploids/ 961 diploids]

ERROR: No variants to be imputed in files
```

I was making sure target chromosome shares same annotation in both input VCF, reference VCF, and map, for example:

Input VCF:
```
22      17274435        .       C       T       .       .       .       GT:DS:PL        0/0:0.3588:0,2,19       0/1:1.2042:5,0,1        0/1:1.2042:5,0,1        0/0:0.3588:0,2,19       0/1:1.2042:5,0,1        0/1:1.2042:5,0,1        0/0:0.3588:0,2,19       
```

Reference VCF:
```
22      16050075        .       A       G       100     PASS    AC=1;AF=0.000199681;AN=5008;NS=2504;DP=8012;EAS_AF=0;AMR_AF=0;AFR_AF=0;EUR_AF=0;SAS_AF=0.001;AA=.|||;VT=SNP     GT      0|0     0|0     0|0     0|0     0|0     0|0     0|0     0|0     0|0  
```

Map:
```
pos     chr     cM
16051347        22      0.000000
16052618        22      0.010291
16053624        22      0.018472
16053659        22      0.018756
16053758        22      0.019561
16054713        22      0.027325
16054960        22      0.029307
16055070        22      0.030190
```

Not sure if I miss any details in VCF file that requires by GLIMPSE imputation? Any thought would be helpful thanks.

**Comment by LouisLeNezet** [comment]
Hi,
I had the same problem.
The region where I tried to impute was to small.
Maybe you should try to increase the size of the input and output region ?

**Comment by srubinacci** [comment]
Hi

I think the files might not overlap.
Can you run `bcftools isec -w1 -n=2 INPUT.vcf.gz REFERENCE.vcf.gz -Ou | bcftools view -H | wc -l` to see how many variants are in the intersection of the files?

Thanks.

Simone

**Comment by chvbs2000** [comment]
Hi Louis and Simone, 

Thanks for the suggestion, I ran the command line as suggested and it seems no overlap regions between reference panel and input. So just happy to confirm GLIMPSE imputes no variants if the region only exists in reference file but not input file? Thanks.

**Comment by srubinacci** [comment]
That is indeed a wanted behavior. Your genotype likelihoods should have been computed at all reference panel positions (so that they would be present, but maybe with PL set to missing if no reads cover the position).
If your genotype likelihood file does not contain reference panel positions, you might want to recompute your likelihoods.
If that is not possible, or you are absolutely sure there are no reads in that position, you can use the [--impute-reference-only-variants](https://odelaneau.github.io/GLIMPSE/glimpse1/commands.html). I remind you that this should be used with caution as it is meant for sporadic missing data and this does not seem to be your case.
