### ISSUE TITLE
ERROR: No variant found in region.

### ISSUE THREAD

**Issue by Daxide** [odelaneau/GLIMPSE#138]
I downloaded the 1000 genomes chr22 reference panel file for hg19 from http://ftp.1000genomes.ebi.ac.uk/vol1/ftp/release/20130502/
then I converted it to bcf using bcftools with the code provided in the tutorial. Then I tried to split the genome into chunks but I run into the following error: 
./GLIMPSE2_chunk_static --input 1000GP.chr22.hg19.sites.vcf.gz --region chr22 --sequential --output chunks.chr22.txt --map ./maps/genetic_maps.b37/chr22.b37.gmap.gz

[GLIMPSE2] Split chromosomes into chunks
  * Authors              : Simone RUBINACCI & Olivier DELANEAU, University of Lausanne
  * Contact              : simone.rubinacci@unil.ch & olivier.delaneau@unil.ch
  * Version       : GLIMPSE2_chunk v2.0.0 / commit = 3bed6d9 / release = 2022-12-07
  * Citation         : BiorXiv, (2022). DOI: https://doi.org/10.1101/2022.11.28.518213
  *                 : Nature Genetics 53, 120–126 (2021). DOI: https://doi.org/10.1038/s41588-020-00756-0
  * Run date       : 17/03/2023 - 16:25:33

Files:
  * Input VCF            : [1000GP.chr22.hg19.sites.vcf.gz]
  * Region               : [chr22]
  * Genetic Map          : [./maps/genetic_maps.b37/chr22.b37.gmap.gz]
  * Output file          : [chunks.chr22.txt]

Parameters:
  * Sparse MAF           : [0.001]
  * Algorithm            : [Sequential]
  * Recombination rates  : [Given by genetic map]
  * Min. Window size     : [4cM | 4Mb | 30000 variants]
  * Min. Buffer size     : [0.5cM | 0.5Mb | 3000 variants]

Other parameters
  * Seed                 : [15052011]
  * #Threads             : [1]

Reading input files
  * Input file read      : [1000GP.chr22.hg19.sites.vcf.gz] (0.00s)
  * #variants            : [0 total | 0 rare | 0 common]
  * Genetic map          : [n=45329] (0.03s)

ERROR: No variant found in region.

**Comment by srubinacci** [comment]
Hi, 
If I am not missing something, this is correct behavior of the software. 
You need to use the correct chromosome encoding to extract regions, similar to bcftools -r.
In this case, the 1000 genomes data you downloaded is in build GRCh37 / hg19 while I believe you are using the tutorial for using GRCh38. The builds have different ways to encode chromosomes: in your case you are using "chr22" while you should use only "22" as your data is in hg19.
This should solve your problem.

Best,
Simone

**Comment by Daxide** [comment]
Thanks! It worked
