### ISSUE TITLE
HLA imputation

### ISSUE THREAD

**Issue by sashagusev** [odelaneau/GLIMPSE#14]
Dear Simone, I am very interested to use GLIMPSE for lage-scale imputation and I was curious how well it handles non-standard imputation targets such as HLA alleles (for example, using reference panels such as this: http://software.broadinstitute.org/mpg/snp2hla/). The constraint being that the reference alleles are **never observed** in the target data, although they do reside on haplotypes and are tagged by SNPs just as with ordinary polymorphisms.

With other low-pass imputation methods we have not had success imputing HLA alleles directly and had to resort to two passes: first impute the genotypes from the reads, then impute the HLA alleles from the genotypes, which is obviously suboptimal in the way noise gets propogated. Appreciate any experience or suggestions you have for this kind of analysis.

Thanks!
Sasha

**Comment by SimoneRubinacci** [comment]
Hi Sasha,

Glad you are interested in using GLIMPSE! 
Very good question. We haven't looked at HLA explicitly (it's definitively in the TODO list by the way), but I believe the model would be appropriate even in that region. As a quick check, I computed the imputation accuracy in the MHC region (https://www.ncbi.nlm.nih.gov/grc/human/regions/MHC) comparing imputed data with 30x genotypes. Surprisingly, imputation accuracy seems to be pretty good, and only slightly worse than other regions. Further tests should be performed (and comparisons with other software like snp2hla) but it seems that it performs well.

However I can see potential sources of problems:
1. GLIMPSE has not support for multiallelic positions
2. The likelihood computation (that we delegate to other methods like GATK or bcftools) for variants in the HLA region might be problematic. Of course GLIMPSE depends on those likelihoods. 

We are interested in investigating this further. Feel free to drop me an email if you have some interest to verify this with us. 

Best wishes,

Simone

**Comment by sashagusev** [comment]
Thanks Simone, that's very helpful and thanks for checking the locus. The main concern I had was whether GLIMPSE would get confused when thh frequencies between the reference and target population are very different (i.e. in this case there would be many common HLA alleles in the reference that are all absent from the target data). It sounds like this should not be an issue. We'll just give it a shot on our end and let you know how it goes.
