### ISSUE TITLE
Segmentation fault on GLIMPSE2_concordance

### ISSUE THREAD

**Issue by zmaroti** [odelaneau/GLIMPSE#140]
> GLIMPSE2_concordance --input CSPF-114_05x_list.txt  --output output/test --min-val-dp 0 --min-val-gl 0.9999 --bins 0.00000 0.00100 0.00200 0.00500 0.01000 0.05000 0.10000 0.20000 0.50000 --af-tag AF --thread 4

[GLIMPSE2] Check concordance of imputed data
  * Authors              : Simone RUBINACCI & Olivier DELANEAU, University of Lausanne
  * Contact              : simone.rubinacci@unil.ch & olivier.delaneau@unil.ch
  * Version              : GLIMPSE2_concordance v2.0.0 / commit = 3bed6d9 / release = 2022-12-07
  * Citation             : BiorXiv, (2022). DOI: https://doi.org/10.1101/2022.11.28.518213
  *                      : Nature Genetics 53, 120–126 (2021). DOI: https://doi.org/10.1038/s41588-020-00756-0
  * Run date             : 21/03/2023 - 17:22:14

Files are listed in [CSPF-114_05x_list.txt]

Parameters:
  * Output            : output/test
  * Seed              : 15052011
  * #Threads          : 4
  * Min validation GL : 0.9999
  * Min validation DP : 0
  * Using INFO/AF tag for allele frequency bins.
  * #bins             : 9
  * Output r2 per site: NO
  * Output rej. sites : NO
  * Output conc sites : NO
  * Output disc sites : NO

Initializing engine based on allele frequency bins:
  * Validation GL Probs >= 0.9999
  * Validation Depth    >= 0
  * #AF bins = 8
  * AF bins [0 0.001 0.002 0.005 0.01 0.05 0.1 0.2 0.5]

Reading list of input files in [CSPF-114_05x_list.txt]
  * 22 sets of files detected

--- Concordance started ---

Reading set of input files [1/22]
  * Truth       [../imputed_full/CSPF-114_truth_chr1_fixed.bcf]
  * Estimates   [../imputed_test/CSPF-114_05x_chr1_fixed.bcf]
  * Frequencies [../freq/chr1.bcf]
  * Region      [1]
  * FPLOIDY = 2 [Only diploid samples in the region]
  * #overlapping samples = 1 [0 haploids/ 1 diploid]
Segmentation fault (core dumped)

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
Additional information about the BCF files used as Truth, Estimates, and Frequencies.

Both Truth and Estimates were generated by GLIMPSE2_phase. The truth "CSPF-114_truth_chr1_fixed.bcf" was phased from the original high coverage (16x) BAM, while the Estimate was generated from a downscaled (0.5x genome coverage) version of the same file. In both files the sample ID are identical (CSPF-114).

Compared to the tutorial there is no DP information at the Truth file as it was generated by GLIMPSE2_phase and not from bcftools/GATK variant calling pipeline. Hence we changed "--min-val-dp 0" option to use all sites. Notably compared to the tutorial our Truth file has GT:DS:GP FORMAT tags and PHASED genotypes, while in the tutorial the truth file has GT:PL:DP tags and UNPHASED genotypes.

The frequencies file was generated from the original 1Kg data set chromosome 1 variants (GRCh37). Our original 1KG data has AF tag in the INFO instead of AF_nfe as in the tutorial gnomad bcf data. Hence we changed "--af-tag AF" to represent this.

In all three bcf files the genotyped coordinates are exactly the same, and also in the order.

In our list file we have one row for each chromosomes, something like this:
1 ../freq/chr1.bcf ../imputed_full/CSPF-114_truth_chr1_fixed.bcf ../imputed_test/CSPF-114_05x_chr1_fixed.bcf
2 ../freq/chr2.bcf ../imputed_full/CSPF-114_truth_chr2_fixed.bcf ../imputed_test/CSPF-114_05x_chr2_fixed.bcf
3 ../freq/chr3.bcf ../imputed_full/CSPF-114_truth_chr3_fixed.bcf ../imputed_test/CSPF-114_05x_chr3_fixed.bcf
4 ../freq/chr4.bcf ../imputed_full/CSPF-114_truth_chr4_fixed.bcf ../imputed_test/CSPF-114_05x_chr4_fixed.bcf
5 ../freq/chr5.bcf ../imputed_full/CSPF-114_truth_chr5_fixed.bcf ../imputed_test/CSPF-114_05x_chr5_fixed.bcf
6 ../freq/chr6.bcf ../imputed_full/CSPF-114_truth_chr6_fixed.bcf ../imputed_test/CSPF-114_05x_chr6_fixed.bcf
7 ../freq/chr7.bcf ../imputed_full/CSPF-114_truth_chr7_fixed.bcf ../imputed_test/CSPF-114_05x_chr7_fixed.bcf
8 ../freq/chr8.bcf ../imputed_full/CSPF-114_truth_chr8_fixed.bcf ../imputed_test/CSPF-114_05x_chr8_fixed.bcf
9 ../freq/chr9.bcf ../imputed_full/CSPF-114_truth_chr9_fixed.bcf ../imputed_test/CSPF-114_05x_chr9_fixed.bcf
10 ../freq/chr10.bcf ../imputed_full/CSPF-114_truth_chr10_fixed.bcf ../imputed_test/CSPF-114_05x_chr10_fixed.bcf
11 ../freq/chr11.bcf ../imputed_full/CSPF-114_truth_chr11_fixed.bcf ../imputed_test/CSPF-114_05x_chr11_fixed.bcf
12 ../freq/chr12.bcf ../imputed_full/CSPF-114_truth_chr12_fixed.bcf ../imputed_test/CSPF-114_05x_chr12_fixed.bcf
13 ../freq/chr13.bcf ../imputed_full/CSPF-114_truth_chr13_fixed.bcf ../imputed_test/CSPF-114_05x_chr13_fixed.bcf
14 ../freq/chr14.bcf ../imputed_full/CSPF-114_truth_chr14_fixed.bcf ../imputed_test/CSPF-114_05x_chr14_fixed.bcf
15 ../freq/chr15.bcf ../imputed_full/CSPF-114_truth_chr15_fixed.bcf ../imputed_test/CSPF-114_05x_chr15_fixed.bcf
16 ../freq/chr16.bcf ../imputed_full/CSPF-114_truth_chr16_fixed.bcf ../imputed_test/CSPF-114_05x_chr16_fixed.bcf
17 ../freq/chr17.bcf ../imputed_full/CSPF-114_truth_chr17_fixed.bcf ../imputed_test/CSPF-114_05x_chr17_fixed.bcf
18 ../freq/chr18.bcf ../imputed_full/CSPF-114_truth_chr18_fixed.bcf ../imputed_test/CSPF-114_05x_chr18_fixed.bcf
19 ../freq/chr19.bcf ../imputed_full/CSPF-114_truth_chr19_fixed.bcf ../imputed_test/CSPF-114_05x_chr19_fixed.bcf
20 ../freq/chr20.bcf ../imputed_full/CSPF-114_truth_chr20_fixed.bcf ../imputed_test/CSPF-114_05x_chr20_fixed.bcf
21 ../freq/chr21.bcf ../imputed_full/CSPF-114_truth_chr21_fixed.bcf ../imputed_test/CSPF-114_05x_chr21_fixed.bcf
22 ../freq/chr22.bcf ../imputed_full/CSPF-114_truth_chr22_fixed.bcf ../imputed_test/CSPF-114_05x_chr22_fixed.bcf

It is likely that the seg fault is due to using PHASED data as truth (parser is not ready for 0|1 1|0 GT-s iand only understands the official  0/1 vcf spec). Or may be it could be also that we have no DP FORMAT tag in our Truth bcf and even when the filter is set to DP=0 the parser looks for the tag and dies if it is not existing in the FORMAT tags.

We could likely genotype our data with bcftools, however (unless we missed some flags) bcftools DOES NOT emit HOM REF calls even with the "   -i, --insert-missed             Output also sites missed by mpileup but present in -T" flag set.

It would be nice if we could calculate concordance between two phased output. Seemingly the only obstacle is technical and not that the data is not suitable for this.

**Comment by zmaroti** [comment]
Reading through the doc it could be also the case that valdiation data set (by default needs a GL tag) that is missing from our phased data. However the GP tag is very similar concept in the phased data that stands for the posterior genotype likelihoods so may be there should be an option in GLIMPSE2_concordance somthing like "--gp-val" to use the GP tags for the validation data (in this case -min-val-gl arg could be either kept or additionally a -min-val-gp arg option implemented to sign this distinction).

**Comment by zmaroti** [comment]
Changing the command to
GLIMPSE2_concordance --input CSPF-114_05x_list.txt --output output/test --gt-val --bins 0.00000 0.00100 0.00200 0.00500 0.01000 0.05000 0.10000 0.20000 0.50000 --af-tag AF --thread 4

seemingly works OK. Only drawback is that there is no control on filtering on the GL/GP tags.

**Comment by srubinacci** [comment]
Hi, 
indeed I think it's because it's expecting the PL field (as you have --min-val-gl set to 0.9999) but cannot find it. Indeed --gt-val would just use the GT field and that should solve the problem. Indeed I have never thought of adding an option for GP instead of PL, as GP is typically the output of imputed data. I reckon that a segfault does not help at all in this case and I should probably handle this better.

For example asking directly the field to take validation data from, one of {GT, PL, GL or GP} and simply check and output proper error messages if the field is not found. I might try to include this soon.
Thanks!

Simone
