### ISSUE TITLE
target SNPs show less after imputation by GILMPSE1

### ISSUE THREAD

**Issue by ymeili** [odelaneau/GLIMPSE#141]
Hi, I was using GLIMPSE1 to impute my data, however, when I go to quality control step, it shows less SNPs compared with the original file. I was confused about the result, and when I run GLIMPSE, no error occurred. Did you encounter the familiar situation?

**Comment by srubinacci** [comment]
Hi,
I am not sure I understand the problem. Do you mean that the concordance does not use all the imputed snps?
