### ISSUE TITLE
Requesting static binary with the latest version commits glimpse2 [ERROR: States for individual 0 are zero. Error during selection. ]

### ISSUE THREAD

**Issue by kvaddad1** [odelaneau/GLIMPSE#142]
Hi Team, 
I was trying to run glimpse2 based GLIMPSE2_split_reference_static on my input reference panel vcf file. I got the following error 
`ERROR: AC/AN INFO fields in VCF are inconsistent with GT field, update the values in the VCF`

Also, my reference file is not very big, so I tried skipping split_reference and tried running ./bin/GLIMPSE2_phase_static  which also pointed to the same issue as follows. 
`ERROR: AC/AN INFO fields in VCF are inconsistent with GT field, update the values in the VCF`
Can you please guide me on how can i rectify for running glimpse2 successfully on my input vcf files. Thank you so much.

**Comment by kvaddad1** [comment]
I have corrected the VCF file manually to make the AC/AN fields consistent with the GT fields.  GLIMPSE2_split_reference_static went through successfully, but now I am getting segmentation fault on GLIMPSE_phase_static module with the following error. 
`ERROR: Problem reading binary file format [v2.0.0]
`
Can you please suggest how can I fix the input vcfs to make glimpse2 work. Thank you so much.

**Comment by srubinacci** [comment]
Hi, 
You don't need to fix your vcf file manually. Bcftools does this for you using `bcftools view -c 0` or `bcftools +fill-tags`.

Indeed, a binary reference panel is only useful if you have thousands of samples. Have you tried to use GLIMPSE_phase directly from the reference panel il VCF format?

Feel free to add more details if you cannot fix the problem.

You might also want to use one of the latest commit versions if your reference panel is small - let me know if you need a static binary with the latest version.

**Comment by kvaddad1** [comment]
@srubinacci Thank you so much for your kind response. 
With your suggested commands, I could successfully eliminate all my above stated ERRORs. I got the following ERROR in the last step of impute 
`ERROR: States for individual 0 are zero. Error during selection.
`
I have seen a previous issue discussion on this ERROR. In my case, my panel vcf file contains 34 samples and 1 sample in the input VCF file to be imputed. As suggested by you, since my panels very small - I directly ran the GLIMPSE_phase command as provided in Tutorials as follows (I am running my analysis on a single chr21 - chunks file was generated from the chunking commond in tutorial). 
```
REF=${1}
VCF=${2}
while IFS="" read -r LINE || [ -n "$LINE" ]; 
do   
	printf -v ID "%02d" $(echo $LINE | cut -d" " -f1)
	IRG=$(echo $LINE | cut -d" " -f3)
	ORG=$(echo $LINE | cut -d" " -f4)
	CHR=$(echo ${LINE} | cut -d" " -f2)
	REGS=$(echo ${IRG} | cut -d":" -f 2 | cut -d"-" -f1)
	REGE=$(echo ${IRG} | cut -d":" -f 2 | cut -d"-" -f2)
	OUT=glimpse2_imputed_file/
       ./bin/GLIMPSE2_phase_static --input-gl ${VCF} --reference ${REF} --input-region ${IRG} --output-region ${ORG} --output ${OUT}_${CHR}_${REGS}_${REGE}.bcf --log logfile
done < chunks.chr21.txt 
```

`ERROR: States for individual 0 are zero. Error during selection.
`
In my current experiments, my main objective is to showcase the glimpse2 based improved accuracies on my data but my reference panels are small only as mentioned above. My current static bins version details are as follows.
`  * Version       	 : GLIMPSE2_phase v2.0.0 / commit = 3bed6d9 / release = 2022-12-07
`
Any suggestion to overcome the above ERROR is greatly appreciated, Thanks a ton!.

**Comment by kvaddad1** [comment]
Hi @srubinacci 
As you said, I am guessing newest version static binaries would greatly help my case. Can you please help sharing the same. Thank you so much.

**Comment by srubinacci** [comment]
Hi, sorry for coming back to you only now. 
I will be able to give you a static binary early next week.

You can download a recent docker image here, meanwhile: https://drive.switch.ch/index.php/s/hZN8NtTtqSGlrSF

**Comment by srubinacci** [comment]
Hi,

I have created a pre-release:
https://github.com/odelaneau/GLIMPSE/releases/tag/v2.0.1

You can find a more recent docker image/static binaries there.

Best,
Simone
