### ISSUE TITLE
Effect Sample Size in GLIMPSE 1.0 default?

### ISSUE THREAD

**Issue by karinkumar** [odelaneau/GLIMPSE#145]
Hello, 

what is the default for the n_e in GLIMPSE 1.0? I can't find the value in the documentation or in the 2021 Nature Genetics paper.

**Comment by srubinacci** [comment]
Hi,

The default option is 20000. You can check the default option using GLIMPSE_phase --help

Best
Simone

**Comment by karinkumar** [comment]
Thank you!
