### ISSUE TITLE
No variant found in region

### ISSUE THREAD

**Issue by a-kwakye** [odelaneau/GLIMPSE#146]
Hi, 

I'm running the following 
GLIMPSE2_chunk --sequential --region chrIV  --input  GA_WGS_170_recalibrated_Snps6mil_chrIV.phasedhaps_maf.recode.vcf.gz --output chunks.chrIV.txt   --map Chrom_chrIV.gmap

and I keep getting the ERROR: No variant found in region. 
Could you help resolve this issue of no variant found when I try to chunk. 
Here is the vcf I'm trying to chunk. 
[GA_WGS_170_recalibrated_Snps6mil_chrIV.phasedhaps_maf.recode.vcf.gz](https://github.com/odelaneau/GLIMPSE/files/11278986/GA_WGS_170_recalibrated_Snps6mil_chrIV.phasedhaps_maf.recode.vcf.gz)

**Comment by srubinacci** [comment]
Hi,

Interesting, I tried to run it and it worked correctly on my side (without the genetic map), but I used the version from the latest commit. What version are you using?

**Comment by a-kwakye** [comment]
I get the same issue when I run without the map file as well. I'm using GLIMPSE2_chunk v2.0.0 / commit = 3bed6d9 / release = 2022-12-07

**Comment by srubinacci** [comment]
Can you try to use the latest version (attaching a static exe here)? 
[GLIMPSE2_chunk_static.zip](https://github.com/odelaneau/GLIMPSE/files/11327231/GLIMPSE2_chunk_static.zip)

**Comment by a-kwakye** [comment]
It still doesn't work, unfortunately. It now throws up 

Do you think it's because there's no AC/AN info? It complained  about this before (ERROR: VCF/BCF needs AC/AN INFO fields to be present), and I manually edited the header to include the following two lines: 

##INFO=<ID=AC,Number=A,Type=Integer,Description="Allele count in genotypes, for each ALT allele">
##INFO=<ID=AN,Number=1,Type=Integer,Description="Total number of alleles in called genotypes">
[Arc-18-X-083-A11_gatk.vcf.gz](https://github.com/odelaneau/GLIMPSE/files/11335895/Arc-18-X-083-A11_gatk.vcf.gz)

After this, it gave me the no variants found error.

It seems to work (both the static and the version v2.0.0) and  on a different, smaller vcf file (attached) generated with gatk haplotypecaller with AC/AN fields. 
[Arc-18-X-083-A11_gatk.vcf.gz](https://github.com/odelaneau/GLIMPSE/files/11335899/Arc-18-X-083-A11_gatk.vcf.gz)




Here's the full output when I try to run with the static using this command[it's the same with or without the map file]: 
./GLIMPSE2_chunk_static  --sequential \
--region chrIV --input GA_WGS_170_recalibrated_Snps6mil_chrIV.phasedhaps_maf.recode.vcf.gz \
 --map Chrom_chrIV.gmap \
--output chunks.chrIV.txt 


[GLIMPSE2] Split chromosomes into chunks
  * Authors              : Simone RUBINACCI & Olivier DELANEAU, University of Lausanne
  * Contact              : simone.rubinacci@unil.ch & olivier.delaneau@unil.ch
  * Version       	 : GLIMPSE2_chunk v2.0.0 / commit = 88915f7 / release = 2023-04-24
  * Citation	         : BiorXiv, (2022). DOI: https://doi.org/10.1101/2022.11.28.518213
  *         	         : Nature Genetics 53, 120–126 (2021). DOI: https://doi.org/10.1038/s41588-020-00756-0
  * Run date      	 : 26/04/2023 - 14:06:59

Files:
  * Input VCF            : [GA_WGS_170_recalibrated_Snps6mil_chrIV.phasedhaps_maf.recode.vcf.gz]
  * Region               : [chrIV]
  * Genetic Map          : [Chrom_chrIV.gmap]
  * Output file          : [chunks.chrIV.txt]

Parameters:
  * Sparse MAF           : [0.001]
  * Algorithm            : [Sequential]
  * Recombination rates  : [Given by genetic map]
  * Min. Window size     : [2.5cM | 2Mb | 20000 variants]
  * Min. Buffer size     : [0.5cM | 0.4Mb | 2000 variants]

Other parameters
  * Seed                 : [15052011]
  * #Threads             : [1]

Reading input files
  * Reading              : [GA_WGS_170_recalibrated_Snps6mil_chrIV.phasedhaps_maf.recode.vcf.gz] ...
ERROR: VCF/BCF needs AC/AN INFO fields to be present

**Comment by srubinacci** [comment]
Hi, 
indeed, that is correct. The AC/AN is needed using GLIMPSE2 due the division between common and rare variant that is the core of GLIMPSE2. 

You can simply use bcftools to update the AC/AN field by using 
`bcftools view -c 0 INPUT.vcf.gz -Oz -o OUTPUT.vcf.gz`

Glad to see it works!

**Comment by a-kwakye** [comment]
Awesome! It works now. Thank you very much.
