### ISSUE TITLE
Output information: FORMAT/GQ field 

### ISSUE THREAD

**Issue by BrianLohman** [odelaneau/GLIMPSE#150]
Hello,

I'm looking for more information about the FORMAT/GQ field. I understand this to be the post-imputation genotype quality. I pulled the FORMAT/GQ field out of an example variant with cycvf2 and it looks they are integers and likely bounded by 0 and 100 (though 2 and 99 were the most extreme values I've seen). I assume that low numbers are bad and high numbers are good but beyond this I'm not sure how to interpret these values. I checked the GLIMPSE2 preprint and I didn't see anything. Is there somewhere else I can find more information about interpreting and using the GQ filed for variant QC? 

Thanks for your help, 

Brian

**Comment by srubinacci** [comment]
Hi Brian, 

The GQ field is typically used in the context of genotype calling, e.g. defivation of genotype likelihoods (GLs), and not really in genotype imputation. As you probably know, the PL field encodes phread-scaled GLs. The GQ field is simply the difference between the second-best GL and the best GL - (always equal to zero as it is phread-scaled). Higher this difference, higher is the certainty in the best GL (more reads are supporting a specific genotype), therefore better the genotype calling is. This quantity is routinely reported by genotype callers like GATK. You can find more documentation on the GATK website.

In the case of GLIMPSE (but in all imputation tools I know), we do not report the GQ as we do not output the GLs, but we usually report is genotype probabilities (GP), as a result of running a probabilistic model (HMM) starting from the GLs (haploid, for computational reasons) and using a reference panel of haplotypes. What is usually used for post-imputation genotype quality is the INFO score. 

Hope this helps, let me know if you have more questions.

Best 

Simone

**Comment by BrianLohman** [comment]
Hi Simone,

Thanks for your quick reply and the detailed explanation. I'm using the DRAGEN variant calling and accelerated GLIMPSE imputation pipeline and it sounds like that might be causing my confusion. It looks like the GQ filed is updated after imputation so I'm trying to understand that. 

Here is an example SNP from the variant calling step and then again after imputation:

```
# prior to imputation 
chr1    10097   .       T       A       0.00    DRAGENSnpHardQUAL;LowDepth      AC=0;AF=0.000;AN=2;DP=1;FS=0.000;MQ=8.00;QD=0.00;SOR=0.223;FractionInformativeReads=1.000;FGT   GT:AD:AF:DP:F1R2:F2R1:GQ:PL:GP:PRI:SB:MB        0/0:1,0:0.000:1:1,0:0,0:34:0,1,2:1.5438e-03,3.5835e+01,4.0246e+01:0.00,34.77,37.77:0,1,0,0:0,1,0,0

# after imputation
chr1    10097   .       T       A       .       .       RAF=0.000399521;AF=0.0015;INFO=0.002    GT:DS:GP:HS:GQ:ORIGIN   0/0:0.003:0.997,0.003,0:0:25:IMP
```

where the hard called GQ of 34 gets reduced to 25 but note the very low INFO score (0.002).

Here is another example with an INFO score of 1
```
# prior to imputation
chr1    10418   .       C       G       0.00    DRAGENSnpHardQUAL;LowDepth      AC=0;AF=0.000;AN=2;DP=2;FS=0.000;MQ=7.21;QD=0.00;SOR=0.693;FractionInformativeReads=0.000;FGT   GT:AD:AF:DP:F1R2:F2R1:GQ:PL:GP:PRI:SB:MB        0/0:0,0
:0.000:0:0,0:0,0:34:0,1,1:1.8464e-03,3.5293e+01,3.8878e+01:0.00,34.77,37.77:0,0,0,0:0,0,0,0

# after imputation
chr1    10418   .       C       G       .       .       RAF=0.000399521;AF=0;INFO=1     GT:DS:GP:HS:GQ:ORIGIN   0/0:0:1,0,0:0:99:IMP
```

where the hard called GQ of 34 is boosted to 99. 

If this behavior is not from GLIMPSE then I'll have to go try to find out how/why/where DRAGEN is doing this. 

Thanks for your help. 

Cheers,

Brian

**Comment by BrianLohman** [comment]
Hi Simone,

Thanks for the clarification on the GQ field. I will see if I can locate more details about how DRAGEN does these calculations.

I was not aware that a larger sample size was needed for meaningful INFO scores. This might be a cause for concern for me. Right now I am imputing one sample at at time using the 2489 sample reference panel provided by Illumina (currently the only panel that the DRAGEN pipeline can be used with). I run each sample by itself because by default the DRAGEN imputation pipeline will use information from other samples in the submitted sample set during imputation. As far as I know this feature cannot be turned off. This is a problem for me because I need to get the same results no matter the context in which the sample is imputed. Does the size of the reference panel count towards the overall sample size? If not I might need to rethink this strategy and the use of INFO scores. 

Thanks for your continued assistance. 

Cheers,

Brian

**Comment by srubinacci** [comment]
In general, I have to admit I rarely use the INFO score, and I tend to use all the data, but I guess this depends on the application. However, the info score can be computed post-imputation from the GP field. Just merge the samples together and run bcftools +impute-info.
Also, GLIMPSE2 is designed to do reference-only imputation. It might be useful in your case.

Feel free to send me an email and we can try to think about the best way to get imputation for your data.

Best,
Simone
