### ISSUE TITLE
Segmentation fault glimpse_phase tutorial 5.1

### ISSUE THREAD

**Issue by GeorgeFoody** [odelaneau/GLIMPSE#153]
im receiving a segmentation fault when running the tutorial. 
all other stages seem ti have ran ok. i followed the previous stages exactly with the exception that i ran glimpse chunk with the sequential option. 

command
REF=reference_panel/split/1000GP.chr22.noNA12878
BAM=NA12878_1x_bam/NA12878.bam

while IFS="" read -r LINE || [ -n "$LINE" ]; 
do   
	printf -v ID "%02d" $(echo $LINE | cut -d" " -f1)
	IRG=$(echo $LINE | cut -d" " -f3)
	ORG=$(echo $LINE | cut -d" " -f4)
	CHR=$(echo ${LINE} | cut -d" " -f2)
	REGS=$(echo ${IRG} | cut -d":" -f 2 | cut -d"-" -f1)
	REGE=$(echo ${IRG} | cut -d":" -f 2 | cut -d"-" -f2)
	OUT=GLIMPSE_impute/NA12878_imputed
	./bin/GLIMPSE2_phase --bam-file ${BAM} --reference ${REF}_${CHR}_${REGS}_${REGE}.bin --output ${OUT}_${CHR}_${REGS}_${REGE}.bcf
done < chunks.chr22.txt

output
[GLIMPSE2] Phase and impute low coverage sequencing data
  * Authors              : Simone RUBINACCI & Olivier DELANEAU, University of Lausanne
  * Contact              : simone.rubinacci@unil.ch & olivier.delaneau@unil.ch
  * Version       	 : GLIMPSE2_phase v2.0.0 / commit = 16f3689 / release = 2023-03-10
  * Citation	         : BiorXiv, (2022). DOI: https://doi.org/10.1101/2022.11.28.518213
  *         	         : Nature Genetics 53, 120–126 (2021). DOI: https://doi.org/10.1038/s41588-020-00756-0
  * Run date      	 : 13/05/2023 - 07:24:44

Files:
  * Input BAM/CRAM       : [NA12878_1x_bam/NA12878.bam]
  * Reference binary     : [reference_panel/split/1000GP.chr22.noNA12878_chr22_48081696_50807843.bin]
  * Output file          : [GLIMPSE_impute/NA12878_imputed_chr22_48081696_50807843.bcf]
  * Output format        : [BCF format | ZLIB compression]

GLIMPSE_phase parameters:
  * Imputation model     : [Reference panel imputation]
  * Input region         : [Given by binary reference panel]
  * Output region        : [Given by binary reference panel]
  * Sparse MAF           : [Given by binary reference panel]
  * Recombination rates  : [Given by binary reference panel]
  * Ploidy               : [Only diploid samples in region]
  * Keep monom. ref sites: [NO]

Model parameters:
  * #Burnin iterations   : [5]
  * #Main iterations     : [15]
  * Ne [eff. pop. size]  : [100000]
  * Phase error rate     : [0.0001]
  * Imputation error rate: [1e-12]
  * Min value for hap GLs: [1e-10]

Selection parameters:
  * K init               : [1000]
  * K pbwt               : [2000]
  * PBWT depth           : [12]
  * PBWT modulo (cM)     : [0.1]
  * State list           : [No list provided]

Genotype calling:
  * Calling model        : [standard]
  * Perform calling]

BAM/CRAM filters and options:
  * Min mapping quality  : [10]
  * Min base quality     : [10]
  * Max depth            : [40]
  * Keep failed QC       : [NO]
  * Keep orphan reads    : [NO]
  * Keep duplicate reads : [NO]
  * Keep supp. alignment : [NO]
  * Check pairing        : [NO]
  * Ignore orientation   : [NO]
  * Illumina-1.3+        : [NO]

Other parameters
  * Seed                 : [15052011]
  * #Threads             : [1]

Initialisation:
  * Binary reference panel parsing [done] (0.07s)
  * Binary reference panel [Nrh=6398] [L=83592] [Lrare= 42197 (50.5%) - Lcommon= 41395 (49.5%)]
  * Input region         : [chr22:48081696-50807843]
  * Output region        : [chr22:48481719-50807843]
  * Sparse MAF           : [0.001]
  * Reading BAM files
  * Reading BAM files done (0.08s)
Segmentation fault (core dumped)

**Comment by c5creative** [comment]
@GeorgeFoody did you find a solution to this? I have the exact same problem. Segmentation fault after "Reading BAM files" for less than a second. I'm also using the `sequential` flag (which is the recommended option).

**Comment by srubinacci** [comment]
Hi,

Does this happen only in this chunk?

**Comment by srubinacci** [comment]
Missing folder reported as error causing segfault in the tutorial.
