### ISSUE TITLE
Haplotype dosages?

### ISSUE THREAD

**Issue by karinkumar** [odelaneau/GLIMPSE#157]
Hello, 

I would like to obtain not only the phased genotypes, but also the haplotype dosages in order to create a meta-imputation algorithm using GLIMPSE. The outputs of GLIMPSE 1 and 2 only give phased genotypes. Is there any way I can get haplotype dosages? I can't see any options for outputting this in the GLIMPSE documentation.

**Comment by srubinacci** [comment]
Hi,

Very good point, thanks for this. At the moment, both GLIMPSE1 or 2 do not emit the AP field. It would be possible and I agree it is a very interesting feature to add, but I haven't done it yet as it is relatively challenging (as the phasing is built in during the imputation). Maybe just doing this in the last iteration can be enough. It will be one of the possible features to add to a new release.

**Comment by srubinacci** [comment]
You are completely correct. I have implemented a version of the option, but I need to test it on some data before I'll be able to release it, and it might take some time. I can send it to you privately if you have data you can test it to. In case, drop me an email. 

Simone

**Comment by srubinacci** [comment]
Close this as the correspondence has been carried by emails.
