### ISSUE TITLE
Not able to run step3_script_chunk.sh gives error novariant found

### ISSUE THREAD

**Issue by ssaloni1610** [odelaneau/GLIMPSE#159]
Hi I installed and compiled glimpse on CentOS following https://odelaneau.github.io/GLIMPSE/ 
I had some issues while compiling and then I removed -ldeflate DYN_LIBS based on one of the similar issues  reported before and compiled successfully.

I am now trying to run through the steps in the tutorial
I can run step 1 and 2 successfully and I have downloaded the complete vcf (size 519930289). So I do not think it is the problem with the vcf.

When I run step 3 it runs for a while and then gives error as 
ERROR: No variant found in the region.

However I downloaded the static from here https://github.com/odelaneau/GLIMPSE/issues/146#issuecomment-1522494856 and run it, it runs fine.

I don't understand what can be the problem why is it not working with my compiled file and works with the static one.

Is it because of CentOS? 
Please let me know if I am missing anything here.

**Comment by srubinacci** [comment]
Hi,
It does not seem related to CentOS. Can you show me your commands?
Simone
