### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by jieteliang** [odelaneau/GLIMPSE#162]
I'm running GLIMPSE2_phase v2.0.0 which is up to date for twenty samples for chromosome 13. It went through but has the following error message. Any idea of why that happened? Thank you!

[GLIMPSE2] Phase and impute low coverage sequencing data
  * Authors              : Simone RUBINACCI & Olivier DELANEAU, University of Lausanne
  * Contact              : simone.rubinacci@unil.ch & olivier.delaneau@unil.ch
  * Version              : GLIMPSE2_phase v2.0.0 / commit = 733431c / release = 2023-06-15
  * Citation             : BiorXiv, (2022). DOI: https://doi.org/10.1101/2022.11.28.518213
  *                      : Nature Genetics 53, 120–126 (2021). DOI: https://doi.org/10.1038/s41588-020-00756-0
  * Run date             : 20/06/2023 - 20:04:18

Files:
  * List BAM/CRAM        : [/public/jietel/scilab/lc_wgs_Imp/LW_lc_jiangcaiyang/0.7X/0.04375_bams.txt]
  * Reference VCF        : [/public/jietel/scilab/lc_wgs_Imp/LW_lc_jiangcaiyang/1582_qu_DLW.vcf.gz]
  * Output file          : [/public/jietel/scilab/lc_wgs_Imp/LW_lc_jiangcaiyang/glimpse/0.7X/0.7X_13.bcf]
  * Output format        : [BCF format | ZLIB compression]

GLIMPSE_phase parameters:
  * Imputation model     : [Reference panel imputation]
  * Input region         : [13:1-208320018]
  * Output region        : [13:1-208320018]
  * Sparse MAF           : [0.001]
  * Recombination rates  : [Constant rate of 1cM/Mb]
  * Ploidy               : [Only diploid samples in region]
  * Keep monom. ref sites: [YES]

Model parameters:
  * #Burnin iterations   : [5]
  * #Main iterations     : [15]
  * Ne [eff. pop. size]  : [150]
  * Phase error rate     : [0.0001]
  * Imputation error rate: [1e-12]
  * Min value for hap GLs: [1e-10]

Selection parameters:
  * K init               : [1000]
  * K pbwt               : [2000]
  * PBWT depth           : [12]
  * PBWT modulo (cM)     : [0.1]
  * State list           : [No list provided]

Genotype calling:
  * Calling model        : [standard]
  * Perform calling]

BAM/CRAM filters and options:
  * Min mapping quality  : [10]
  * Min base quality     : [10]
  * Max depth            : [40]
  * Keep failed QC       : [NO]
  * Keep orphan reads    : [NO]
  * Keep duplicate reads : [NO]
  * Keep supp. alignment : [NO]
  * Check pairing        : [NO]
  * Ignore orientation   : [NO]
  * Illumina-1.3+        : [NO]

Other parameters
  * Seed                 : [15052011]
  * #Threads             : [30]

Initialisation:

Parsing specified genomic regions
  * Input region  [13:1-208320018]
  * Output region  [13:1-208320018]
  * VCF/BCF scanning [L=1756321 (Lrare= 0 (0.0%) - Lcommon= 1756321 (100.0%))]
  * VCF/BCF scanning [Nm=20 (Nmh=0 - Nmd=20) / Nr=1582 (Nrh=0 - Nrd=1582)]
  * VCF/BCF scanning [Reg=13:1-208320018 / L=1756321] [0.03s]
  * Reference panel parsing done (131.86s)
  * VCF/BCF reference panel [Nrh=3164] [L=1756321] [Lrare= 0 (0.0%) - Lcommon= 1756321 (100.0%)]
  * Input region         : [13:1-208320018]
  * Output region        : [13:1-208320018]
  * Sparse MAF           : [0.001]
  * Reading BAM files
  * Reading BAM files done (4.36s)
  * Coverage statistics reported in: [/public/jietel/scilab/lc_wgs_Imp/LW_lc_jiangcaiyang/glimpse/0.7X/0.7X_13_stats_coverage.txt.gz]
  * Avg. sequencing coverage: 0.482873
  * RARE transpose Ref (0.01s)
  * cM constant [1cM=1Mb] (0.22s)
  * Region spans 208178027 bp and 208.18 cM
  * Size sparsePBWT (111 Mb)
  * sparsePBWT built and compressed (12.39s)
  * Size PBWT (111 Mb) / pbwt-depth=12 / n_stored=2083

Initializing iteration
  * Init rare Tar [#non-ref gls: 0] (0.09s)
  * HMM imputation [#states=1000.0 / %poly=100.0%] (32.38s)

Burn-in iteration [1/5]
  * HAP update Tar (0.27s) 
  * RARE transpose Tar (0.00s)
  * sparsePBWT selection (4.19s)
  * HMM imputation [#states=2000.0 / %poly=100.0%] (71.33s)

Burn-in iteration [2/5]
  * HAP update Tar (0.27s) 
  * RARE transpose Tar (0.00s)
  * sparsePBWT selection (4.28s)
  * HMM imputation [#states=2000.0 / %poly=100.0%] (71.61s)

Burn-in iteration [3/5]
  * HAP update Tar (0.27s) 
  * RARE transpose Tar (0.00s)
  * sparsePBWT selection (4.25s)
Segmentation fault (core dumped)

**Comment by srubinacci** [comment]
Hi,

Did you remove rare variants in the reference panel? It might be the total lack of rare variants that somehow causes problems.
"VCF/BCF scanning [L=1756321 (Lrare= 0 (0.0%) - Lcommon= 1756321 (100.0%))]"

Can you try to increase the --sparse-maf value so that we have at least few rare variants, just to see if the problem arises from that?

Thanks

**Comment by jieteliang** [comment]
Thank you very much for your reply！

I have run the software according to your suggestion, but the result is still not good. The parameters you provided don't seem to work, I mean the software does not follow my command when it runs。

My command is **--sparse-maf 0.01** , but the parameters of the software running are still the default 0.001

Then when the program was running, I observed the change of the running memory. The maximum value was about 400g, which did not exceed the memory of the server, so I thought it might not be a memory problem.

GLIMPSE2_phase --bam-list 0.04375_bams.txt --reference 1582_qu_DLW.vcf.gz --input-region 13:1-208320018 --output-region 13:1-208320018 --ne 150 --output 0.7X_13.bcf --sparse-maf 0.01 --thread 30

[GLIMPSE2] Phase and impute low coverage sequencing data
  * Authors              : Simone RUBINACCI & Olivier DELANEAU, University of Lausanne
  * Contact              : simone.rubinacci@unil.ch & olivier.delaneau@unil.ch
  * Version              : GLIMPSE2_phase v2.0.0 / commit = 733431c / release = 2023-06-15
  * Citation             : BiorXiv, (2022). DOI: https://doi.org/10.1101/2022.11.28.518213
  *                      : Nature Genetics 53, 120–126 (2021). DOI: https://doi.org/10.1038/s41588-020-00756-0
  * Run date             : 26/06/2023 - 14:30:04

Files:
  * List BAM/CRAM        : [0.04375_bams.txt]
  * Reference VCF        : [1582_qu_DLW.vcf.gz]
  * Output file          : [0.7X_13.bcf]
  * Output format        : [BCF format | ZLIB compression]

GLIMPSE_phase parameters:
  * Imputation model     : [Reference panel imputation]
  * Input region         : [13:1-208320018]
  * Output region        : [13:1-208320018]
  * Sparse MAF           : [0.001]
  * Recombination rates  : [Constant rate of 1cM/Mb]
  * Ploidy               : [Only diploid samples in region]
  * Keep monom. ref sites: [NO]

Model parameters:
  * #Burnin iterations   : [5]
  * #Main iterations     : [15]
  * Ne [eff. pop. size]  : [150]
  * Phase error rate     : [0.0001]
  * Imputation error rate: [1e-12]
  * Min value for hap GLs: [1e-10]

Selection parameters:
  * K init               : [1000]
  * K pbwt               : [2000]
  * PBWT depth           : [12]
  * PBWT modulo (cM)     : [0.1]
  * State list           : [No list provided]

Genotype calling:
  * Calling model        : [standard]
  * Perform calling]

BAM/CRAM filters and options:
  * Min mapping quality  : [10]
  * Min base quality     : [10]
  * Max depth            : [40]
  * Keep failed QC       : [NO]
  * Keep orphan reads    : [NO]
  * Keep duplicate reads : [NO]
  * Keep supp. alignment : [NO]
  * Check pairing        : [NO]
  * Ignore orientation   : [NO]
  * Illumina-1.3+        : [NO]

Other parameters
  * Seed                 : [15052011]
  * #Threads             : [30]

Initialisation:

Parsing specified genomic regions
  * Input region  [13:1-208320018]
  * Output region  [13:1-208320018]
  * VCF/BCF scanning [L=1756321 (Lrare= 172 (0.0%) - Lcommon= 1756149 (100.0%))]
  * VCF/BCF scanning [Nm=20 (Nmh=0 - Nmd=20) / Nr=1582 (Nrh=0 - Nrd=1582)]
  * VCF/BCF scanning [Reg=13:1-208320018 / L=1756321] [0.05s]
  * Reference panel parsing done (191.58s)
  * VCF/BCF reference panel [Nrh=3164] [L=1756321] [Lrare= 172 (0.0%) - Lcommon= 1756149 (100.0%)]
  * Input region         : [13:1-208320018]
  * Output region        : [13:1-208320018]
  * Sparse MAF           : [0.01]
  * Reading BAM files
  * Reading BAM files done (8.16s)
  * Coverage statistics reported in: [/public/jietel/scilab/lc_wgs_Imp/LW_lc_jiangcaiyang/glimpse/0.7X/0.7X_13_stats_coverage.txt.gz]
  * Avg. sequencing coverage: 0.482873
  * RARE transpose Ref (0.07s)
  * cM constant [1cM=1Mb] (0.29s)
  * Region spans 208178027 bp and 208.18 cM
  * Size sparsePBWT (111 Mb)
  * sparsePBWT built and compressed (21.96s)
  * Size PBWT (111 Mb) / pbwt-depth=12 / n_stored=2083

Initializing iteration
  * Init rare Tar [#non-ref gls: 14.5] (0.14s)
  * HMM imputation [#states=1000.0 / %poly=100.0%] (69.05s)

Burn-in iteration [1/5]
  * HAP update Tar (0.32s) 
  * RARE transpose Tar (0.06s)
  * sparsePBWT selection (5.69s)
  * HMM imputation [#states=2000.0 / %poly=100.0%] (173.58s)

Burn-in iteration [2/5]
  * HAP update Tar (0.33s) 
  * RARE transpose Tar (0.01s)
  * sparsePBWT selection (5.57s)
  * HMM imputation [#states=2000.0 / %poly=100.0%] (131.05s)

Burn-in iteration [3/5]
  * HAP update Tar (0.33s) 
  * RARE transpose Tar (0.01s)
  * sparsePBWT selection (5.19s)
  * HMM imputation [#states=2000.0 / %poly=100.0%] (91.57s)

Burn-in iteration [4/5]
  * HAP update Tar (0.31s) 
  * RARE transpose Tar (0.00s)
  * sparsePBWT selection (5.01s)
  * HMM imputation [#states=2000.0 / %poly=100.0%] (93.04s)

Burn-in iteration [5/5]
  * HAP update Tar (0.32s) 
  * RARE transpose Tar (0.01s)
  * sparsePBWT selection (5.31s)
  * HMM imputation [#states=2000.0 / %poly=100.0%] (92.24s)

Main iteration [1/15]
  * HAP update Tar (0.30s) 
  * RARE transpose Tar (0.00s)
  * sparsePBWT selection (5.01s)
Segmentation fault (core dumped)

**Comment by srubinacci** [comment]
I see. Can you drop me an email with a small example? I can look at it.

**Comment by jieteliang** [comment]
Thank you very much for your reply! The smaller chunks are useful.
