### ISSUE TITLE
Imputation for chrX 

### ISSUE THREAD

**Issue by sumudu-rangika** [odelaneau/GLIMPSE#163]
Hi Simon,

Thanks for the great tool !!

I ran the GLIMPSE v1.1.1 on 4X coverage WGS data (GRCh37 aligned) from 2000 samples. I extracted the chrX non-PAR regions as explained in the tutorial for imputation. My question is that, the resulting VCF file has diploid genotypes for females and males. For my downstream analysis I need to identify genotypes for females and males. Is there a workaround on this? Greatly appreciate your thoughts on this. 

Thank you
Best Regards
Sumudu

**Comment by srubinacci** [comment]
Hi,

Are you sure that GLIMPSE1 outputs diploid genotypes for both males and females in the nonPAR region? This should is not supposed to be the behaviour of GLIMPSE1 if the --samples-file option is provided correctly. Can you check that?

**Comment by sumudu-rangika** [comment]
Hi Simone,

Many thanks for the reply. No I didn't include gender information in a --sample-file. Only 343 out of 2000 samples have gender information. Is there a way to get around without this information. 

Best
Sumudu

**Comment by srubinacci** [comment]
For 4X coverage data, it should be fairly straightforward to determine the sex of the samples, by looking at the number of reads mapping to sex chromosomes. 
There should be several tools for that working with even lower coverages (I cannot point to one, as I haven't used them myself, but it should be a fairly easy task). You might want to determine the sex of your samples first and then run chrX imputation using the --haploid option.

**Comment by sumudu-rangika** [comment]
Hi Simone, 

Thanks for the reply. I inferred gender of the samples using PyPGx tool (a PGx star allele calling tool which I use for my analysis). This worked well calling 341 out of 343 gender known samples correctly. Now I can use GLIMPSE for chrX imputation as you explained. Thanks a lot !

Best
Sumudu
