### ISSUE TITLE
GLIMPSE phase - ERROR base sequences

### ISSUE THREAD

**Issue by dhruvaOrchidHealth** [odelaneau/GLIMPSE#164]
I'm trying to work through the [tutorial](https://odelaneau.github.io/GLIMPSE/docs/tutorials) using the 1KG b37 reference data (e.g.(s3://1000genomes/release/20130502/ALL.chr22.phase3_shapeit2_mvncall_integrated_v5a.20130502.genotypes.vcf.gz) and internal data mapped to that version of the reference. I'm getting the below error

`ERROR: ERROR base sequences.`

which I've traced to [here](https://github.com/odelaneau/GLIMPSE/blob/733431cdc54be06ce5ea3b26dfb4f9d88c860189/phase/src/io/genotype_bam_caller.cpp#L375) and [here](https://github.com/odelaneau/GLIMPSE/blob/733431cdc54be06ce5ea3b26dfb4f9d88c860189/phase/src/containers/glimpse_mpileup.h#L42) in the code, indicating that it's somehow finding more than the 4 expected alleles in either the ref or alt for the variant(s?). I've tried with different chunks and bams I have on hand, error is consistent. Example full output below:

` [GLIMPSE2] Phase and impute low coverage sequencing data
  * Authors              : Simone RUBINACCI & Olivier DELANEAU, University of Lausanne
  * Contact              : simone.rubinacci@unil.ch & olivier.delaneau@unil.ch
  * Version              : GLIMPSE2_phase v2.0.0 / commit = 88915f7 / release = 2023-04-24
  * Citation             : BiorXiv, (2022). DOI: https://doi.org/10.1101/2022.11.28.518213
  *                      : Nature Genetics 53, 120–126 (2021). DOI: https://doi.org/10.1038/s41588-020-00756-0
  * Run date             : 21/06/2023 - 05:50:44

Files:
  * Input BAM/CRAM       : [sample1.bqsr.marked.bam]
  * Reference binary     : [/e/07/orchdhl04/Sequencing_Analysis_Tools/GLIMPSE-v2.0.1/reference_panels/1000G_phase3_v4_20130502/split/chr22_22_34151949_37586738.bin]
  * Output file          : [sample1_22_34151949_37586738.bcf]
  * Output format        : [BCF format | ZLIB compression]

GLIMPSE_phase parameters:
  * Imputation model     : [Reference panel imputation]
  * Input region         : [Given by binary reference panel]
  * Output region        : [Given by binary reference panel]
  * Sparse MAF           : [Given by binary reference panel]
  * Recombination rates  : [Given by binary reference panel]
  * Ploidy               : [Only diploid samples in region]
  * Keep monom. ref sites: [NO]

Model parameters:
  * #Burnin iterations   : [5]
  * #Main iterations     : [15]
  * Ne [eff. pop. size]  : [100000]
  * Phase error rate     : [0.0001]
  * Imputation error rate: [1e-12]
  * Min value for hap GLs: [1e-10]

Selection parameters:
  * K init               : [1000]
  * K pbwt               : [2000]
  * PBWT depth           : [12]
  * PBWT modulo (cM)     : [0.1]
  * State list           : [No list provided]

Genotype calling:
  * Calling model        : [standard]
  * Perform calling]

BAM/CRAM filters and options:
  * Min mapping quality  : [10]
  * Min base quality     : [10]
  * Max depth            : [40]
  * Keep failed QC       : [NO]
  * Keep orphan reads    : [NO]
  * Keep duplicate reads : [NO]
  * Keep supp. alignment : [NO]
  * Check pairing        : [NO]
  * Ignore orientation   : [NO]
  * Illumina-1.3+        : [NO]

Other parameters
  * Seed                 : [15052011]
  * #Threads             : [1]

Initialisation:
  * Binary reference panel parsing [done] (0.20s)
  * Binary reference panel [Nrh=5008] [L=110683] [Lrare= 72009 (65.1%) - Lcommon= 38674 (34.9%)]
  * Input region         : [22:34151949-37586738]
  * Output region        : [22:34991008-37186766]
  * Sparse MAF           : [0.001]
  * Reading BAM files
  ERROR: ERROR base sequences. `

**Comment by srubinacci** [comment]
Hi, 

Can you try to compute likelihoods on this region using BCFTOOLS as explained [here](https://odelaneau.github.io/GLIMPSE/glimpse1/tutorial_b38.html#run_likelihoods)? Then try to run GLIMPSE but this time using the --input-gl option. 

If everything runs fine on your BAM, I might need to ask you to send it to me in a anonymised way (even just that region) if possible. It's likely that something in your BAM is triggering that error and I'll need to investigate this problem more in details.

Simone

**Comment by srubinacci** [comment]
Closing for now as there's no way to understand the source of the problem. Please reopen in case there're updates.

**Comment by lycium0605** [comment]
Wow thanks for going down so deep, for me after filtering out all indels in my reference panel bcf, this error disappeared. My sense is that indels are more variable in general and can have >4 alternative alleles in your to-be-imputed set (for SNP there's only 3 possible alt at most). So filtering them all out or at least the rare ones out should help avoid this error.
