### ISSUE TITLE
Concordance check between glimpse.v1 and glimpse.v2

### ISSUE THREAD

**Issue by PengZhangJHU** [odelaneau/GLIMPSE#165]
Hi Simone,

I ran glimpse imputation on 92 samples both using V1 (1.1.1) and V2 (2.0.0) then calculated concordance with GLIMPSE_concordance (v1.1.1), by comparing to variant calls from WGS for the same 92 samples (as gold standard, the WGS calls don't have reference homozygote calls).

The glimpse v2 is much faster than v1, but the concordance seems worse across MAF bins than those from glimpse v1. I'm showing average concordance across 92 samples for chr1 to chr22 (v1 in red, v2 in blue). This is different than I have expected. Anyone has observed similar comparison before? What are the possible reasons? The majority (2/3) of samples are European, the rest are African and admixture ancestry. thanks!

![image](https://github.com/odelaneau/GLIMPSE/assets/51458996/615b474d-7b61-447e-931f-a723775acd90)

**Comment by srubinacci** [comment]
Hi,

That's interesting. I am happy to look at this in details and I have few questions. Can you send me an email with more details on your experiment (e.g. ref panel used, coverage, chunking used, if G2 was run with the --input-gl option or --bam-list, number of target samples used)? 

Thanks!

**Comment by PengZhangJHU** [comment]
Hi Simone, 

I just emailed you with more details. Thank you for looking into this, and let me know if you don't receive my email.

"We might also want to split EUR from non-EUR ancestry", you mean to check concordance separately for EUR and non-EUR?

Peng

**Comment by srubinacci** [comment]
I suspect this can arise from the large chunk size used. Indeed this likely comes from an error in GLIMPSE2_chunk when it was originally published here: the chunk size was set for SHAPEIT5 instead of GLIMPSE2. I should have fixed that in one of the first commits. Anyway, we let's carry the conversation by email and update here when we have a clear idea of what is the problem.

**Comment by srubinacci** [comment]
Update: it seems likely that the lower performance derives from the way GLs are computed. Using the same GLs, GLIMPSE2 performs equally well.
