### ISSUE TITLE
Question about indel imputation with GATK

### ISSUE THREAD

**Issue by adamyhe** [odelaneau/GLIMPSE#166]
The tutorials for GLIMPSE1 and 2 recommends excluding indels if using genotype likelihoods calculated by bcftools. Is this an issue for the GATK pipeline? i.e., is it safe to retain indels in the reference panel and target vcfs? And is it appropriate to use the genotype likelihoods from joint calling?

Thanks!

**Comment by srubinacci** [comment]
Hi,

GLIMPSE2 has been designed to perform imputation of indels using an haplotype scaffold, therefore it should not be a problem to include these sites (as errors won't propagate in case). By default genotype likelihoods are not used, the model just assumes "missing" data at the site and standard missing-data imputation is performed. Also, you can use the "--use-gl-indels" option if you want the model to actually use the GLs. I would recommend testing these two strategies first, if possible, possibly with 1KP data.

As you said in the message, with GLIMPSE1 and bcftools we have noticed a decreased imputation accuracy at indels and neighbouting SNPs, therefore I'd not recommend using the GLs unless strongly tested first. However, users imputed indels by forcing a "flat" GL at the site (similary to the standard GLIMPSE2 behavior).

Hope this answers you queston.
Best

Simone

**Comment by adamyhe** [comment]
Yes, that was helpful. Thanks for clarifying!
