### ISSUE TITLE
Allele frequency file and validation file problem

### ISSUE THREAD

**Issue by YuxiaoRuoyao** [odelaneau/GLIMPSE#168]
Hi,

I met trouble in concordance part. I downloaded the gnomAD v3 file for chr20. I see you mentioned you did some pre-processing work to extract a few information from this large file to get the file in the tutorial. Could you please tell me how to do the pre-processing? Like `bcftools annotate -x ^INFO/AF,^INFO/AC,^INFO/AN,^FORMAT > output.bcf` ? I'm not so sure whether it's the right way. 

And for the validation file, I see in the tutorial, you give the command code `bcftools mpileup -f ${REFGEN} -I -E -a 'FORMAT/DP' -T ${VCF} -r chr22 ${BAM} -Ou | bcftools call -Aim -C alleles -T ${TSV} -Ob -o ${OUT}`. 

Since I have multiple samples, should I use `BAM=bam.list;
bcftools mpileup -f ${REFGEN} -I -E -a 'FORMAT/DP' -T ${VCF} -r chr22 --bam-list ${BAM} -Ou | bcftools call -Aim -C alleles -T ${TSV} -Ob -o ${OUT}`? Just put bam samples' name in the bam.list and use `--bam-list` to input? 

Thank you so much!!
Best,
Ruoyao

**Comment by srubinacci** [comment]
Hi Ruoyao,

For 1, I'd use: `bcftools annotate -x FORMAT,FORMAT/GT,^INFO/AF,^INFO/AC,^INFO/AN input.bcf -Ob -o output.bcf`
Remember to index the output: `bcftools index -f  output.bcf`

GL computation seems fine to me, that command should work. Remember to index the ${OUT} file!

Simone
