### ISSUE TITLE
Error parsing command line arguments: unrecognised option '--input-GL'

### ISSUE THREAD

**Issue by chvbs2000** [odelaneau/GLIMPSE#169]
Hi,

In Glimpse_1, there's a commend option for taking format/GL as input during imputation (glimpse_phase) by --input-GL, however I got error: 

`Error parsing command line arguments: unrecognised option '--input-GL'`

my command line looks like:

`GLIMPSE_phase --input  --reference HRC.hg19.chr22.noNA12878.bcf --map GLIMPSE/maps/genetic_maps.b37/chr22.b37.gmap.gz --input-region 22:16050435-19261385 --output-region 22:16050435-19061356 --output ./NA12878.chr22.1x.GL.glimpse_imputed.bcf --input-GL`

Is the argument taking GL as input still being supported? Please let me know how I could potentially fix this issue, thank you very much!

**Comment by srubinacci** [comment]
One thing I notice is that the --input file is missing. Maybe that is the main problem?

**Comment by chvbs2000** [comment]
Hi Simone,

Sorry for the confusion. The input is not missing during code execution and the execution code looks like:

`GLIMPSE_phase --input NA12878.chr22.1x.vcf.gz --reference HRC.hg19.chr22.noNA12878.bcf --map /GLIMPSE/maps/genetic_maps.b37/chr22.b37.gmap.gz --input-region 22:16050435-19261385 --output-region 22:16050435-19061356 --output ./NA12878.chr22.1x.glimpse_imputed.00.bcf --input-GL "FORMATL/GL"`

And the error occurs: `Error parsing command line arguments: unrecognised option '--input-GL'`

I used glimpse version 1.1.0 and noticed that argument '--input-GL'` is not available in `GLIMPSE_phase --help`, is there any other 1.x version that supports argument '--input-GL'`? 

Thank you very much.

**Comment by srubinacci** [comment]
Yes, it is implemented in v1.1.1. 
Also, the part of your command `--input-GL "FORMAT/GL"` should be simply `--input-GL "FORMAT/GL"`

Hopefully this will work fine!

Simone
