### ISSUE TITLE
Input "block gVCF" files with GLIMPSE2

### ISSUE THREAD

**Issue by orr161** [odelaneau/GLIMPSE#173]
As you may know, the GATK haplotype caller exports "block gVCF" files, where blocks of consecutive ref/ref genotypes of similar quality are represented by one line with an "END=" tag, denoting the position where the block ends. 

Does GLIMPSE2 know how to handle this format? 

Setting GATK to not block the gVCF files generates much larger files and takes a lot longer, which is a problem with the many samples we have. 

Thank you!
Or.

**Comment by srubinacci** [comment]
Hi,

No, gVCF files are not supported. 

What we do is to tell the caller to generate calls at reference panel positions (force-calling).
[Here](https://github.com/odelaneau/GLIMPSE/issues/21#issuecomment-895385063) is how in the past I run GATK for low-coverage data. I have to say that, while GATK is a great caller for high-coverage WGS, I found other be much faster and reach the same accuracy for low-coverage WGS (e.g. freebayes, angsd, but even bcftools does a good job). Of course ultimately the choice of the caller to use is up to you.

Simone

**Comment by orr161** [comment]
Thanks!
To be clear- does glimpse not support gVCF at all ? or only the re-blocked ones (with the END tag)?
Does it support the ref,<NON REF> notation ?

**Comment by srubinacci** [comment]
Hi,

No, GLIMPSE does not support gVCF the gVCF format at all. Genotype likelihoods have to be computed at reference panel variants either internally or with a haplotype caller.

Simone

**Comment by orr161** [comment]
Thank you
