### ISSUE TITLE
Invalid machine command

### ISSUE THREAD

**Issue by whothis7** [odelaneau/GLIMPSE#174]
Hello,
I am trying to phase with GLIMPSE2 but I get an error message saying "invalid machine command". 

This is how I try to run it:
> ./GLIMPSE2_phase --bam-file mybam.bam --reference 1000GP.chr22.noNA12878_chr22_1_20119180.bin --output imputed1.vcf

I also tried running the example code from the GLIMPSE2 tutorial but I got the same error. What is the problem? 
Thanks in advance.

**Comment by srubinacci** [comment]
Hi, 
it's likely your machine does not support the static binary or the was a problem during compilation.
Have you compiled the code on your machine?

**Comment by whothis7** [comment]
Yes I compiled the code. The compilation of both chunk and split reference worked for me.

**Comment by whothis7** [comment]
Yes, the machine is old and doesn't have AVX2. Seems like I'll have to try GLIMSPE1 which is a bit unpractical for me since it doesn't support BAM input files.

**Comment by srubinacci** [comment]
I guess that explains it. Unfortunately, at the moment there's no plan to re-implement the core part of the algorithm without AVX2 intrinsics (and that will produce much slower code). 
I understand compatibility issues are frustrating, but on the other end the majority (>95%) of HPC/Cloud computing systems allow AVX2 and this is a very specific case. 
At least GLIMPSE1 should work fine.

Best,
Simone
