### ISSUE TITLE
Concordance plot with GL 

### ISSUE THREAD

**Issue by chvbs2000** [odelaneau/GLIMPSE#178]
Hi Simone,

In GLIMPSE v1.1x, I used GL as input for imputation, and the output looks like:

```
22      16386858        rs541031211     A       G       .       .       RAF=0.000220881;AF=0.001;INFO=0.001     GT:DS:GP:HS     0/0:0.002:0.998,0.002,0:0
22      16388178        .       G       T       .       .       RAF=0.000276101;AF=0.0005;INFO=0.001    GT:DS:GP:HS     0/0:0.001:0.999,0.001,0:0
22      16393045        rs532331855     G       A       .       .       RAF=0.000386541;AF=0.0025;INFO=0.003    GT:DS:GP:HS     0/0:0.005:0.995,0.005,0:0
22      16393312        rs138132527     G       A       .       .       RAF=0.155997;AF=0.152;INFO=0.001        GT:DS:GP:HS     0/0:0.304:0.719,0.258,0.023:17412
```

Yet when I do concordance plot using:
```
GLIMPSE_concordance --input concordance.lst --minDP 8 --output ./ --minPROB 0.9999 --bins 0.00000 0.00100 0.00200 0.00500 0.01000 0.05000 0.10000 0.20000 0.50000 --af-tag AF_nfe --thread $(nproc)
```

I had weird output compared to the one using PL as input for imputation (both of them are the same sample but with different genotype likelihood input format (PL vs. GL)):

#### GL as input for imputation and concordance:
```
0 134247 0.000269235 -nan -nan
1 18580 0.00142858 0.130061 0.130061
2 22854 0.003257 -nan -nan
3 14700 0.00721247 -nan -nan
4 31541 0.0243276 -nan -nan
5 15586 0.072363 0.00184261 0.00184261
6 18393 0.147158 6.05594e-05 6.05594e-05
7 37646 0.342285 0.040831 0.040831
```

#### PL as input for imputation and concordance:
```
0 134247 0.000269235 0.503842 0.503842
1 18580 0.00142858 0.797691 0.797691
2 22854 0.003257 0.783344 0.783344
3 14700 0.00721247 0.89014 0.89014
4 31541 0.0243276 0.926658 0.926658
5 15586 0.072363 0.968959 0.968959
6 18393 0.147158 0.972129 0.972129
7 37646 0.342285 0.968285 0.968285
```

I wonder if there's any specific parameters I need to specify when using GL-imputed VCF as input for running concordance analysis? Thank you very much.

**Comment by srubinacci** [comment]
No, the output is the same (GT, DS, GP). 
The input is by default PL, and can be defined as GL if caller outputs GL (much more inefficient).

The results you get sign that imputation completely failed when you used GL. Can you show an example of your input?

**Comment by chvbs2000** [comment]
Hi Simone,

Thanks for the tips. Yes, the input GL to imputation looks like:

```
1       4920898 .       G       A       .       .       .       GT:DS:GL        .:.:.
1       4920899 .       T       A       .       .       .       GT:DS:GL        0/0:0.3334:0.6667629605753056,0.33435803873608505,-0.0003743954341572376
1       4920901 .       C       T       .       .       .       GT:DS:GL        0/0:0.3326:0.6675153984967152,0.3332918582379703,-0.00026883507825101297
1       4920916 .       G       A       .       .       .       GT:DS:GL        .:.:.
1       4920916 .       G       T       .       .       .       GT:DS:GL        .:.:.
1       4920921 .       C       A       .       .       .       GT:DS:GL        0/0:0.3335:0.6664627108474508,0.33308767217984686,0.00014982923657776612
1       4920922 .       A       G       .       .       .       GT:DS:GL        .:.:.
1       4920949 .       A       T       .       .       .       GT:DS:GL        0/0:0.3328:0.6673692093492067,0.33394970782900346,-0
```

And the code I ran for imputation is:
```
GLIMPSE_phase --input NA12878.chr22.1x.liftover2hg19.rename.vcf.gz --reference HRC.hg19.chr22.noNA12878.bcf --map chr22.b37.gmap.gz --input-region  [22:16050435-19261385] --output-region [22:16050435-19061356] --input-GL --output NA12878.chr22.1x.liftover2hg19.rename.glimpse_imputed.00.bcf
```

And detailed information when running imputation:
```
[GLIMPSE] Phase and impute low coverage sequencing data
  * Author        : Simone RUBINACCI & Olivier DELANEAU, University of Lausanne
  * Contact       : simone.rubinacci@unil.ch & olivier.delaneau@unil.ch
  * Version       : 1.1.1
  * Run date      : 30/08/2023 - 17:50:28

Files:
  * Input VCF     : [NA12878.chr22.1x.liftover2hg19.rename.vcf.gz]
  * Reference VCF : [HRC.hg19.chr22.noNA12878.bcf]
  * Genetic Map   : [chr22.b37.gmap.gz]
  * Output VCF    : [NA12878.chr22.1x.liftover2hg19.rename.glimpse_imputed.00.bcf]
  * Input region  : [22:16050435-19261385]
  * Output region : [22:16050435-19061356]

Parameters:
  * Seed       : 15052011
  * Input      : FORMAT/GL field for genotype likelihoods
  * #Threads   : 1
  * #Burnin    : 10
  * #Main      : 10
  * PBWT depth : 2
  * PBWT modulo: 8
  * HMM        : Recombination rates given by genetic map
  * Ploidy     : All samples are diploids in this region
  * Init K     : 1000
```

When I run imputation there was no sign of error, but the output was the one I posted above. Happy to learn any things that might potential cause imputation to fail. Thank you!

**Comment by srubinacci** [comment]
Hi,

In the example above, your GLs are not log10 scaled likelihoods, therefore do not to follow the [VCF spec](https://samtools.github.io/hts-specs/VCFv4.2.pdf):
`• GL : genotype likelihoods comprised of comma separated floating point log10-scaled likelihoods for all possible genotypes given the set of alleles defined in the REF and ALT fields. In presence of the GT field the same ploidy is expected and the canonical order is used; without GT field, diploidy is assumed. If A is the allele in REF and B,C,... are the alleles as ordered in ALT, the ordering of genotypes for the likelihoods is given by: F(j/k) = (k*(k+1)/2)+j. In other words, for biallelic sites the ordering is: AA,AB,BB; for triallelic sites the ordering is: AA,AB,BB,AC,BC,CC, etc. For example: GT:GL 0/1:-323.03,-99.29,-802.53 (Floats)`


As  GLIMPSE is then forced to work with misspecified input, this causes failed imputation. 

Did you convert this yourself from the PL or a caller produced this output?

Simone

**Comment by chvbs2000** [comment]
Hi Simone,

Thanks for the information. SO would you suggest to convert GL to log10 scale? Yes, I converted this from the PL by myself. Happy to learn any insight! Thanks.

**Comment by srubinacci** [comment]
Hi,

Indeed, GLs are computed in log10 scale by genotype callers, such as freebayes, for numerical reasons (e.g. `GT:GL 0/1:-323.03,-99.29,-802.53`). This is the reason why the VCF standard uses log10-scaled likelihoods in the GL field. 

[Here](https://gatk.broadinstitute.org/hc/en-us/articles/360035890451-Calculation-of-PL-and-GQ-by-HaplotypeCaller-and-GenotypeGVCFs) there's is a gentle introduction on this concepts. 

Hope this helps

Simone

**Comment by chvbs2000** [comment]
Hi Simone,

I converted GL to log10 scale as suggested:

```
1       4920916 .       G       A       .       .       .       GT:DS:GL        0/0:0.3337:-0.1763490137367566,-0.47706406607209095,
-3.9307953035800565
1       4920916 .       G       T       .       .       .       GT:DS:GL        .:.:.
1       4920921 .       C       A       .       .       .       GT:DS:GL        0/0:0.3362:-0.17810365888787572,-0.47565956231667605
,-3.18294638920137
1       4920922 .       A       G       .       .       .       GT:DS:GL        0/0:0.3339:-0.17645044718549804,-0.4767936145338387,
-4.000152572447926
```
and run imputation with the same command line above, yet the imputation results are still off:

```
0 134247 0.000269235 -nan -nan
1 18580 0.00142858 0.130061 0.130061
2 22854 0.003257 -nan -nan
3 14700 0.00721247 -nan -nan
4 31541 0.0243276 -nan -nan
5 15586 0.072363 0.00184261 0.00184261
6 18393 0.147158 6.05594e-05 6.05594e-05
7 37646 0.342285 0.040831 0.040831
```

Could you please share how GLIMPSE normalizes -10*log(GLs) to PL? I previously used -10*log(GLs)[i]-min(-10*log(GLs)) to set min=0 and max to 255, but not sure if it aligns to what GLIMPSE does. Thank you!
