### ISSUE TITLE
Concordance output of Total #variants = 0

### ISSUE THREAD

**Issue by mcmk3** [odelaneau/GLIMPSE#18]
Good day,

I am trying to use the concordance tool and am getting an output of 0 variants even when using the same file for truth and estimate.

I have gone through the tutorial and the sample files do work.
The files in the concordance.lst for this working example have the following format:

Truth file: 
```
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  NA12878
chr22   16367266        .       G       A       181     .       MQSB=1;MQ0F=0.947368;MQ=0;SGB=-0.379885;RPB=1;MQB=1;BQB=1;DP=9203;DP4=4651,3994,2,5;AN=2;AC=0   GT:PL:DP        0/0:0,33,23:11
```

Frequency file:
```
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO
chr22   16367322        rs542895279     C       T       394     AC0     AF_afr=0;AF_nfe=0
```

Estimate file
```
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  NA12878
chr22   10874444        .       C       T       .       .       RAF=0.195965;AF=0.169422;INFO=0 GT:DS:GP:HS     0/0:0.339:0.691,0.28,0.03:643
```

**My files:**

The high coverage 'truth file' had the following format

```
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  high_cov
chr22   10521847        .       G       A       8.13869 .       DP=1;SGB=-0.379885;MQ0F=0;AC=2;AN=2;DP4=0,0,0,1;MQ=37   GT:PL   1/1:37,3,0
chr22   10526424        .       C       T       3.62418 .       DP=12;VDB=0.28;SGB=-0.453602;RPB=0.777778;MQB=1;MQSB=1;BQB=1;MQ0F=0;ICB=1;HOB=0.5;AC=1;AN=2;DP4=6,3,2,0;MQ=37   GT:PL   0/1:36,0,207
```

I also tried using the same file processed to the following format (all sites):

```
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  high_cov
chr22   10510183        .       A       G       .       .       .       GT      .
chr22   10511349        .       A       G       .       .       .       GT      .
chr22   10513433        .       A       T       .       .       .       GT      .
chr22   10513961        .       A       G       64      .       DP=1;MQ0F=0;AC=0;AN=2;DP4=1,0,0,0;MQ=37 GT:PL:DP        0/0:0,3,37:1
```
and also as (DP in 'genotype area'):

```
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  high_cov
chr22   10521847        .       G       A       8.13869 .       DP=1;SGB=-0.379885;MQ0F=0;AC=2;AN=2;DP4=0,0,0,1;MQ=37   GT:PL:DP        1/1:37,3,0:1
chr22   10526424        .       C       T       3.62418 .       DP=12;VDB=0.28;SGB=-0.453602;RPB=0.777778;MQB=1;MQSB=1;BQB=1;MQ0F=0;ICB=1;HOB=0.5;AC=1;AN=2;DP4=6,3,2,0;MQ=37   GT:PL:DP        0/1:36,0,207:11
```

I have tried several different **reference files**:

First I tried a series of the same file processed in different ways (this is the file used to make the sites file for calling likelihoods for my samples with angsd) as below. I also tried the reference used in the tutorial (making sure to set --info_af AF appropriately).
1.

```
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO
	chr22   10510183        .       A       G       17      MIS2    AF=0.000199681
```
 
2.

```
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  HG00096 HG00097 HG00099 HG00100 HG00101 HG00102 HG00103 HG00105 HG00106 HG00107 HG00108 HG00109 HG00110 HG00111 HG00112 HG00113 HG00114 HG00115 HG00116 HG00117 HG00118 HG00119 etc etc
chr22   10510183        .       A       G       17      MIS2    AF=0.000199681  GT      0|0     0|0     0|0     0|0     0|0     0|0     0|0     0|0     0|0     0|0     0|0     0|0     0|0     0|0     0|0     0|0     0|0     0|0     0|0
     0|0     0|0     0|0     0|0     0|0     0|0     0|0     0|0     0|0     0|0 etc etc
```
 
3.
 
```
CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  HG00096 HG00097 HG00099 HG00100 HG00101 HG00102 HG00103 HG00105 HG00106 HG00107 HG00108 HG00109 HG00110 HG00111 HG00112 HG00113 HG00114 HG00115 HG00116 HG00117 HG00118 HG00119 etc etc
chr22   10510183        .       A       G       17      MIS2    AVGDP=1.74054;AC=1;AN=5008;FIBC_P=0.271567;HWE_SLP_P=76.687;FIBC_I=0.211143;HWE_SLP_I=0.50214;MAX_IF=0.000188;MIN_IF=1e-05;BETA_IF=0;ABE=0.722943;ABZ=7.93693;BQZ=-12.8167;MQZ=-0.07539;CYZ=3.30302;STZ=0;NMZ=4.86092;IOR=-0.767945;NM0=1.15199;NM1=0.242151;LLK0=-181.088;SVM=-0.366369;ANN=G|intergenic_region|MODIFIER|CHR_START-U2|CHR_START-ENSG00000277248|intergenic_region|CHR_START-ENSG00000277248|||n.10510183A>G||||||;FMIS10=0.953016;MAX_HM3_R2=0;LOG_HM3_BUDDY_03=0;LOG_HM3_BUDDY_05=0;LOG_HM3_BUDDY_08=0;LOG_HM3_DIST_03=6;LOG_HM3_DIST_05=6;LOG_HM3_DIST_08=6;DUP_NH_ALL=0;DUP_NH_DIS=0;TRI_NH_ALL=0;TRI_NH_DIS=0;AF=0.000199681       GT      0|0 0|0     0|0     0|0     0|0   etc etc
```

My **estimate file** (imputed with GLIMPSE_phase using likelihoods called by angsd) has the following format: 

```
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  0.25x.cov     0.5x.cov      0.75x.cov     1x.cov        1.25x.cov     1.5x.cov     1.75x.cov     2x.cov
chr22   10510183        .       A       G       .       .       RAF=0.000199681;AF=0.000262468;INFO=0   GT:DS:GP:HS     0/0:0.001:0.999,0.001,0:0       0/0:0:1,0,0:0   0/0:0:1,0,0:0   0/0:0:1,0,0:0   0/0:0:1,0,0:0   0/0:0:1,0,0:0   0/0:0.001:0.999,0.001,0:0       0/0:0.001:0.999,0.001,0:0
chr22   10511349        .       A       G       .       .       RAF=0.000199681;AF=0.000237473;INFO=0   GT:DS:GP:HS     0/0:0.001:0.999,0.001,0:0       0/0:0:1,0,0:0   0/0:0:1,0,0:0   0/0:0:1,0,0:0   0/0:0:1,0,0:0   0/0:0.001:0.999,0.001,0:0       0/0:0:1,0,0:0   0/0:0.001:0.999,0.001,0:0
```

I get the following output for these iterations (excepting the second truth file, which gives a segmentation fault):

```
Region      [chr22]
  * #overlapping samples = 0
  * #variants in the overlap = 40309
  * #variants with validation data = 0
  * #genotypes used in validation = 0
  * %error rate in this file = -nan
  * Total #variants = 0
```

If I use the truth file for both the truth and estimate input:

```
Region      [chr22]
  * #overlapping samples = 1
  * #variants in the overlap = 40695
  * #variants with validation data = 0
  * #genotypes used in validation = 0
  * %error rate in this file = -nan
  * Total #variants = 0
```

If I set my both truth and estimate to the estimate file:

```
  * Region      [chr22]
  * #overlapping samples = 8
  * #variants in the overlap = 1316816
  * #variants with validation data = 0
  * #genotypes used in validation = 0
  * %error rate in this file = -nan
  * Total #variants = 0
```

There are similar results for the use of the reference genome used in the tutorial. (Furthermore, when using my reference frequencies with the truth and estimate files for the tutorial the program runs fine.) Using a single sample in the estimate (rather than the eight samples) does not solve the issue.
Do you have any advice?

Thank you for your time.

**Comment by mcmk3** [comment]
On further investigation. These problems were the result of two issues.
The truth and estimate files must have the same name for the sample (which means the eight samples in my estimate file must be done one at a time, with the truth file reheadered).
GLIMPSE_concordance requires the ID field, which was not present in the correct format in my files.
I am now recieving an output:
```
* Region      [chr22]
  * #overlapping samples = 1
  * #variants in the overlap = 40309
  * #variants with validation data = 35093
  * #genotypes used in validation = 35093
  * %error rate in this file = 60.2029
  * Total #variants = 35093
```
But still experiencing one problem. The output files contain an output with the exception of the avg.rsquare file, which is specifically required for making plots.
i.e.

avg.rsquare.grp.txt.gz
```
0 0 0 0
1 0 0 0
2 0 0 0
3 0 0 0
4 0 0 0
5 0 0 0
6 0 0 0
7 0 0 0
```

rsquare.grp.txt.gz
```
0 446 0.000424879 -0.0785156 0.00616471
1 156 0.00160254 0.0216294 0.000467829
2 320 0.00355245 0.112312 0.0126141
3 478 0.0071392 0.160611 0.0257959
4 1783 0.0289078 0.0441005 0.00194486
5 2975 0.0746113 0.013095 0.000171479
6 6491 0.151064 -0.0223512 0.000499575
7 22444 0.352237 0.0537549 0.00288959
```

**Comment by srubinacci** [comment]
Hi,

Yes, indeed the validation and your imputed dataset must contain the same sample IDs or at both contain a subset of the sample IDs you intend to verify. From what I see here, the results you are getting are pretty worrying and denote a problem somewhere, since you get an rsquared of almost zero at each bin. This might be due to how you run concordance, but also it can be due to how you run GLIMPSE_phase.

First of all, please discard `avg.rsquare.txt.gz` file as it contains a metric (the average of variant-level rsquared) that can't be computed at each variant. The aggregate rsquare is what you probably want to use (`rsquare.grp.txt.gz` file), as the variants are aggregated first and then an rsquare is computed between imputed and validation genotypes.

I am not sure I follow you when you are saying you need to run the estimation one target at the time. If you have a single validation file for each target sample, can't you just merge these files? 

A possible mistake I can see is that in your validation file you have the DP field specified as an INFO field, but you don't have it in the in the FORMAT field. That might cause problems in GLIMPSE_concordance, as it is really made to be run for multiple individuals at the same time, therefore it uses the DP in the FORMAT field. What software are you using to generate the genotype likelihoods of your target/validation dataset?

Other than this, it's pretty difficult to understand where's the problem, as this is the last step of a full analysis, but I can certainly see there's a problem somewhere. If you want you can post or email me your scripts, I'll definitively be able to understand a bit better what is going on. 

Best wishes,

Simone

**Comment by mcmk3** [comment]
Hi,

Apologies for the late reply. If the avg.rsquare.txt.gz is not meant to be calculated then I think that the I now have everything working without obvious error. (It might be nice to have headers in the concordance output files.) I agree however, that I am causing a problem somewhere, as the scores are far too low. 

I had been using Angsd to impute, I have now tried with Bcftools mpileup as in your tutorial, this achieved better results. 

Thank you for the help and your time.
