### ISSUE TITLE
Question about input vcf files

### ISSUE THREAD

**Issue by K-ayers** [odelaneau/GLIMPSE#181]
Hi! I had a question about the input vcf files. I have forced called my sample at the 1000 genomes positions (I am not joint calling at the moment). I have low pass sequencing, so I expect the read count will be zero for some variants and I don't believe these variants get called. I was wondering how GLIMPSE handles missing data? Does it require a call in the input vcf when the read depth is greater than zero, and then assumes if the variant is not there the read depth is zero and thus the genotype likelihoods (GLs) are equal? Or do I need to add in these missing calls and GLs? And does GLIMPSE handle missing calls set to ./.   ? Thanks

**Comment by srubinacci** [comment]
Hi,

There are indeed several ways a variant can be represented as missing in the VCF file, all equal. First, it can be that you have DP=0 for the reference panel alleles and this can be represented as a flat genotype likelihood (e.g. PL=0,0,0 - although I have never seen this in practice!), or missing data (./.). Additionally, if all your samples have no reads in that position, the PL can even be a simple "." for all samples.

GLIMPSE handles all these equivalent cases. As the genotypes are missing, they will be imputed using IBD from the reference panel.

So, going back to your question, no need to add missing calls and PLs.
Just make sure the variant is set to missing but is still present in the file, as GLIMPSE does not impute variants only present in the reference panel*.

Hope this helps

Simone


*unless --impute-reference-only-variants is used, but I never recommend using this option, as it's the caller that has to take the decision to not output a PL for that variant.
