### ISSUE TITLE
GLIMPSE1: ERROR: Parsing line 0 : incorrect number of columns, observed: 1 expected: 3

### ISSUE THREAD

**Issue by whothis7** [odelaneau/GLIMPSE#182]
Hi, 
when I run an imputation and chromosome 13 is reached, I get the error:
` ERROR: Parsing line 0 : incorrect number of columns, observed: 1 expected: 3`

This only happens with chromosome 13. Until yesterday I didn't have such an error. I tried changing the input files and reference files and format but the error remains.

**Comment by srubinacci** [comment]
Hi,

It seems there's a problem when attempting to read the map file. Are you using the provided map files or you own file format?

**Comment by whothis7** [comment]
Thanks, that was the problem. I was using the provided map file but it seems like it got corrupted in some way.
