### ISSUE TITLE
GLIMPSE2 : Called variants handling in output imputed data

### ISSUE THREAD

**Issue by bpprins** [odelaneau/GLIMPSE#183]
Hi Simone ! I'm currently testing out GLIMPSE2, apart from reported bugs sofar so good ! I was wondering what happens to the typed / called variants in the final imputed output dataset : 1) Are the original dosages preserved and injected into the output file for a given input VCF, or are they imputed upon and probabilities given for imputed ? Secondly 2) I was wondering if there would be a way to recognise / flag somewhere in the output VCF which variants were original input for imputation (if imputing from VCF and not CRAM ?

Thanks a lot in advance !

Bram

**Comment by srubinacci** [comment]
Hi,

1. In GLIMPSE, the original dosages are not injected into the output file. Instead, GLIMPSE imputes and refines the likelihoods given in the input VCF or CRAM file. The output includes the imputed best-guess genotypes (GT field) along with their posterior probabilities (GP). 
2. Not sure I fully understand your point, but if you mean that you want to separate variants having a non-flat genotype likelihood vs variants having a genotype likelihood, you can fairly easily do that after imputation, simply interesecting the two files.

Let me know if I can help more

Simone
