### ISSUE TITLE
Questions about imputation

### ISSUE THREAD

**Issue by acty2323** [odelaneau/GLIMPSE#187]
Hi, 

I'm attempting to use GLIMPSE2_phase to impute my data, but I'm encountering errors indicating that it failed to open the file "/cromwell_root/gcp-public-data-broad-references/hg38/v0/Homo_sapiens_assembly38.fasta". Additionally, I've received warnings telling me to check my BAM file because there is no mapped read available for sample in the current chunk. However, I think my BAM file is correct. Is there something else I should check?

Below is the code and error message.

Code :
`GLIMPSE2_phase --bam-file EABP869820.cram --reference 1000GP.chr22.noNA12878_chr22_39706677_44881437.bin --output chr22_imputed_chr22_39706677_44881437.bcf`

Error message :

> [E::fai_build3_core] Failed to open the file /cromwell_root/gcp-public-data--broad-references/hg38/v0/Homo_sapiens_assembly38.fasta
> [E::refs_load_fai] Failed to open reference file '/cromwell_root/gcp-public-data--broad-references/hg38/v0/Homo_sapiens_assembly38.fasta'
> [W::cram_get_ref] Failed to populate reference for id 21
> [E::cram_decode_slice] Unable to fetch reference #21:38096967-38386536
> 
> [E::cram_next_slice] Failure to decode slice
>   * Reading BAM files done (0.04s)
> 
> WARNING: No mapped read available for sample EABP869820 in the current chunk. Check your BAM file prior to perform phasing/imputation.
> 
> WARNING: Sample: EABP869820 has 1.000% of missing data. Imputation might be non meaningful for this sample due to the large amount of missing data. Check your sample if this does not agree with your expectations.
>   * Coverage statistics reported in: [GLIMPSE_impute/chr22_imputed_chr22_38258240_43270139_stats_coverage.txt.gz]
>   * Avg. sequencing coverage: 0.000000
>   * RARE transpose Ref (0.01s)
>   * Region spans 5011900 bp and 4.50 cM
> 
> WARNING: Small imputation region in cM detected (for Kpbwt parameter): changing PBWT modulo parameter to: 0.050000 cM
>   * Size PBWT (1 Mb) / pbwt-depth=12 / n_stored=91

Thanks!

Penny

**Comment by c5creative** [comment]
CRAM is a typically used as a reference-based compressed format, storing only differences between it and the reference aligned against. I suspect you performed your alignment against `Homo_sapiens_assembly38.fasta` and saved the alignment as a reference-based CRAM file. This means that you need to have the fasta file present for the CRAM to be readable. No readable CRAM == nor reads. 

Check the docs - https://odelaneau.github.io/GLIMPSE/docs/documentation/phase/#bamcram-options-and-filters
> Faidx-indexed reference sequence file in the appropriate genome build. Necessary for CRAM files

I could be completely wrong, but it's something to look into. Good luck! 
JP
