### ISSUE TITLE
Fewer variants in the reference panel file  downloaded from the GLIMPSE2 website

### ISSUE THREAD

**Issue by acty2323** [odelaneau/GLIMPSE#190]
Hi, 

I've been using the reference panel files from the tutorial section of the GLIMPSE2 website (http://ftp.1000genomes.ebi.ac.uk/vol1/ftp/data_collections/1000G_2504_high_coverage/working/20201028_3202_phased/CCDG_14151_B01_GRM_WGS_2020-08-05_chr22.filtered.shapeit2-duohmm-phased.vcf.gz{,.tbi}), but I've noticed that for some chromosomes, there are fewer variants compared to the vcf files I have.
This difference seems to cause errors when I try to create a binary reference panel.
Does this mean that I need to use another reference panel?

Below is the error message.

> ERROR: Reading binary reference panel file: [1000GP.chr16.noNA12878_chr16_85493365_1000000000.bin]. File not good(): eofbit, failbit or badbit set or file not found.

Thanks!

Penny

**Comment by srubinacci** [comment]
Hi,

It seems that some of your job failed. Can you post a log file to understand the problem?

**Comment by acty2323** [comment]
Hi, 

Here is the phasing log file for chr16. 

[Impute_814_1017.log](https://github.com/odelaneau/GLIMPSE/files/13446209/Impute_814_1017.log)

Because I don't have the log file for creating a binary reference panel, I'm uploading the phasing log file, but the errors are similar between these two processes.

Thanks!

Penny
