### ISSUE TITLE
Are imputed individuals included back into the reference panel?

### ISSUE THREAD

**Issue by sahwa** [odelaneau/GLIMPSE#199]
Hi quick question -  if you run GLIMPSE v1.1.1 with a reference panel, are the target individuals who have been imputed then included back  into the reference panel? i.e. does the inclusion of different target individuals affect how the other target individuals are imputed?

Thanks, 

Sam.

**Comment by srubinacci** [comment]
Hi,

yes, that is a main difference between GLIMPSE2 and GLIMPSE1.1.1. For reference panel only imputation, GLIMPSE2 should be the method of choice.

Best,

Simone
