### ISSUE TITLE
problem with compilation

### ISSUE THREAD

**Issue by thierrygrange** [odelaneau/GLIMPSE#2]
I am trying to compile on a computer with Ubuntu 18. I have linker problems that give the following errors:
chunker_io.cpp:(.text+0x34a): undefined reference to `bcf_sr_init'
chunker_io.cpp:(.text+0x366): undefined reference to `bcf_sr_add_reader'
chunker_io.cpp:(.text+0x37a): undefined reference to `bcf_sr_add_reader'
chunker_io.cpp:(.text+0x3a4): undefined reference to `bcf_sr_next_line'
chunker_io.cpp:(.text+0x3e0): undefined reference to `bcf_unpack'
chunker_io.cpp:(.text+0x464): undefined reference to `bcf_sr_next_line'
chunker_io.cpp:(.text+0x474): undefined reference to `bcf_sr_destroy'

Any idea what could go wrong? I have modified the Paths in the makefile according to the outputs of the locate commands as indicated. I linked to the boot header folder that was in /usr/include/boot/ 

Thanks for your help

Thierry

**Comment by SimoneRubinacci** [comment]
Hi,

Thanks for the question. Looks like there are problems while linking to HTSLIB. If you have not read it yet, more detailed installation instructions can be found here: https://odelaneau.github.io/GLIMPSE/installation.html. We also require BOOST libraries.

I recommend you to try to install the program on your machine following the instructions on our website and I am very happy to help you in the process. However, if your purpose if just to try the software and no machine-optimized compilation is needed, we also provide already-compiled binaries in the static_bins folders, tested for Ubuntu 18.

**Comment by thierrygrange** [comment]
Dear Simone

Of course, I followed the instructions before even sending the help notice. I had previously installed HTSLIB and BOOST libraries and I indicated the links to them.  I have modified the makefile as follows to adapt to my computer:

desktop: HTSLIB_INC=/home/paleogenomique/samtools-1.10/htslib-1.10/
desktop: /home/paleogenomique/Software/samtools-1.10/htslib-1.10/libhts.a
desktop: BOOST_INC=/usr/include/boot/
desktop: BOOST_LIB_IO=/usr/lib/x86_64-linux-gnu/libboost_iostreams.a
desktop: BOOST_LIB_PO=/usr/lib/x86_64-linux-gnu/libboost_program_options.a
desktop: $(BFILE)

One possibility I have considered is that I was not using the proper HTSLIB libraries, because I have many existing due to previous updates of this library that is widely used by many tools we are routinely using. I have tried several without sucess, even though the error message may differ depending on the one I use. The latest one indicated above correspond to one associated to our current samtools version that is running fine. I indicate here the outcome of the locate command:
locate libboost_program_options.a libboost_iostreams.a libhts.a
/home/paleogenomique/R/x86_64-pc-linux-gnu-library/3.6/Rhtslib/usrlib/libhts.a
/home/paleogenomique/Software/bcftools-1.10.2/htslib-1.10.2/libhts.a
/home/paleogenomique/Software/fqtools/htslib/libhts.a
/home/paleogenomique/Software/htslib-1.10.2/libhts.a
/home/paleogenomique/Software/htslib-1.10.2/lib/libhts.a
/home/paleogenomique/Software/htslib-1.6/lib/libhts.a
/home/paleogenomique/Software/htslib_1-9/lib/libhts.a
/home/paleogenomique/Software/samtools-1.10/htslib-1.10/libhts.a
/usr/lib/x86_64-linux-gnu/libboost_iostreams.a
/usr/lib/x86_64-linux-gnu/libboost_program_options.a
/usr/local/lib/libhts.a

I have also tried to use either /usr/include/boot/ or /usr/include/ as indicated for the Boost header files location but it did not change the outcome and on my computer, the path to the Boost files is  /usr/include/boot/

As a reminder, the iostream linker errors I received were:

chunker_io.cpp:(.text+0x34a): undefined reference to bcf_sr_init' chunker_io.cpp:(.text+0x366): undefined reference to bcf_sr_add_reader'
chunker_io.cpp:(.text+0x37a): undefined reference to bcf_sr_add_reader' chunker_io.cpp:(.text+0x3a4): undefined reference to bcf_sr_next_line'
chunker_io.cpp:(.text+0x3e0): undefined reference to bcf_unpack' chunker_io.cpp:(.text+0x464): undefined reference to bcf_sr_next_line'
chunker_io.cpp:(.text+0x474): undefined reference to `bcf_sr_destroy'

Any more precise idea of the required dependency that is not working here?

Thanks for your help

Best

Thierry Grange

________________________________
De : Simone Rubinacci [notifications@github.com]
Envoyé : dimanche 19 avril 2020 23:02
À : odelaneau/GLIMPSE
Cc : GRANGE Thierry; Author
Objet : Re: [odelaneau/GLIMPSE] problem with compilation (#2)


Hi,

Thanks for the question. Looks like there are problems while linking to HTSLIB. If you have not read it yet, more detailed installation instructions can be found here: https://odelaneau.github.io/GLIMPSE/installation.html. We also require BOOST libraries.

I recommend you to try to install the program on your machine following the instructions on our website and I am very happy to help you in the process. However, if your purpose if just to try the software and no machine-optimized compilation is needed, we also provide already-compiled binaries in the static_bins folders, tested for Ubuntu 18.

**Comment by SimoneRubinacci** [comment]
It looks like HTSLIB_LIB is missing and it seems that the HTSLIB_INC location is not the right path, since the right location seems to be: /home/paleogenomique/**Software**/samtools-1.10/htslib-1.10.

Can you try if something along these lines:

desktop: HTSLIB_INC=/home/paleogenomique/Software/samtools-1.10/htslib-1.10
desktop: HTSLIB_LIB=/home/paleogenomique/Software/samtools-1.10/htslib-1.10/libhts.a
desktop: BOOST_INC=/usr/include
desktop: BOOST_LIB_IO=/usr/lib/x86_64-linux-gnu/libboost_iostreams.a
desktop: BOOST_LIB_PO=/usr/lib/x86_64-linux-gnu/libboost_program_options.a

and let me know if it works?

**Comment by thierrygrange** [comment]
Dear colleague

Indeed I lost the HTSLIB_LIB= on the way, but I have now a much longer error message, that I add here.

Thanks for your help

Best

Thierry

make -C chunk
make[1]: Entering directory '/home/paleogenomique/Software/GLIMPSE/chunk'
g++ -std=c++11 -O3 obj/chunk.o obj/chunker_parameters.o obj/chunker_io.o obj/chunker_management.o obj/chunker_algorithm.o /home/paleogenomique/Software/samtools-1.10/htslib-1.10/libhts.a /usr/lib/x86_64-linux-gnu/libboost_iostreams.a /usr/lib/x86_64-linux-gnu/libboost_program_options.a -o bin/GLIMPSE_chunk -lz -lbz2 -lm -lpthread -llzma
/home/paleogenomique/Software/samtools-1.10/htslib-1.10/libhts.a(hfile_libcurl.o): In function `easy_errno':
hfile_libcurl.c:(.text+0x1083): undefined reference to `curl_easy_getinfo'
hfile_libcurl.c:(.text+0x10cc): undefined reference to `curl_easy_getinfo'
/home/paleogenomique/Software/samtools-1.10/htslib-1.10/libhts.a(hfile_libcurl.o): In function `libcurl_exit':
hfile_libcurl.c:(.text+0x1249): undefined reference to `curl_share_cleanup'
hfile_libcurl.c:(.text+0x137f): undefined reference to `curl_global_cleanup'
/home/paleogenomique/Software/samtools-1.10/htslib-1.10/libhts.a(hfile_libcurl.o): In function `process_messages':
hfile_libcurl.c:(.text+0x263f): undefined reference to `curl_multi_info_read'
/home/paleogenomique/Software/samtools-1.10/htslib-1.10/libhts.a(hfile_libcurl.o): In function `wait_perform':
hfile_libcurl.c:(.text+0x2743): undefined reference to `curl_multi_fdset'
hfile_libcurl.c:(.text+0x277b): undefined reference to `curl_multi_timeout'
hfile_libcurl.c:(.text+0x28a2): undefined reference to `curl_multi_perform'
/home/paleogenomique/Software/samtools-1.10/htslib-1.10/libhts.a(hfile_libcurl.o): In function `libcurl_read':
hfile_libcurl.c:(.text+0x2be5): undefined reference to `curl_easy_pause'
/home/paleogenomique/Software/samtools-1.10/htslib-1.10/libhts.a(hfile_libcurl.o): In function `libcurl_write':
hfile_libcurl.c:(.text+0x2e7b): undefined reference to `curl_easy_pause'
/home/paleogenomique/Software/samtools-1.10/htslib-1.10/libhts.a(hfile_libcurl.o): In function `restart_from_position':
hfile_libcurl.c:(.text+0x3273): undefined reference to `curl_easy_setopt'
hfile_libcurl.c:(.text+0x32fa): undefined reference to `curl_easy_duphandle'
hfile_libcurl.c:(.text+0x333e): undefined reference to `curl_easy_setopt'
hfile_libcurl.c:(.text+0x3371): undefined reference to `curl_easy_setopt'
hfile_libcurl.c:(.text+0x33a4): undefined reference to `curl_easy_setopt'
hfile_libcurl.c:(.text+0x3431): undefined reference to `curl_multi_add_handle'
hfile_libcurl.c:(.text+0x3493): undefined reference to `curl_easy_pause'
hfile_libcurl.c:(.text+0x3560): undefined reference to `curl_multi_remove_handle'
hfile_libcurl.c:(.text+0x357e): undefined reference to `curl_easy_reset'
hfile_libcurl.c:(.text+0x359b): undefined reference to `curl_multi_remove_handle'
hfile_libcurl.c:(.text+0x35c5): undefined reference to `curl_easy_cleanup'
hfile_libcurl.c:(.text+0x3607): undefined reference to `curl_easy_cleanup'
hfile_libcurl.c:(.text+0x364a): undefined reference to `curl_easy_setopt'
hfile_libcurl.c:(.text+0x3681): undefined reference to `curl_easy_setopt'
hfile_libcurl.c:(.text+0x36c4): undefined reference to `curl_easy_reset'
hfile_libcurl.c:(.text+0x378e): undefined reference to `curl_easy_reset'
hfile_libcurl.c:(.text+0x37ab): undefined reference to `curl_multi_remove_handle'
hfile_libcurl.c:(.text+0x37fe): undefined reference to `curl_easy_cleanup'
/home/paleogenomique/Software/samtools-1.10/htslib-1.10/libhts.a(hfile_libcurl.o): In function `libcurl_close':
hfile_libcurl.c:(.text+0x38a8): undefined reference to `curl_easy_pause'
hfile_libcurl.c:(.text+0x395a): undefined reference to `curl_multi_remove_handle'
hfile_libcurl.c:(.text+0x3997): undefined reference to `curl_easy_cleanup'
hfile_libcurl.c:(.text+0x39a7): undefined reference to `curl_multi_cleanup'
/home/paleogenomique/Software/samtools-1.10/htslib-1.10/libhts.a(hfile_libcurl.o): In function `libcurl_open':
hfile_libcurl.c:(.text+0x3d1e): undefined reference to `curl_multi_init'
hfile_libcurl.c:(.text+0x3d4b): undefined reference to `curl_easy_init'
hfile_libcurl.c:(.text+0x3d9e): undefined reference to `curl_easy_setopt'
hfile_libcurl.c:(.text+0x3dd0): undefined reference to `curl_easy_setopt'
hfile_libcurl.c:(.text+0x3e0d): undefined reference to `curl_easy_setopt'
hfile_libcurl.c:(.text+0x3e3e): undefined reference to `curl_easy_setopt'
hfile_libcurl.c:(.text+0x3e85): undefined reference to `curl_easy_setopt'
/home/paleogenomique/Software/samtools-1.10/htslib-1.10/libhts.a(hfile_libcurl.o):hfile_libcurl.c:(.text+0x3eb6): more undefined references to `curl_easy_setopt' follow
/home/paleogenomique/Software/samtools-1.10/htslib-1.10/libhts.a(hfile_libcurl.o): In function `libcurl_open':
hfile_libcurl.c:(.text+0x41f3): undefined reference to `curl_multi_add_handle'
hfile_libcurl.c:(.text+0x4291): undefined reference to `curl_easy_getinfo'
hfile_libcurl.c:(.text+0x43b4): undefined reference to `curl_easy_setopt'
hfile_libcurl.c:(.text+0x43e6): undefined reference to `curl_easy_setopt'
hfile_libcurl.c:(.text+0x4418): undefined reference to `curl_easy_setopt'
hfile_libcurl.c:(.text+0x44bb): undefined reference to `curl_easy_getinfo'
hfile_libcurl.c:(.text+0x4536): undefined reference to `curl_easy_setopt'
hfile_libcurl.c:(.text+0x4568): undefined reference to `curl_easy_setopt'
hfile_libcurl.c:(.text+0x45d0): undefined reference to `curl_easy_getinfo'
hfile_libcurl.c:(.text+0x4645): undefined reference to `curl_multi_remove_handle'
hfile_libcurl.c:(.text+0x46b5): undefined reference to `curl_easy_cleanup'
hfile_libcurl.c:(.text+0x46d2): undefined reference to `curl_multi_cleanup'
/home/paleogenomique/Software/samtools-1.10/htslib-1.10/libhts.a(hfile_libcurl.o): In function `hfile_plugin_init_libcurl':
hfile_libcurl.c:(.text+0x4e85): undefined reference to `curl_global_init'
hfile_libcurl.c:(.text+0x4eb6): undefined reference to `curl_share_init'
hfile_libcurl.c:(.text+0x4ece): undefined reference to `curl_global_cleanup'
hfile_libcurl.c:(.text+0x4f03): undefined reference to `curl_share_setopt'
hfile_libcurl.c:(.text+0x4f26): undefined reference to `curl_share_setopt'
hfile_libcurl.c:(.text+0x4f47): undefined reference to `curl_share_setopt'
hfile_libcurl.c:(.text+0x4f5f): undefined reference to `curl_share_cleanup'
hfile_libcurl.c:(.text+0x4f64): undefined reference to `curl_global_cleanup'
hfile_libcurl.c:(.text+0x5002): undefined reference to `curl_share_cleanup'
hfile_libcurl.c:(.text+0x5007): undefined reference to `curl_global_cleanup'
hfile_libcurl.c:(.text+0x5060): undefined reference to `curl_version_info'
/home/paleogenomique/Software/samtools-1.10/htslib-1.10/libhts.a(hfile_s3.o): In function `s3_sign':
hfile_s3.c:(.text+0x573): undefined reference to `EVP_sha1'
hfile_s3.c:(.text+0x597): undefined reference to `HMAC'
/home/paleogenomique/Software/samtools-1.10/htslib-1.10/libhts.a(hfile_s3.o): In function `s3_sha256':
hfile_s3.c:(.text+0x5ec): undefined reference to `SHA256'
/home/paleogenomique/Software/samtools-1.10/htslib-1.10/libhts.a(hfile_s3.o): In function `s3_sign_sha256':
hfile_s3.c:(.text+0x619): undefined reference to `EVP_sha256'
hfile_s3.c:(.text+0x640): undefined reference to `HMAC'
/home/paleogenomique/Software/samtools-1.10/htslib-1.10/libhts.a(hfile_s3_write.o): In function `cleanup_local':
hfile_s3_write.c:(.text+0x462): undefined reference to `curl_easy_cleanup'
/home/paleogenomique/Software/samtools-1.10/htslib-1.10/libhts.a(hfile_s3_write.o): In function `set_html_headers':
hfile_s3_write.c:(.text+0x509): undefined reference to `curl_slist_append'
hfile_s3_write.c:(.text+0x520): undefined reference to `curl_slist_append'
hfile_s3_write.c:(.text+0x53b): undefined reference to `curl_slist_append'
hfile_s3_write.c:(.text+0x556): undefined reference to `curl_slist_append'
hfile_s3_write.c:(.text+0x571): undefined reference to `curl_slist_append'
/home/paleogenomique/Software/samtools-1.10/htslib-1.10/libhts.a(hfile_s3_write.o):hfile_s3_write.c:(.text+0x598): more undefined references to `curl_slist_append' follow
/home/paleogenomique/Software/samtools-1.10/htslib-1.10/libhts.a(hfile_s3_write.o): In function `set_html_headers':
hfile_s3_write.c:(.text+0x5c1): undefined reference to `curl_easy_setopt'
/home/paleogenomique/Software/samtools-1.10/htslib-1.10/libhts.a(hfile_s3_write.o): In function `abort_upload':
hfile_s3_write.c:(.text+0x7cd): undefined reference to `curl_easy_reset'
hfile_s3_write.c:(.text+0x7fb): undefined reference to `curl_easy_setopt'
hfile_s3_write.c:(.text+0x82c): undefined reference to `curl_easy_setopt'
hfile_s3_write.c:(.text+0x85d): undefined reference to `curl_easy_setopt'
hfile_s3_write.c:(.text+0x895): undefined reference to `curl_easy_setopt'
hfile_s3_write.c:(.text+0x8d7): undefined reference to `curl_easy_perform'
hfile_s3_write.c:(.text+0x979): undefined reference to `curl_slist_free_all'
/home/paleogenomique/Software/samtools-1.10/htslib-1.10/libhts.a(hfile_s3_write.o): In function `complete_upload':
hfile_s3_write.c:(.text+0xbf2): undefined reference to `curl_easy_reset'
hfile_s3_write.c:(.text+0xc21): undefined reference to `curl_easy_setopt'
hfile_s3_write.c:(.text+0xc59): undefined reference to `curl_easy_setopt'
hfile_s3_write.c:(.text+0xc91): undefined reference to `curl_easy_setopt'
hfile_s3_write.c:(.text+0xcc2): undefined reference to `curl_easy_setopt'
hfile_s3_write.c:(.text+0xcf3): undefined reference to `curl_easy_setopt'
/home/paleogenomique/Software/samtools-1.10/htslib-1.10/libhts.a(hfile_s3_write.o):hfile_s3_write.c:(.text+0xd24): more undefined references to `curl_easy_setopt' follow
/home/paleogenomique/Software/samtools-1.10/htslib-1.10/libhts.a(hfile_s3_write.o): In function `complete_upload':
hfile_s3_write.c:(.text+0xdcf): undefined reference to `curl_easy_perform'
hfile_s3_write.c:(.text+0xe71): undefined reference to `curl_slist_free_all'
/home/paleogenomique/Software/samtools-1.10/htslib-1.10/libhts.a(hfile_s3_write.o): In function `upload_part':
hfile_s3_write.c:(.text+0x117e): undefined reference to `curl_easy_reset'
hfile_s3_write.c:(.text+0x11ad): undefined reference to `curl_easy_setopt'
hfile_s3_write.c:(.text+0x11de): undefined reference to `curl_easy_setopt'
hfile_s3_write.c:(.text+0x120f): undefined reference to `curl_easy_setopt'
hfile_s3_write.c:(.text+0x1247): undefined reference to `curl_easy_setopt'
hfile_s3_write.c:(.text+0x1278): undefined reference to `curl_easy_setopt'
/home/paleogenomique/Software/samtools-1.10/htslib-1.10/libhts.a(hfile_s3_write.o):hfile_s3_write.c:(.text+0x12a9): more undefined references to `curl_easy_setopt' follow
/home/paleogenomique/Software/samtools-1.10/htslib-1.10/libhts.a(hfile_s3_write.o): In function `upload_part':
hfile_s3_write.c:(.text+0x1385): undefined reference to `curl_easy_perform'
hfile_s3_write.c:(.text+0x1424): undefined reference to `curl_slist_free_all'
/home/paleogenomique/Software/samtools-1.10/htslib-1.10/libhts.a(hfile_s3_write.o): In function `s3_write':
hfile_s3_write.c:(.text+0x1531): undefined reference to `curl_easy_getinfo'
/home/paleogenomique/Software/samtools-1.10/htslib-1.10/libhts.a(hfile_s3_write.o): In function `s3_close':
hfile_s3_write.c:(.text+0x1728): undefined reference to `curl_easy_getinfo'
/home/paleogenomique/Software/samtools-1.10/htslib-1.10/libhts.a(hfile_s3_write.o): In function `initialise_upload':
hfile_s3_write.c:(.text+0x1ba7): undefined reference to `curl_easy_setopt'
hfile_s3_write.c:(.text+0x1bd6): undefined reference to `curl_easy_setopt'
hfile_s3_write.c:(.text+0x1c07): undefined reference to `curl_easy_setopt'
hfile_s3_write.c:(.text+0x1c38): undefined reference to `curl_easy_setopt'
hfile_s3_write.c:(.text+0x1c69): undefined reference to `curl_easy_setopt'
/home/paleogenomique/Software/samtools-1.10/htslib-1.10/libhts.a(hfile_s3_write.o):hfile_s3_write.c:(.text+0x1c9a): more undefined references to `curl_easy_setopt' follow
/home/paleogenomique/Software/samtools-1.10/htslib-1.10/libhts.a(hfile_s3_write.o): In function `initialise_upload':
hfile_s3_write.c:(.text+0x1d73): undefined reference to `curl_easy_perform'
hfile_s3_write.c:(.text+0x1e03): undefined reference to `curl_slist_free_all'
/home/paleogenomique/Software/samtools-1.10/htslib-1.10/libhts.a(hfile_s3_write.o): In function `s3_write_open':
hfile_s3_write.c:(.text+0x1f33): undefined reference to `curl_easy_init'
hfile_s3_write.c:(.text+0x2107): undefined reference to `curl_easy_getinfo'
/home/paleogenomique/Software/samtools-1.10/htslib-1.10/libhts.a(hfile_s3_write.o): In function `s3_write_exit':
hfile_s3_write.c:(.text+0x2633): undefined reference to `curl_share_cleanup'
hfile_s3_write.c:(.text+0x267a): undefined reference to `curl_global_cleanup'
/home/paleogenomique/Software/samtools-1.10/htslib-1.10/libhts.a(hfile_s3_write.o): In function `hfile_plugin_init_s3_write':
hfile_s3_write.c:(.text+0x269c): undefined reference to `curl_global_init'
hfile_s3_write.c:(.text+0x26b4): undefined reference to `curl_share_init'
hfile_s3_write.c:(.text+0x26cc): undefined reference to `curl_global_cleanup'
hfile_s3_write.c:(.text+0x2701): undefined reference to `curl_share_setopt'
hfile_s3_write.c:(.text+0x2724): undefined reference to `curl_share_setopt'
hfile_s3_write.c:(.text+0x2745): undefined reference to `curl_share_setopt'
hfile_s3_write.c:(.text+0x275d): undefined reference to `curl_share_cleanup'
hfile_s3_write.c:(.text+0x2762): undefined reference to `curl_global_cleanup'
hfile_s3_write.c:(.text+0x2781): undefined reference to `curl_version_info'
collect2: error: ld returned 1 exit status
makefile:37: recipe for target 'bin/GLIMPSE_chunk' failed
make[1]: *** [bin/GLIMPSE_chunk] Error 1
make[1]: Leaving directory '/home/paleogenomique/Software/GLIMPSE/chunk'
makefile:8: recipe for target 'chunk' failed
make: *** [chunk] Error 2

**Comment by SimoneRubinacci** [comment]
Okay this is better. It's finally linking against libhts.a but it does not find libcurl.
Can you please try change your dynamic libraries (usualy is line 9) to this:

DYN_LIBS=-lz -lpthread -lbz2 -llzma -lcurl -lcrypto

and let me know the result?

**Comment by thierrygrange** [comment]
That was it for most of the makefile, adding the DYN_LIBS to -lcurl and -lcrypto solved the problem.

Only the snparray/make had a novel problem:

make[1]: Entering directory '/home/paleogenomique/Software/GLIMPSE/snparray'
g++ -std=c++11 -O3  -c src/snparray.cpp -o obj/snparray.o -Isrc -I/home/paleogenomique/samtools-1.10/htslib-1.10/ -I/usr/include/
Assembler messages:
Fatal error: can't create obj/snparray.o: No such file or directory
makefile:40: recipe for target 'obj/snparray.o' failed
make[1]: *** [obj/snparray.o] Error 1
make[1]: Leaving directory '/home/paleogenomique/Software/GLIMPSE/snparray'
makefile:8: recipe for target 'snparray' failed
make: *** [snparray] Error 2

Thanks

Thierry
________________________________
De : Simone Rubinacci [notifications@github.com]
Envoyé : lundi 20 avril 2020 23:12
À : odelaneau/GLIMPSE
Cc : GRANGE Thierry; Author
Objet : Re: [odelaneau/GLIMPSE] problem with compilation (#2)


Okay this is better. It's finally linking against libhts.a but it does not find libcurl.
Can you please try change your dynamic libraries (usualy is line 9) to this:

DYN_LIBS=-lz -lpthread -lbz2 -llzma -lcurl -lcrypto

and let me know the result?

**Comment by SimoneRubinacci** [comment]
Glad now it's working. 
Thanks for finding a problem in GLIMPSE/snparray. It's actually my failt, I've just pushed a fix to this. If you pull the new code a folder named "obj" will appear under GLIMPSE/snparray and will solve the problem. You can create that folder by yourself in case, without pulling new code.

Hope everything will run smoothly now.

**Comment by thierrygrange** [comment]
Thanks

Now everything worked.

We will probably get back to you along the way when using it, if we are welcome to do it.

Best

Thierry
________________________________
De : Simone Rubinacci <notifications@github.com>
Envoyé : lundi 20 avril 2020 23:44
À : odelaneau/GLIMPSE
Cc: GRANGE Thierry; Author
Objet : Re: [odelaneau/GLIMPSE] problem with compilation (#2)


Glad now it's working.
Thanks for finding a problem in GLIMPSE/snparray. It's actually my failt, I've just pushed a fix to this. If you pull the new code a folder named "obj" will appear under GLIMPSE/snparray and will solve the problem. You can create that folder by yourself in case, without pulling new code.

Hope everything will run smoothly now.

**Comment by SimoneRubinacci** [comment]
Brilliant.
Sure, happy to help.

Best,
Simone
