### ISSUE TITLE
Support for GRCh37 version

### ISSUE THREAD

**Issue by ssinh10** [odelaneau/GLIMPSE#200]
Hi,  I am looking for the right reference panel to use for human genome version GRCh37 .  I was able to replicate the tutorial https://odelaneau.github.io/GLIMPSE/docs/tutorials/getting_started/, it was super useful.
However,  I only found the resources for human genome version GRCh38.  
Is there any recommended version GRCh37 equivalent of http://ftp.1000genomes.ebi.ac.uk/vol1/ftp/data_collections/1000G_2504_high_coverage/working/20201028_3202_phased/CCDG_14151_B01_GRM_WGS_2020-08-05_chr22.filtered.shapeit2-duohmm-phased.vcf.gz  for reference panel.  

Any insights will be helpful. Thanks for your help.

**Comment by srubinacci** [comment]
Hi,

The GRCh37 version is based on low-coverage WGS (~8x). There's nothing wrong with the version you linked, it has been extensively validated and used for many years, but of course the 30x version is higher quality and has ~600 more (related) samples.
Knowing this limitation, the version you linked is absolutely fine.

Best,
Simone

**Comment by ssinh10** [comment]
Hi @srubinacci, thank you for your response. The version I have linked is  from your tutorial page and I think that is GRCh38. 
My question was do you know if there is a GRCh37 1000 genome reference panel which can be used. 
Hope that reframes my question in a right way. Sorry about the confusion.

**Comment by srubinacci** [comment]
Right, I just misread the link. 
1000 Genomes Phase 3 dateset in b37 can be found here:
ftp://ftp.1000genomes.ebi.ac.uk/vol1/ftp/release/20130502/

Keep in mind this has the limits I briefly mentioned before.

**Comment by ssinh10** [comment]
Thanks @srubinacci that helps.

**Comment by ssinh10** [comment]
Hi @srubinacci , I have been thinking about the best method to work with the GRCh37 files, as you mentioned using the reference panel from GRCh37 has some limitations. I am thinking is a there a better way to run GLIMPSE2 on GRCh37?
1. Can I convert the GRCh38 reference panel to GRCh37 ? I tried that using liftover but that resulted in 1000s of unmapped regions which might act like a gap in the reference panel.

2. Do you know if there is any better GRCh37 reference panel available which can overcome some of the limitations of 1000 genome GRch37 reference panel?

Thank you for any insights you can provide.

**Comment by srubinacci** [comment]
Hi, 
1. The low-coverage dataset has been widely used and I don't think there's a need to liftover for most applications. If you want to proceed with the conversion, liftover will work fine and should not create large gaps as you encountered. Maybe try using modern liftover tools, such as: 
https://academic.oup.com/bioinformatics/article/40/2/btae038/7585532
 
2. In general, 1000 Genomes is a great reference panel, extensively validated. The 30x version is great to get even more variants, but the 2015 version is still currently very largely used. I wouldn't worry too much about it personally.

Hope it helps,

Simone

**Comment by ssinh10** [comment]
Thanks for the elaborate explanation. That helps!
