### ISSUE TITLE
Documentation around GATK usage

### ISSUE THREAD

**Issue by vkulkarni-invitae** [odelaneau/GLIMPSE#21]
Hello again,
We are loving this software. Many thanks!

Would it be possible to add a sample usage of how you would change the tutorial to add GATK? The paper mentions GATK being used with great success so was wondering if you could give the exact invocation string you used? I presume this would be just in the GL step?

Thank you.
Vinayak.

**Comment by srubinacci** [comment]
Hi both,

Indeed, this is something we are actively working on at the moment, one of our top priorities. Will update you here as soon as we have news about it.

Best wishes,
Simone

**Comment by mcieslik-mctp** [comment]
Thank you Simone, much appreciated.

**Comment by mcieslik-mctp** [comment]
Hi Simone, sorry to trouble you but we are really anxious to try GLIMPSE on GATK data. Perhaps rather than providing something that would take much of your time you could just give us some tips on the expected input (gVCF vs VCF, how to deal with indels), to get started (or just rough command lines how you used GATK for the analyses in your paper)? Thank you so much!

**Comment by srubinacci** [comment]
Hi,

Thank you for your message.
I apologise, unfortunately the benchmark is still running and we still do not have definitive guidelines. 

Indeed, I have a command line I use to run for GATK, but consider this as untested, and I am not sure this is recommended by the GATK community.
Basically, the way I use GATK is to run only GATK HaplotypeCaller to force the computation of the likelihoods at a set of variants in VCF format, (e.g. biallelic snps of the reference panel), similarly to what we do in the tutorial with bcftools. 

Please contact me via email if you want to know how we do it, and how we run GLIMPSE afterwards.  

Regarding indels, we are benchmarking in this moment. Hopefully we'll get some preliminary answer in the next few days. 

Best,
Simone

**Comment by mcieslik-mctp** [comment]
Thank you. It appears your solution to genotype at given alleles is the same as implemented here in a benchmark of shallow-genotyping approaches (https://pubmed.ncbi.nlm.nih.gov/33122697/), including GLIMPSE. 

For mulit-allelics is it OK to decompose multi-allelics in the imputation panel (rather than removing tham with -m2 -M2), similar to how it is done for Beagle? It appears Gencove got it to work somehow (https://medium.com/the-gencove-blog/experimental-human-imputation-pipeline-using-glimpse-45f98f9778bc)?

**Comment by wrosan** [comment]
Hello, I am trying to use these imputation tools to analyze some skim seq data. I was also interested in knowing the implementation of GATK in the pipeline. I saw this thread on GATK, so I decided to follow up here. Is it possible to share the documentation on using GATK? Also, had there been any updates on handling indels? Thank you for this amazing tool, and thank you in advance for all your effort to answer our concerns and queries.

**Comment by srubinacci** [comment]
Hi, 
One way to use GATK (4.2.*.*) to derive genotype likelihoods is the following:

`gatk --java-options "-Xmx16g" HaplotypeCaller -R reference.fasta -I lowcov.bam -O output.vcf.gz --all-site-pls --L sites.vcf.gz --alleles sites.vcf.gz --output-mode EMIT_ALL_ACTIVE_SITES --min-pruning 0`

However, it is not very clear from their documentation and this is just a command line I have been using and nothing official. 
For example the option "--min-pruning 0" has been referenced [here](https://gatk.broadinstitute.org/hc/en-us/articles/360043491652-When-HaplotypeCaller-and-Mutect2-do-not-call-an-expected-variant) as important for low-coverage data, but in the past I have excluded it, and things were working reasonably well.

Regarding indels. A very simple way to handle indels is to avoid genotype likelihood computation for them (so your sites.vcf.gz is a file containing only biallelic snps) and perform standard imputation on them (e.g. insert the indels as missing, or flat likelihoods sites prior to imputation). This is the safest way to do it without trying to call likelihood callers that can actually be harmful for the whole imputation process, as we saw with bcftools). 

Hope it helps,
Best wishes,

Simone

**Comment by wrosan** [comment]
Thank you, Simone. I will run GATK as you suggested and will check the results.

**Comment by wrosan** [comment]
I ran my samples using haplotype caller, but I used -ERC GVCF to enable merging of all the g.vcf.gz files (I have > 500 samples) using GenomicsDBImport followed by GenotypeGVCFs? GenomicsDBImport was done per chromosome and GenotypeGVCFs are still ongoing. With these steps, I would end up with a single vcf per chromosome for all samples. 

Now, I am wondering if that VCF file is what I need or I need to perform additional steps to extract genotype likelihood? Also, I noticed that vcf files have multi allele SNPs, does that need to be processed using bcftools to split multiple alleles into multiallelic records (bcftools norm -m any)?

**Comment by srubinacci** [comment]
Hi,

Unfortunately I really cannot help with GVCF/DBImport as it is something I have never done. The solution I posted above, was just a similar version to the one provided in the tutorial, where variant discovery is not performed and genotype calling is only performed on a set of fixed (bi-allelic) sites. Regarding the merging, that should be possible even without using the -ERC GCVF option, just by using bcftools.
Regarding multiallelic variants, you are correct, you will need to split them using bcftools norm.

Best wishes,

Simone

**Comment by wrosan** [comment]
Thank you so much for your inputs and suggestions.

**Comment by mcieslik-mctp** [comment]
@wrosan we have experimented quite a bit in using GLIMPSE work with gVCF files. 

What we came up with is implemented here:
https://github.com/mctp/lopass

Using low-pass sequencing (1X, GRCh38, and 1000G imputation panel) this solution matches, in our tests, the performance of GLIMPSE and loimpute (Gencove).

The key idea is to 'extract' specific bi-allelic genotypes present in the panel from the gVCF directly (without the need for joint-calling). If you use GATK4 on low-pass data it is important to force it to call more sites, the builtin script `lopass-gatk.py` implements this but for reference:

```
GVCF_CMD = [
    "gatk", "HaplotypeCaller",
    "--emit-ref-confidence", "GVCF",
    "--min-dangling-branch-length", "1",
    "--min-pruning", "1",
    "--indel-size-to-eliminate-in-ref-model", "0",
    "--heterozygosity", "0.1",
    "--indel-heterozygosity", "0.1",
    "--base-quality-score-threshold", "10",
    "--dont-use-soft-clipped-bases", "true",
    "--create-output-variant-index", "false"
]
```

**Comment by wrosan** [comment]
@mcieslik-mctp  thank you so much for sharing the information. I will try implementing the steps you recommended and check the output.
