### ISSUE TITLE
Phasing with larger chunks?

### ISSUE THREAD

**Issue by drneavin** [odelaneau/GLIMPSE#223]
Thanks for providing such an effective and fast phasing tool! 

I'm wondering if the chunks used by glimpse could be longer? Would this impact the phasing in any way?

For my use case I'm applying to glimpse to hundreds of samples that are each in their own vcf so one of the limiting factors is the spin up of a different job for each chunk for each sample so it would be better if I could make the chunks a bit longer but I want to make sure this wouldn't impact the phasing results. If so, is there a max length that you would recommend?

Thanks for the input.

**Comment by srubinacci** [comment]
Hi,

Using larger chunks should be fine, but you might actually want to pull samples together, as the program will be much more efficient. Are you using GLIMPSE2?
To merge GL files you can use something similar to step 3.3 here:
https://odelaneau.github.io/GLIMPSE/glimpse1/tutorial_b38.html#run_likelihoods

Simone

**Comment by drneavin** [comment]
Hi @srubinacci, for my use case merging samples isn't really an option at the moment. I'm using GLIMPSE version 1 since I ran into some issues with GLIMPSE2 that I couldn't resolve (https://github.com/odelaneau/GLIMPSE/issues/196) quickly and I'm under a bit of a time crunch. I wanted to compare the results between the two version for my use case but just couldn't get it working on time.

In my case I have one donor that I'm phasing at a time against a larger reference so I think based on the documents you would recommend GLIMPSE1 over GLIMPSE2 for this use case? Otherwise, I can go back and redo the tests with Glimpse2 if you think that Glimpse2 would be a better fit. Now that I'm using larger chunks, I don't think I should run into the same issue I raised above.

**Comment by bgulko** [comment]
I am finding that G2_phase runs to completion when there are <613K variants in the reference panel but fails when there are >670K. Memory consumption for large successful runs is <64G, and 256G is available. Have you seen anything like this? If so, how did you get around it? (I am also running whole-chromosome, without chunk/ligate logic), also for personalized medicine.

**Comment by drneavin** [comment]
I ended up using larger chunks but I found that using each chromosome as a single chunk was infeasible because of the memory and time limitations you listed. I ended up using the following parameters:
```
--window-size 30000000 \
--buffer-size 200000 \
```

Hope it helps!

**Comment by bgulko** [comment]
Thanks @drneavin, actually this does help!

Ultimately we may have to chunk or reduce our reference panel size. Chunking brings additional stages & dependencies (code/check) into the pipeline. We already have plenty and with limited developer resources (me), this is an issue. Your response stands as another testament to the reliability of this process. Thanks.

I've found the memory and time limitations of whole chromosome phasing to be acceptable within our reference panel, so long as we run chromosomes in parallel. We have plenty of memory and compute (though more effective use of threads for large runs would also be helpful). I expect this is the future direction of resources.

Our central problem in relying on GLIMPSE for trio analysis has been proper conditioning and stability, hopefully this too will soon be resolved . :) 

Best, --B
