### ISSUE TITLE
Merging target individuals

### ISSUE THREAD

**Issue by sabrinacamp2** [odelaneau/GLIMPSE#24]
Hi, 

Great tool! The documentation was a life-saver in implementing it on the cloud. 

I have a project where I would be imputing genotypes for ~1400 individuals. I saw on the tutorial that merging target samples pre-imputation is not necessary. If I did merge them, would this increase the imputation accuracy? 

Best,
Sabrina Camp

**Comment by srubinacci** [comment]
Hi Sabrina,

Yes, indeed you'll increase the imputation accuracy, as you might increase the chance to spot larger IBD segments. Especially in the case your reference panel is small, having ~2800 haps more to potentially condition on, could be really beneficial.
Of course if your reference panel is very large, the gain will be smaller. This is somewhat what we show as supplementary figure 2 in our pre-print. 

Hope this is helpful,

Best wishes
Simone

**Comment by sabrinacamp2** [comment]
Hi Simone,

Thank you for your response, and this is really helpful. The supplement does lay this out nicely, I appreciate you pointing me in that direction.

All the best,
Sabrina
