### ISSUE TITLE
If without reference panel

### ISSUE THREAD

**Issue by biozzq** [odelaneau/GLIMPSE#27]
Dear all,

I am wondering that whether GLIMPSE can be used to impute and phase the variants in the non-model organisms those don't have any reference panel and the genetic map. Thank you very much.

Your sincerely.
Zheng zhuqing

**Comment by srubinacci** [comment]
Hi,

Thanks for you question. Unfortunately no, at the current state of the project, GLIMPSE requires a reference panel, as it was the main focus of our work. We do not exclude an extension to reference-free imputation in the future, but it will require some additional modelling.

Best wishes,
Simone

**Comment by biozzq** [comment]
Dear @srubinacci 

Thanks for your information.

Best wishes,
Zheng zhuqing
