### ISSUE TITLE
Regarding installation

### ISSUE THREAD

**Issue by speed5003** [odelaneau/GLIMPSE#28]
Hello, I am facing a problem on GLIMPSE installation. This 'non-declaration' error keeps coming when I tried to install different versions of GLIMPSE. I think that errors are encountered when 'nthread' was used in bcf_~ function.
"error: bcf_sr_set_threads' was not declared in this scope"
Do you have any clue to solve this problem? gcc 5.3.0, HTSLIB 1.7 and Boost 1.65 were used.

**Comment by srubinacci** [comment]
Hi,
You probably have some problem in your makefile, not pointing to the right include/lib paths (in this case for HTSLIB).

Can you try to install the latest versions of htslib and boost locally as described in the [installation guide](https://odelaneau.github.io/GLIMPSE/installation.html) (just copy the instructions should work), then checkout GLIMPSE and go into the "phase" folder and change the target desktop to:

`#CONDITIONAL PATH DEFINITON
desktop: HTSSRC=../..
desktop: HTSLIB_INC=$(HTSSRC)/htslib
desktop: HTSLIB_LIB=$(HTSSRC)/htslib/libhts.a
desktop: BOOST_INC=../../boost/include
desktop: BOOST_LIB_IO=../../boost/lib/libboost_iostreams.a
desktop: BOOST_LIB_PO=../../boost/lib/libboost_program_options.a
desktop: $(BFILE)
`

This should solve the problem.
