### ISSUE TITLE
ERROR: No markers in region: chr22. Check chromosome name and start/end positions.

### ISSUE THREAD

**Issue by chvbs2000** [odelaneau/GLIMPSE#29]
Hi, I have a vcf.gz file that contains whole genome sequencing info. And follow the tutorial starts from step 4 in https://odelaneau.github.io/GLIMPSE/tutorial_b38.html#run_preliminaries. Yet it showed the error "ERROR: No markers in region: chr22. Check chromosome name and start/end positions." I wonder how could I specify markers in the region for a whole genome data? Thanks!

**Comment by srubinacci** [comment]
Hi,

This error can be caused from a multitude of different problems and it is not easy to tell what's exactly the problem. First, you should double check that that the chromosome ID matches for both the panels (however, this is the case for the tutorial). A common mistake is to use specifications different from the one specified in the VCF/BCF file. A quick way to check it would be running:

`bcftools view -H -G target.vcf.gz | head -n 1 | awk '{print $1}'`

Additionally, of course you should check the content of your files, and verify that both your target and reference have data, for example by using

`bcftools view -H -r chr22 target.vcf.gz`

Hope this will help to solve your problem.
