### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by chvbs2000** [odelaneau/GLIMPSE#31]
When I followed step 5 (imputation and phasing on whole genome), segmentation fault happens when imputing chromosome 1 with reference genome of hg38:

Parameters:
  * Seed       : 15052011
  * #Threads   : 1
  * #Burnin    : 10
  * #Main      : 10
  * PBWT depth : 2
  * PBWT modulo: 8
  * HMM     : Recombination rates given by genetic map
  * Ploidy     : All samples are diploids in this region
  * Init K     : 1000

Initialization:

Parsing specified genomic regions
  * Input region  [chr1:204291491-208562184]
  * Output region  [chr1:204491503-208362061]
  * #samples = 1 [0 haploids/ 1 diploid]
  * VCF/BCF scanning [Reg=chr1:204291491-208562184 / L=107405 (Lgl= 107405 (100%) - Lnl= 0 (0%))] (1.72s)
  * VCF/BCF scanning [Nm=1 (Nmh=0 - Nmd=1) / Nr=2503 (Nrh=0 - Nrd=2503)]
  * VCF/BCF parsing done (4.93s)
  * GMAP parsing [n=255802] (0.16s)
  * cM interpolation [s=0 / i=0] (0.00s)
Segmentation fault

We tried to impute the whole genome and chunk each chromosome following the tutorial. We did check all input and they were no problem, and it also worked in some other chromosomes. Could you provide some directions of where to trouble shoot the issue? Thanks!

**Comment by srubinacci** [comment]
Hi, 
I am not sure what the problem can be. Can you maybe try to download the version of GLIMPSE phase from the latest commit (yesterday evening) and tell me if you get something different? In the previous (dev) version, there was indeed a small bug regarding the input, when missing data are detected.

Please let me know,

Best,
Simone
