### ISSUE TITLE
ERROR when trying to generate chunks

### ISSUE THREAD

**Issue by aguilar-gomez** [odelaneau/GLIMPSE#32]
I am running the following:
 GLIMPSE_chunk --input $chr.imputed.vcf.gz --region $chr --window-size 2000000 --buffer-size 200000 --output chunks.$chr.txt --thread 5

For example for chr1 I get the following:
[GLIMPSE] Split chromosomes into chunks
  * Author        : Simone RUBINACCI & Olivier DELANEAU, University of Lausanne
  * Contact       : simone.rubinacci@unil.ch & olivier.delaneau@unil.ch
  * Version       : 1.1.0
  * Run date      : 03/02/2021 - 17:22:15

Files:
  * Input VCF      : [chr1.imputed.vcf.gz]
  * Chromosome     : [chr1]
  * Output file    : [chunks.chr1.txt]

Parameters:
  * Seed             : 15052011
  * #Threads   : 5
  * Min. Window size : 2000000bp / 1000 variants
  * Min. Buffer size : 200000bp / 100 variants

Reading input files
  * Main      : [chr1.imputed.vcf.gz]
  * #variants = 0 (79.36s)

ERROR: No markers in region: chr1. Check chromosome name and start/end positions.

And I get an error on it not having markers in that region. I am sure that vcf contains positions in chr1 so I am not sure what am i doing wrong

**Comment by aguilar-gomez** [comment]
i am not sure what I did wrong with the installation (it did not give me any error). However I tried running the static bins and it generates my chunks without any problems

**Comment by srubinacci** [comment]
Hi,

Not sure why the static binary worked and the compiled version did not. It seems that the versions differ for some reason. 
Have you downloaded the source code from the released version or from the latest commit?
Would it be possible for you to share the file?

Best,
Simone

**Comment by aguilar-gomez** [comment]
I downloaded it yesterday by : `git clone https://github.com/odelaneau/GLIMPSE.git`
They both say version 1.1
/programs/GLIMPSE/static_bins/GLIMPSE_phase_static

[GLIMPSE] Phase and impute low coverage sequencing data
  * Author        : Simone RUBINACCI & Olivier DELANEAU, University of Lausanne
  * Contact       : simone.rubinacci@unil.ch & olivier.delaneau@unil.ch
  * Version       : 1.1.0
  * Run date      : 04/02/2021 - 10:42:42

ERROR: You must specify one input file using --input

GLIMPSE_phase 

[GLIMPSE] Phase and impute low coverage sequencing data
  * Author        : Simone RUBINACCI & Olivier DELANEAU, University of Lausanne
  * Contact       : simone.rubinacci@unil.ch & olivier.delaneau@unil.ch
  * Version       : 1.1.0
  * Run date      : 04/02/2021 - 10:43:01

ERROR: You must specify one input file using --input

**Comment by srubinacci** [comment]
I have hard time to understand this error, as there were not public changes in GLIMPSE_chunk for the last ~4 months. Therefore the static binary should be based on same source code as the program you compiled. (please not that the release version and the latest commit can differ - but this does not seem to be a problem in this specific problem)
I really do not know why you get different results. 

If can you share your `chr.imputed.vcf.gz` I can manually check. I would only need the sites of the file.

Best,
Simone

**Comment by aguilar-gomez** [comment]
Hi Simone, 

Thank you for doing this. Here is the file I was using. As you pointed out I am including positions that are not biallelic (which I willl remove for my real run).

The trial I did with one chromosome ran without errors using the static bins, do you think there is a problem if I decide to do the whole project with the static bins?

[chr1.onlypos.vcf.zip](https://github.com/odelaneau/GLIMPSE/files/5954952/chr1.onlypos.vcf.zip)

Thank you,
Diana

**Comment by srubinacci** [comment]
Hi Diana,

Sorry for the delay. I've just run the compiled chunking program on your file and I do not get the same error. Same with the static_bin version. I really do not understand why this happened to you, maybe a problem during compilation? What version of htslib are you using?

Anyway, no problem with using the static_bin version. Just that it might be slower if you have many samples.

Best,
Simone

**Comment by aguilar-gomez** [comment]
htslib 1.11
Not sure why it did not work but I did it using the static bins and it seemed to work fine. Thank you
