### ISSUE TITLE
Lost some positions in the final file

### ISSUE THREAD

**Issue by aguilar-gomez** [odelaneau/GLIMPSE#33]
I am currently doing some trials and I am following your tutorial.
The final ligated chromosome 10 for my sample 10 is in the file 10_S44.chr10.merged.bcf
```
$ bcftools view -Ov Ligated/10_S44.chr10.merged.bcf|grep -v "#"|head -5
chr10	10381	chr10_10381	TAACCC	T	.	.	RAF=0.00375;AF=5.27011e-05;INFO=0.998	GT:DS:GP:HS	0/0:0:1,0,0:0
chr10	10394	chr10_10394	A	T	.	.	RAF=0.00375;AF=0.000103153;INFO=0.998	GT:DS:GP:HS	0/0:0:1,0,0:0
chr10	10937	chr10_10937	C	T	.	.	RAF=0.00375;AF=5.15829e-05;INFO=0.998	GT:DS:GP:HS	0/0:0:1,0,0:0
chr10	10980	chr10_10980	G	C	.	.	RAF=0.16;AF=0.0240238;INFO=0.998	GT:DS:GP:HS	0/0:0.048:0.952,0.048,0:0
chr10	10982	chr10_10982	G	A	.	.	RAF=0.06875;AF=0.023065;INFO=0.998	GT:DS:GP:HS	0/0:0.046:0.954,0.046,0:0

```
The following is the original genotype likelihoods (I generated this file in step 3 of the tutorial)
```
$ bcftools view -Ov 10_S44_L001.chr10.vcf.gz|grep -v "#"|head -5
chr10	10380	.	C	.	30.58	.	DP=3;MQ0F=0.333333;AC=0;AN=2;DP4=0,1,0,0;MQ=0	GT:PL:DP	0/0:0,3,4:1
chr10	10381	.	TAACCC	T	30.58	.	DP=3;MQ0F=0.333333;AC=0;AN=2;DP4=0,1,0,0;MQ=0	GT:PL:DP	0/0:0,3,4:1
chr10	10394	.	A	T	29.5864	.	DP=1;MQ0F=0;AC=0;AN=0;DP4=0,0,0,0;MQ=.	GT:PL:DP	./.:0,0,0:0
chr10	10411	.	TA	.	29.5864	.	DP=1;MQ0F=0;AC=0;AN=0;DP4=0,0,0,0;MQ=.	GT:PL:DP	./.:0,0,0:0
chr10	10430	.	C	A	.	.	.	GT	.

```
As you might notice some positions are not there, here I counted the total number of positions in each file:
```
$ bcftools view -Ov 10_S44_L001.chr10.vcf.gz|grep -v "#"|wc
1439244 14392440 149671377
$ bcftools view -Ov Ligated/10_S44.chr10.merged.bcf|grep -v "#"|wc
1277800 12778000 122345690
```

I am losing ~200K sites, I am not sure why. I saw there was another issue saying they lost positions with zero depth, could that be the reason?

**Comment by srubinacci** [comment]
Hi,

Indeed, your input is pretty different from what we recommend/use in the tutorial.
You really need to check the file containing your likelihoods, as it contains a strange pattern of variants. GLIMPSE takes only biallelic variants that belong at both the target and the reference panel, that is the reason why we perform genotype calling at the positions of the  reference panel.

From what I see you have probably problems during the process of genotype calling, as you have positions with the alt allele missing. These positions won't be found in the reference panel. Additionally, in the tutorial we strongly recommend to exclude indels, while you decided to include them. In theory, GLIMPSE should work fine for indels, but the callers might have problems at those loci, and these errors might propagate in the neighboring positions. 
We are currently testing callers to have more precise recommendations regarding indels from low-coverage data, but I really recommend to exclude them for now.

Hope this helps.
Simone

**Comment by aguilar-gomez** [comment]
Yes, thank you I think I will exclude indels and do biallelic positions.
