### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by rodrigopsav** [odelaneau/GLIMPSE#36]
Hello,
I am using GLIMPSE-phase static version and the analysis didn't finish because a segmentation fault (core dumped) occured.
What could cause this issue (I have 3tb of ram memory and 128 cores available). Please, find below the log for a single chunck:

Thanks,

[GLIMPSE] Phase and impute low coverage sequencing data
  * Author        : Simone RUBINACCI & Olivier DELANEAU, University of Lausanne
  * Contact       : simone.rubinacci@unil.ch & olivier.delaneau@unil.ch
  * Version       : 1.1.0
  * Run date      : 16/03/2021 - 16:24:21

Files:
  * Input VCF     : [/home/work/rps/output/imputeMe_ex2_50K_seq/phased/phased_29.vcf.gz]
  * Reference VCF : [/home/work/rps/test/ImputeMe2/examples/phased_filtered_holRefPop_chr29.vcf.gz]
  * Output VCF    : [/home/work/rps/output/imputeMe_ex2_50K_seq/imputed/imputed_16_29:47156074-51098442.bcf]
  * Input region  : [29:47156074-51098442]
  * Output region : [29:47176123-51098442]

Parameters:
  * Seed       : 15052011
  * #Threads   : 1
  * #Burnin    : 10
  * #Main      : 10
  * PBWT depth : 2
  * PBWT modulo: 8
  * HMM     : Constant recombination rate of 1cM per Mb
  * Ploidy     : All samples are diploids in this region
  * Init K     : 1000

Initialization:

Parsing specified genomic regions
  * Input region  [29:47156074-51098442]
  * Output region  [29:47176123-51098442]
  * #samples = 10 [0 haploids/ 10 diploids]
  * VCF/BCF scanning [Reg=29:47156074-51098442 / L=34 (Lgl= 34 (100%) - Lnl= 0 (0%))] (0.36s)
  * VCF/BCF scanning [Nm=10 (Nmh=0 - Nmd=10) / Nr=200 (Nrh=0 - Nrd=200)]
  * VCF/BCF parsing done (0.35s)
  * cM constant [1cM=1Mb]
Segmentation fault (core dumped)

**Comment by srubinacci** [comment]
Hi,
I see that a problem is that there are only 34 variants are found in common between the reference panel and the target dataset.
There's probably something wrong with the data, you need to check both how you produced your chunks and the target/reference data.

Hope this helps,
Simone

**Comment by rodrigopsav** [comment]
Thanks for your help!
