### ISSUE TITLE
Reference panel provided is not found

### ISSUE THREAD

**Issue by batelz** [odelaneau/GLIMPSE#37]
Hi,
when following [this](https://odelaneau.github.io/GLIMPSE/tutorial_b38.html#run_preliminaries) tutorial, 
I get an error 404 when trying to download the chromosome 22 reference panel (section 2.1 in the tutorial), using this command:
` > wget http://ftp.1000genomes.ebi.ac.uk/vol1/ftp/release/20130502/supporting/GRCh38_positions/ALL.chr22_GRCh38.genotypes.20170504.vcf.gz{,.tbi}`

When manually trying to look the data up in 1000 genomes, I found this note:

> March 2021 note:

> As noted below, there were a number of known issues with the files in this directory and there are now a number of alternatives available. As such, these files have been withdrawn.
> Users interested in the variants on GRCh38 should check the information about the data collection at : https://www.internationalgenome.org/data-portal/data-collection/30x-grch38.
> 
> Also, the GRCh38 liftover variants are still available at: https://www.ensembl.org/
> 
> Should you have any concerns, please contact us at info@1000genomes.org." 

Can you provide a compatible link for the reference panel?

Thanks,
Batel

**Comment by srubinacci** [comment]
Hi,
Indeed, few days ago they removed the link and point the newer version of the data. 

The newest version of the data can be found here: `http://ftp.1000genomes.ebi.ac.uk/vol1/ftp/data_collections/1000G_2504_high_coverage/working/20201028_3202_phased/`

Will update the tutorial as soon as possible. 
Hopefully running the tutorial on this newer version of the data won't be too different (other than changed the file names). 

Best wishes

Simone

**Comment by batelz** [comment]
> Hi,
> Indeed, few days ago they removed the link and point the newer version of the data.
> 
> The newest version of the data can be found here: `http://ftp.1000genomes.ebi.ac.uk/vol1/ftp/data_collections/1000G_2504_high_coverage/working/20201028_3202_phased/`
> 
> Will update the tutorial as soon as possible.
> Hopefully running the tutorial on this newer version of the data won't be too different (other than changed the file names).
> 
> Best wishes
> 
> Simone

Simone,
Thank you for your fast reply.

Unfortunatly it is not running smoothly :( 
I get this error when using it as reference panel in the tutorial:

`>bcftools annotate --rename-chrs chr_names.txt /mnt/c/Users/PC/Documents/aDNA/CCDG_14151_B01_GRM_WGS_2020-08-05_chr22.filtered.shapeit2-duohmm-phased.vcf.gz -Ou | bcftools view -m 2 -M 2 -v snps -s ^NA12878 --threads 4 -Ob -o reference_panel/1000GP.chr22.noNA12878.bcf

[W::bcf_sr_add_reader] No BGZF EOF marker; file '/mnt/c/Users/PC/Documents/aDNA/CCDG_14151_B01_GRM_WGS_2020-08-05_chr22.filtered.shapeit2-duohmm-phased.vcf.gz' may be truncated
[E::bgzf_read_block] Failed to read BGZF block data at offset 1055640 expected 2777 bytes; hread returned 684
[E::vcf_parse_format] Number of columns at chr22:10708001 does not match the number of samples (1998 vs 3202)
` 

Also, I noticed it is very small (1 MB), while you intended for a 200 MB file.

Thanks,
Batel

**Comment by lmtani** [comment]
@batelz It seems like your `CCDG_14151_B01_GRM_WGS_2020-08-05_chr22.filtered.shapeit2-duohmm-phased.vcf.gz` file is incomplete, probably the download has failed. In the FTP is said that it should have 519930289 bytes.

I also noted that this new file already has the `chr` prefix, so the basic QC could be only the second part of the command:

```sh
bcftools view -m 2 -M 2 -v snps -S ^NA19625,NA19703 --threads 4 -Ob \
    -o reference_panel/1000GP.chr${CHR}.filt.bcf \
    ALL.chr${CHR}_GRCh38.genotypes.20170504.vcf.gz
```

**Comment by batelz** [comment]
@lmtani Thank you for your reply.
I've tried to download and re-download the chr22, as well as chr1 and chr10 files from the folder @srubinacci posted, which always ends up with the same error of truncated file when running the bcf view code. 
I don't think there is a failure in download there, perhaps the files are corrupted. Does any of the files run well for you?

Anyway, I hope the tutorial will be updated soon.

Thanks,
Batel.

**Comment by lmtani** [comment]
Hi @batelz 

> Does any of the files run well for you?

Yes, it's running well. I download again the chr22 and it is working, but the download speed is painfully slow (717KB/s) even when using a Google Compute Engine VM (for better bandwidth). As you can see in the screenshot, the connection was closed and `wget` needed to "resume" the download.

![image](https://user-images.githubusercontent.com/12699242/113857387-da57f800-9778-11eb-821e-4a1f91524316.png)

Check your file size (in bytes) to see if it match what is expected, it is a quick and dirty way to check if it's ok.

**Comment by batelz** [comment]
Thank you @lmtani,
It was indeed an unsuccessful download issue.

I changed to another internet connection and it worked fine.
Thanks!
Batel
