### ISSUE TITLE
Inconsistent number of output loci based on whether no PL loci are included

### ISSUE THREAD

**Issue by Arkarachai** [odelaneau/GLIMPSE#38]
I have done several experiments with the GLIMPSE 1.1, but I face some unexpected behavior that I would need your guidance on.
If I start from the 1X bam file and call variant using bcftools mpileup on GRCh38, I would get 27.6M loci regardless of samples. However, lots of them has no quality score and PL field. I understood that this indicate missing loci with no mapped read. If I decide to filter out these empty loci, I would end up around 14.5M-16.2M loci depend on my samples. For my sample A, I would have 16.26M loci left. 
The last three loci are the one that I filter out using QUAL filter. 

![Screen Shot 2021-03-09 at 11 02 38 AM](https://user-images.githubusercontent.com/1155815/113449543-12071e80-93cc-11eb-8ef0-1e6e2258f15a.png)

The confusion part is when I run GLIMPSE on this sample A alone (without any other samples except ref panel), I would end up 16.15 or 16.52M loci depend on whether use filter or non-filter for empty loci. I thought they suppose to be the same. Does this mean that if I filter out loci with PL=0 first, GLIMPSE will only do genotype refinement, otherwise, it would impute as well, so I end up able to genotype loci that has no reads mapped to? 
However, if I run GLIMPSE using multiple samples, my sample A even after I filter out all loci wth no QUAL value, it would end up with many more loci (26M in this case), so it seems that my explanation about genotype refinement vs both genotype refinement and imputation doesn't sound. For sure, imputation is going on here. I get very confused at this point why did I get different results when I filter or not filter empty loci. Would you mind help me clarify it a bit?

**Comment by srubinacci** [comment]
Hi,
Thank you for your question, and sorry for the delay in the answer.
Indeed, the key point is to let the caller to take the decision about what variants have data or not. Therefore, in GLIMPSE we take the most conservative approach, and by default GLIMPSE_phase only works with the intersection of variants between the target and reference panel. 

Dealing with low-coverage, we would get many times in a situation where a variant is called as missing by the caller. In this case there are several possible representations, such as a completely missing site (e.g. the last three variants in your example), a missing FORMAT/PL field or flat likelihood information, (e.g. FORMAT/PL=0,0,0).
GLIMPSE_phase should (hopefully) consider all these three cases as the same, calling an uniform likelihood. 

Therefore, if you filter out variants (for example those having a QUAL field < some threshold), you might get in the situation of having a different number of sites in each of your target samples (as you might have reads covering a specific position for one sample and not for others). When these files are merged together, you should get a file containing the union of these sites. This might explain why you get a different number of sites when you use GLIMPSE on one or multiple samples.
Please let me know if you think this is the case.

Another option you might want to use to get an uniform number of sites in output is `--impute-reference-only-variants`, in this case you force imputation at all sites in the reference panel (and not only in the intersection). This approach is not default, as we really want to users to ask the caller to take the decision of what variant has a flat likelihood or not.

Hope this helps,

Simone

**Comment by Arkarachai** [comment]
Hi Simone,
This is very helpful. Thank you very much for your answer. I took a look into the data based on your recommendation. Here is what I found.
- For differences between 1 sample GLIMPSE run with and without QUAL prefilter, I found that some of loci that have flat likelihood are also imputed by GLIMPSE like this one. 
1       16114   .       G       A       .       .       DP=1;MQ0F=0;AC=0;AN=0;DP4=0,0,0,0;MQ=.  GT:PL:DP        ./.:0,0,0:0
So, the DP is >0, but PL is flat. I'm still not quite sure why this is the case.
- For multi-sample GLIMPSE run, it could be as you mentioned. However, the genotype of loci for a sample that has no read mapped to is also present in the final results, but not as no-call. In the cases I see, they are 0|0. I did not use --impute-reference-only-variants here, so I think the no-call is encoded the same way as ref call here. I wonder if there is an option to output ./. or anything that I can distinguish ref call from no call instead? I think what I need is the opposite of --impute-reference-only-variants. I don't want imputation the loci that has no read mapped to.

**Comment by srubinacci** [comment]
Hi,
Regarding the two points you raised:
1. Here I tend too think that at this position we have a single "high quality" mapped read that neither is G or A. You can maybe verify this using samtools tview from your bam file. Anyway, the caller outputs a flat likelihood and glimpse uses this information and performs "standard" (=missing data) imputation.
2. Here what happens is that missing data for a sample is again interpreted as a flat likelihood. As the variant is present, standard imputation is triggered and very often this case is imputed as 0|0. Anyway, I remark that your variant is imputed from a flat likelihood and not considered as ref/ref. 
So, if the variant is present and has samples with missing data, it is always imputed. Therefore, to avoid imputation at loci that have no reads mapped, you unfortunately have to filter your genotype likelihood VCFs to those sites having DP>=1 (plus other filters) and then impute one sample at the time.

Another possibility is to impute the merged target file and then filtering sites based on the INFO score.

Best wishes
Simone

**Comment by Arkarachai** [comment]
That is crystal clear. Many thanks Simone!
