### ISSUE TITLE
Possible solution to put_time problem with older GCC compilers

### ISSUE THREAD

**Issue by DanielEWeeks** [odelaneau/GLIMPSE#39]
The documentation states:

> "In order to compile, we require a modern Linux operating system and a version of GCC > 4.4."

but it failed to compile under GCC 4.8.5, complaining about `std::put_time` not being defined. 

I know updating the g++ compiler version would also solve this problem, but this easier faster solution appears to have worked just fine (although I haven't tested the compiled code yet).  If this looks OK, consider adding this to your `timer.h` file. 

**Problem:** GLIMPSE modules failed to compile under GCC 4.8.5 because std::put_time was not defined.

```
$ gcc --version
gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-39)
```
**Solution:** Change `std::put_time` to `put_time` and paste this definition into `timer.h`

```
#if __GNUC__ && __GNUC__ < 5
#include <ostream>  // std::basic_ostream
#include <ios>      // std::ios_base
#include <locale>   // std::use_facet, std::time_put
#include <iterator> // std::ostreambuf_iterator

template<typename CharT>
struct _put_time                   
{                                                                     
  const std::tm* time;
  const char *fmt;
};
    
template<typename CharT>
inline _put_time<CharT>
put_time(const std::tm* time, const CharT* fmt)
{ return { time, fmt }; }
  
template<typename CharT, typename Traits>
std::basic_ostream<CharT, Traits>&
operator<<(std::basic_ostream<CharT, Traits> &os, _put_time<CharT> f)
{   
  typedef typename std::ostreambuf_iterator<CharT, Traits> Iter;
  typedef std::time_put<CharT, Iter> TimePut;
      
  const CharT* const fmt_end = f.fmt + Traits::length(f.fmt);
  const TimePut& mp = std::use_facet<TimePut>(os.getloc());
    
  std::ios_base::iostate err = std::ios_base::goodbit;
  try {
    if (mp.put(Iter(os.rdbuf()), os, os.fill(), f.time, f.fmt, fmt_end).failed())
      err |= std::ios_base::badbit;
  }
  catch (...) {
    err |= std::ios_base::badbit;
  }  
   
  if (err)
    os.setstate(err);

  return os;
} 

#endif
```

Solution from: https://stackoverflow.com/questions/37421747/is-there-a-builtin-alternative-to-stdput-time-for-gcc-5

**Comment by srubinacci** [comment]
Thanks, will consider this for the next release.
