### ISSUE TITLE
Problematic overlapping between chunks: Chr X non-PAR region

### ISSUE THREAD

**Issue by MySelvan** [odelaneau/GLIMPSE#40]
Hi,

Thanks for the great tool and documentation! 
When running GLIMPSE_ligate for chrX:non-PAR region, I get 'problematic overlapping between chunks' error only when the samples are of mixed ploidy.

Please see below (I am using version 1.1.0).
Ligating chunks
  * Create all file descriptors
  * Extract sample IDs
  * FPLOIDY = -2 [Mixed haploid/diploid samples in the region]
  * Checking samples and FPLOIDY consistency across all input files
  * Samples overlap and FPLOIDY are consistent across files.
  * #samples = 10 [5 haploids/ 5 diploids]
  * #main_iterations = 10

Chunk 1 from position [2781604]
...
...
ERROR: ^[[0mProblematic overlapping between chunks):

I used the below code:
GLIMPSE_chunk --input $REF --region chrX:2781480-155701382 --output chunks.chr${CHR}.txt

GLIMPSE_phase --input ${VCF} --reference ${REF} --map ${MAP} --thread 16 --input-region ${IRG} --output-region ${ORG} --output ${OUT} --samples-file sampleid_gender.txt

GLIMPSE_ligate --input ${LST} --output $OUT

and below are the first few lines of the chunk file generated. There doesn't seem to be any obvious overlap
0       chrX    chrX:2781514-4921416    chrX:2781514-4721330    1939817 42675
1       chrX    chrX:4521302-6940305    chrX:4721343-6740220    2018878 42674
2       chrX    chrX:6540236-8244296    chrX:6740255-8044234    1303980 21338

However, GLIMPSE_ligate_static seems to be running without error.

Could you please let me know why GLIMPSE_ligate to be failing? 
Would it be okay to proceed with the GLIMPSE_ligate_static ?  

Thanks,
Myvizhi

**Comment by srubinacci** [comment]
Hi, 

If I understand correctly, your're saying that the release version (v1.1.0) and the static binary of the same release version have different behaviors? This is a bit strange honestly. How did you donwload GLIMPSE?
It is really difficult to provide an answer from this. Are you using only SNPs, right (no indels)?

**Comment by MySelvan** [comment]
Hi,

GLIMPSE was downloaded from github (https://github.com/odelaneau/GLIMPSE, and the v1.1.0 version). I used the static version from the same release (glimpse/1.1.0/src/GLIMPSE/static_bins/)

I am using both SNPs and indels. Since indels' genotype likelihoods were generated using GATK (and not bcftools), I have included them.

If you could please let me know what additional data would be required to sort this out, I would be happy to provide them to you.

**Comment by srubinacci** [comment]
Ok, this is more clear now. I think the problem is due to the use of indels. Indeed we solved this problem in a more recent version of GLIMPSE, not release yet. Please contact me in private (by email), I can help if this issue.

**Comment by srubinacci** [comment]
Hi,
sorry for coming back to this.
Can you try again with v1.1.1?

Best,
Simone

**Comment by soyeon-2023** [comment]
Hello, 
I'm encountering the same error mentioned earlier: "ERROR: Three files overlapping at position: 96027772." using GLIMPSE2 ligate.
Is there a possible solution to address this issue?
