### ISSUE TITLE
Does GLIMPSE accept the 10 number PL format or empty ALT columns?

### ISSUE THREAD

**Issue by devenvyas89** [odelaneau/GLIMPSE#41]
I have VCFs that have the 10-number PL format (i.e., AA, AC, AG, AT, CC, CG, CT, GG, GT, TT) instead of the Ref-Ref, Ref-Alt, Alt-Alt format. Is this compatible with Glimpse?

Also, my VCFs do not have the ALT column filled in for 0/0 genotypes. I have been using --impute-reference-only-variants. Will that still use information from my VCFs?

**Comment by srubinacci** [comment]
Hi, 

No, as said in the tutorial GLIMPSE works on biallelic variants, and it accepts only a more standard PL field in the VCF file, RR,RA,AA.  
Not having the ALT  is not considered a valid locus for GLIMPSE, and it should discard the site. You might want to recall the likelihoods in a different way to match what we describe in the tutorial.

In the case you generated this with a caller like angsd, you can use something along the lines of:
`angsd [some option like, -bam -GL -out]  -doMajorMinor 3 -sites reference.sites -dobcf 1 -dopost 1 -domaf 1 --ignore-RG 0 -dogeno 1 -docounts 1`
They explain how to create the *.sites file in the documentation, and reference.sites are the sites of your reference panel.

**Comment by devenvyas89** [comment]
Thank you for the clarification. Also, during imputation, does GLIMPSE
refer to the GT call at all, or just the RR,RA,AA PL field?

**Comment by srubinacci** [comment]
GLIMPSE only uses the PL field for the study dataset. GT is only used for the reference panel.

Hope this helps,
Simone
