### ISSUE TITLE
Multi-Allelic records

### ISSUE THREAD

**Issue by MySelvan** [odelaneau/GLIMPSE#43]
Hello,

I have a question regarding indels and multi-allelic sites.

In the tutorials, it is suggested to remove indels because the genotype likelihood calculated using bcftools is not accurate. If the genotype likelihood is calculated using GATK can they be included?

Also if my vcf file contains multi-allelic sites, could I decompose and normalize the vcf and then run the GLIMPSE with multi-allelic records listed as bi-allelic sites? Or is it better to remove the muti-allelic sites before running GLIMPSE?

**Comment by srubinacci** [comment]
Hi,

indeed it seems to be a problem only related to bcftools. We did some tests with Freebayes and there are no problems arising from it. I assume GATK should be the same as Freebayes. 
If you have some validation data, the best thing you could do, would be to test. 

Regarding your second question, splitting multi-allelic to bi-allellic should be fine in the general case.
However, you might need to be a bit careful when you merge these back, and it can be non-so-obvious.

**Comment by ratrrs** [comment]
Hi,

Can you please share the freebayes command line arguments you are using to force call indels? I am trying to do something similar and am having trouble with freebayes. This might be a bug with freebayes, but the resulting alleles (i.e., indels) being output are not the same set of alleles I am passing it using the `--variant-input` and `--only-use-input-alleles` options.

E.g.,
`freebayes -f reference_fasta/unzipped/hs37d5.fa --variant-input reference_panels_prepped/chr20/ALL.chr20.phase3_shapeit2_mvncall_integrated_v5b.20130502.genotypes.prepped.sites.vcf.gz --only-use-input-alleles --min-alternate-count 0 --min-alternate-fraction 0 --min-coverage 0 -r 20 target_samples/sample.bam`
