### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by jecady** [odelaneau/GLIMPSE#44]
I'm having an issue where I hit a segmentation fault
Parsing specified genomic regions
  * Input region  [4:154527615-157999090]
  * Output region  [4:154728117-157798858]
  * VCF/BCF scanning ...^M  * #samples = 1 [0 haploids/ 1 diploid]
  * VCF/BCF scanning [Reg=4:154527615-157999090 / L=18263 (Lgl= 18263 (100%) - Lnl= 0 (0%))] (3.00s)
  * VCF/BCF scanning [Nm=1 (Nmh=0 - Nmd=1) / Nr=2504 (Nrh=0 - Nrd=2504)]
  * VCF/BCF parsing VCF/BCF parsing [84%]
^M/home/snapshot/wgs/GLIMPSE_beagle_imputation.sh: line 45: 44572 Segmentation fault      GLIMPSE_phase --input ${bcftools_vcf} --reference ${REF} --map ${MAP} --input-region $
{IRG} --output-region ${ORG} --output ${OUT} --thread $threads --samples-file $sample_ploidy

Then I'll re-run the exact same thing and it works fine

 * Input region  [4:154527615-157999090]
  * Output region  [4:154728117-157798858]
  * VCF/BCF scanning ...^M  * #samples = 1 [0 haploids/ 1 diploid]
  * VCF/BCF scanning [Reg=4:154527615-157999090 / L=18263 (Lgl= 18263 (100%) - Lnl= 0 (0%))] (3.63s)
  * VCF/BCF scanning [Nm=1 (Nmh=0 - Nmd=1) / Nr=2504 (Nrh=0 - Nrd=2504)]
  * VCF/BCF parsing done (4.26s)
  * GMAP parsing [n=211115] (0.21s)
  * cM interpolation [s=3149 / i=12308] (0.01s)
  * Region spans 3470836 bp and 4.53 cM
And then it proceeds as normal

I'm looping over all chunks of all chromosomes. I've run this on several different input VCFs and there's no consistency in terms on which chunks it happens on and it generally works the 2nd time around. There are a couple I've had to do 3 times. Every time this has been the only process running on the machine.

**Comment by srubinacci** [comment]
Hi,
The error seems to happen during the reading of the file, which makes it very weird that sometimes it runs and sometimes not (as if there was an error in the input file, you would always get the problem). 
Obvious question, are you sure you allocated enough RAM to the process and all these jobs have the space to run on your system? Might simply be that it tries to allocate RAM and it cannot. 
Best,
Simone

**Comment by jecady** [comment]
There should be plenty of RAM, especially given nothing is different between the times it fails and the times it doesn't.

**Comment by jecady** [comment]
Well, I guess the only difference is that when I re-run it, I'm skipping all of the chunks that have completed successfully, but the command for that chunk is exactly the same and the environment is the same.
