### ISSUE TITLE
tutorial vcf no longer exists

### ISSUE THREAD

**Issue by Zepeng-Mu** [odelaneau/GLIMPSE#45]
Hi, I think due to recent update in 1000G, the example file used in the tutorial no longer exists. Thanks

https://github.com/odelaneau/GLIMPSE/blob/38ebc50f0d2e924f2477170773247281fca77dcf/tutorial/step2_script_reference_panel.sh#L6

**Comment by srubinacci** [comment]
Hi,
Yes that is true.
We are planning to schedule a new release of GLIMPSE by tomorrow, and we'll update the links and the tutorial. In the meantime you can maybe follow the tutorial in b37.

Best wishes,

Simone

**Comment by srubinacci** [comment]
The new release is now online, together with the updated tutorial.
Hope this solves your issue.

Simone
