### ISSUE TITLE
Error building rephase with GLIMPSE version 1.0.0

### ISSUE THREAD

**Issue by moravveji** [odelaneau/GLIMPSE#46]
Hi

I'm trying to compile GLIMPSE from source using foss/2018a toolchain on our cluster. However, I get the following error message:

```bash
rm -f obj/*.o bin/GLIMPSE_rephase
g++ -std=c++11 -O3 -c src/containers/haplotype_set.cpp -o obj/haplotype_set.o -Isrc -I/apps/leuven/skylake/2018a/software/HTSlib/1.9-GCC-6.4.0-2.28/include/htslib -I/apps/leuven/skylake/2018a/software/Boost/1.70.0-foss-2018a/include
In file included from src/containers/haplotype_set.cpp:24:0:
src/containers/haplotype_set.h:30:37: fatal error: containers/genotype_set.h: No such file or directory
 #include <containers/genotype_set.h>
                                     ^
compilation terminated.
make: *** [obj/haplotype_set.o] Error 1
```
When I check for `genotype_set.h`, I can just find it under the source tree, so no idea why it cannot be found:
```bash
$ find GLIMPSE-1.0.0/ -name genotype_set.h
GLIMPSE-1.0.0/phase/src/containers/genotype_set.h
```
Do you have an idea how to fix this?

Please do not hesitate to contact me if you need additional information.

Regards
Ehsan

**Comment by srubinacci** [comment]
Hi, 
indeed I am not sure why this happens. 
However, you are trying to compile an old version of GLIMPSE and in particular a tool that is not maintained anymore (actually it was never maintained or described anywhere). What I am trying to say is that there is no need to compile this tool and it was our mistake to leave it there in v1.1.0.
I'd recommend to actually compile a newer release version of GLIMPSE if possible. 

Best wishes,

Simone

**Comment by moravveji** [comment]
@srubinacci thanks for your comment. You were right; skipping the building of `reshape` easily helped me proceed with the whole built.
Best
