### ISSUE TITLE
 Input region needs to be specificied as chrX:Y-Z (chromosome ID cannot be extracted)

### ISSUE THREAD

**Issue by batelz** [odelaneau/GLIMPSE#48]
Hi,
In step 5.1, I'm trying to run this code:
`while IFS="" read -r LINE || [ -n "$LINE" ]; do printf -v ID "%02d" $(echo $LINE | cut -d" " -f1); IRG=$(echo $LINE | cut -d" " -f3); ORG=$(echo $LINE | cut -d" " -f4); OUT=GLIMPSE_imputed/NA12878.chr22.1x.${ID}.bcf; bin/GLIMPSE_phase --input ${VCF} --reference ${REF} --map ${MAP} --input-region ${IRG} --output-region ${ORG} --output ${OUT}; bcftools index -f ${OUT}; done < chunks.chr22.txt`

For some reason, it shows that the format of the input region is wrong (even though the pattern is there in the parameter list printed at the beginning of phasing for each chunk).

```
-bash: printf: 2        chr22   chr22:19786071-22595399 chr22:19986107-22395366 2409260 58114: invalid number

[GLIMPSE] Phase and impute low coverage sequencing data
  * Author        : Simone RUBINACCI & Olivier DELANEAU, University of Lausanne
  * Contact       : simone.rubinacci@unil.ch & olivier.delaneau@unil.ch
  * Version       : 1.1.0
  * Run date      : 31/05/2021 - 13:30:40

Files:
  * Input VCF     : [NA12878_1x_vcf/NA12878.chr22.1x.vcf.gz]
  * Reference VCF : [reference_panel/1000GP.chr22.noNA12878.bcf]
  * Genetic Map   : [../maps/genetic_maps.b38/chr22.b38.gmap.gz]
  * Output VCF    : [GLIMPSE_imputed/NA12878.chr22.1x.02.bcf]
  * Input region  : [2  chr22   chr22:19786071-22595399 chr22:19986107-22395366 2409260 58114]
  * Output region : [2  chr22   chr22:19786071-22595399 chr22:19986107-22395366 2409260 58114]

Parameters:
  * Seed       : 15052011
  * #Threads   : 1
  * #Burnin    : 10
  * #Main      : 10
  * PBWT depth : 2
  * PBWT modulo: 8
  * HMM     : Recombination rates given by genetic map
  * Ploidy     : All samples are diploids in this region
  * Init K     : 1000

Initialization:

Parsing specified genomic regions

ERROR: Input region needs to be specificied as chrX:Y-Z (chromosome ID cannot be extracted)
```
Any idea what's the problem?
Thanks,
Batel.

**Comment by srubinacci** [comment]
Hi,
Indeed your Input/output regions are not well defined and GLIMPSE rightly complains about it. You should have `chr22:19786071-22595399` as an input region and 'chr22:19986107-22395366' as your output region. 

For some reason your script/loop is not working as expected and even the printf command fails. I've just re-run the same script on my system and everything works well. I send you my set of chunks, try to re-run the same script on this file. If this does not work as well, there's something on your side and I do not know how help with that.

[chunks.chr22.txt](https://github.com/odelaneau/GLIMPSE/files/6570338/chunks.chr22.txt)

**Comment by batelz** [comment]
@srubinacci, as always, thank you for your fast reply.

I closed and re-opened the shell, then re-ran the code - it worked perfectly.
should have tried that before coming up here...
Sorry for the waste of time. 

Batel
