### ISSUE TITLE
Still can't run concordance due to unrecognized option --info_af

### ISSUE THREAD

**Issue by batelz** [odelaneau/GLIMPSE#49]
This issue continues issue #42.

The problem still consists.
Whenever I run the command:
```
 > ./bin/GLIMPSE_concordance --input concordance.lst --minDP 8 --output GLIMPSE_concordance/output --minPROB 0.9999 \
 > --bins 0.00000 0.00100 0.00200 0.00500 0.01000 0.05000 0.10000 0.20000 0.50000 \
 > --info_af AF_nfe --thread 4
```
 (or the `./step8_script_concordance.sh` script), I get the following message:
`Error parsing command line arguments: unrecognised option '--info_af'
`
I first faced this issue when working according to the tutorial.
Now again - when working on another simulation.

Why can't the script acknowledge the `'--info_af'` option?

**Comment by srubinacci** [comment]
What version of GLIMPSE are you using?

**Comment by batelz** [comment]
according to README.md
### Versions

**Current Release: 1.1.0**. Release date: October 07, 2020

**Comment by srubinacci** [comment]
Just checked, and it is indeed a typo in the tutorial. From v1.1.0 this option has changed name to af-tag (for compatibility with bcftools stats).
The typo was only in the online version of the tutorial, ./step8_script_concordance.sh (at least in the latest release) does contain the right name for this option. I've just updated the website to fix the typo. 
Thanks,
Simone
