### ISSUE TITLE
missing GP/HS/DS field in output

### ISSUE THREAD

**Issue by Arkarachai** [odelaneau/GLIMPSE#52]
I try GLIMPSE 1.1 and 1.1.1 and got very good results. However, I noticed that I only have GT field in output, not the GP/HS/DS when I follow the tutorial. Have these features been dropped? If not, could you recommend the parameter that I could use to show these values? I could not find it from the command line manual page. Thank you!

**Comment by srubinacci** [comment]
Hi,
You should be able to get the GP/HS/DS after the ligation step (and not the sample step). Have you checked those files?

**Comment by Arkarachai** [comment]
Thank you for your reply. Yes, you are correct. Thanks for pointing that out.
I just wonder if there is any particular season not to keep those flag after `sample` step?

**Comment by srubinacci** [comment]
Nothing particular. Indeed it would be possible to include DS and GP after the sample step as it might be useful for the users. For now, we split this in two different files.
