### ISSUE TITLE
GLIMPSE_sample samples same two haplotypes

### ISSUE THREAD

**Issue by batelz** [odelaneau/GLIMPSE#55]
Hi,

I'm using your tutorial data and trying to sample from the genotype posterior distribution outputted from the Ligate module.

When I reach GLIMPSE_sample I get an odd output for the `--sample` option.
When sampling 50 individuals, I get the same two haplotypes.
meaning I get 50 sets of the same 2 haplotypes 
(the two haplotypes are not identical, but haplotype1 for sample1 is identical for haplotype1 in sample2-50, and the same for haplotype2 ).

The input of GLIMPSE_sample is the ligated genotype posterior distribution ([this is mine](https://drive.google.com/file/d/1GyH_3wI_t5SZTClEputmJLV6gjDsm62u/view?usp=sharing) and [index ](https://drive.google.com/file/d/1hVRObXqwoyOPE4WgM4FInkzsWKBUMF6x/view?usp=sharing)).
And this is my code:
```
VCF=GLIMPSE_ligate/NA12878.chr22.merged.bcf
for i in {1..50}; do
		OUT=GLIMPSE_phased/NA12878.sample.chr22.${i}.phased.bcf	 
		/bin/GLIMPSE_sample --input ${VCF} --sample --output ${OUT}
		bcftools index -f ${OUT}
		done
#merge samples to onc vcf
ls GLIMPSE_phased/*sample*.bcf > GLIMPSE_phased/50inds_bcf
bcftools merge -l GLIMPSE_phased/50_inds_bcf -o GLIMPSE_phased/50.bcf --force-samples
bcftools view GLIMPSE_phased/50.bcf
```
[Here ](https://drive.google.com/file/d/1zDMhWq-1As4OdI-HISzDn9dBCpbpNRiV/view?usp=sharing)is an example of the output with 10 inds.

I tried looking at the output bcf file (that from my understanding should contain 10 samples with at least slightly different phase) in R and compare the haplotypes:
```
bcf.10<-read.vcfR("0.bcf")
bcf.10.gt<-bcf.10@gt
sum(bcf.10.gt[,i]!=bcf.10.gt[,j])
```
This results in a 0 for each i and j I choose.
_________
I've also compared these haplotypes to the output of GLIMPSE_sample with the `--solve` option on, and it does not match.
Meaning the 2 haplotypes that are sampled again and again are not the same as the "best fit" phase.

Am I doing something wrong or perhaps there is a problem with the sampling algorithm?

Thank you,
Batel

**Comment by srubinacci** [comment]
Hi,
Thank you for the feedback. 
Indeed, the sampling algorithm was developed quite same time ago and it has never really been in use, therefore it might be an internal bug. Unfortunately I cannot look at this in details soon, but I'll add this in the list of check/fixes for the next release. 
Best wishes,
Simone
