### ISSUE TITLE
Selection of high quality Glimpse imputed markers

### ISSUE THREAD

**Issue by PengZhangJHU** [odelaneau/GLIMPSE#57]
I have a question on how to select good imputed markers from Glimpse and wondering if anyone has any experiences that you can share. I noticed that the Glimpse output doesn't have the "R2" measure, Estimated Imputation Accuracy (R-square), that people usually use to filter SNPs for downstream association analysis. It has an "INFO" column described as "IMPUTE info quality score for diploid samples". Is the "INFO" something similar to "R2", or something very different? What measures (and their empirical cut-offs) can we use to select high confidence imputed markers? Thank you!

**Comment by srubinacci** [comment]
Hi,

Indeed, GLIMPSE uses the IMPUTE INFO score. The INFO score is pretty popular in the GWAS setting, you will be able to find many papers discussing about it and its common cutoff (e.g. https://static-content.springer.com/esm/art%3A10.1038%2Fnrg2796/MediaObjects/41576_2010_BFnrg2796_MOESM3_ESM.pdf provides a good description).

Depending on the experimental settings, different cutoffs can be used. In a normal scenario, an INFO score >0.8 should imply good imputation. You might want to relax or have a stringent threshold dependent on your application, the amount of markers you want to keep/discard, etc. 

Hope this helps,

Simone

**Comment by PengZhangJHU** [comment]
Thank you Simone for your response, This is very helpful and I’ll take a look.

Peng

From: Simone Rubinacci ***@***.***>
Date: Monday, July 5, 2021 at 8:15 AM
To: odelaneau/GLIMPSE ***@***.***>
Cc: Peng Zhang ***@***.***>, Author ***@***.***>
Subject: Re: [odelaneau/GLIMPSE] Selection of high quality Glimpse imputed markers (#57)



Hi,

Indeed, GLIMPSE uses the IMPUTE INFO score. The INFO score is pretty popular in the GWAS setting, you will be able to find many papers discussing about it and its common cutoff (e.g. https://static-content.springer.com/esm/art%3A10.1038%2Fnrg2796/MediaObjects/41576_2010_BFnrg2796_MOESM3_ESM.pdf<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fstatic-content.springer.com%2Fesm%2Fart%253A10.1038%252Fnrg2796%2FMediaObjects%2F41576_2010_BFnrg2796_MOESM3_ESM.pdf&data=04%7C01%7Cpzhang13%40jhmi.edu%7C9025fe392ed54e349a7308d93fae6e5a%7C9fa4f438b1e6473b803f86f8aedf0dec%7C0%7C0%7C637610841134745707%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=YxVOhAY6WRdSPvxlyvEKAkkQfwQqoJfECPACjD0oxWk%3D&reserved=0> provides a good description).

Depending on the experimental settings, different cutoffs can be used. In a normal scenario, an INFO score >0.8 should imply good imputation. You might want to relax or have a stringent threshold dependent on your application, the amount of markers you want to keep/discard, etc.

Hope this helps,

Simone
