### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by gibberwocky** [odelaneau/GLIMPSE#58]
Hi

Is there some documentation explaining the various files output from the concordance script, and what each of the columns within those files relate to? As an example, the software outputs an error rate but it's not immediately clear how to calculate that value from any of the files output. I'm struggling to find details.

Cheers

D

**Comment by srubinacci** [comment]
Hi, 
Indeed the concordance tool and output are not documented and there is no plan to fully document the output. However, in the latest release [v1.1.1] I've added self-explanatory headers, similarly to bcftools stats (except of the .rsquare.grp.txt file that is typically used for quick plotting). Are any of those not clear to you?

Simone

**Comment by gibberwocky** [comment]
Thanks

I've been using the previous version. Judging by the change log, am I correct in my understanding that the structure of the output files for the concordance tool have not changed, and that the columns from these files generated by v1.1.0 relate to the same headers output by v1.1.1, identifiable in the code (GLIMPSE/concordance/src/containers/call_set_writing.cpp)?

Cheers

D

**Comment by srubinacci** [comment]
Unfortunately not: as the changelog says, there are big changes in the output format. Therefore my recommendation is to run the concordance too v1.1.1 instead.

Best wishes,
Simone

**Comment by gibberwocky** [comment]
The change log from v1.1.0 to v1.1.1 doesn't indicate that there has been any big changes in the output format. A few bug fixes are mentioned along with a couple of extra options. Are the changes more comprehensive than described here:

https://github.com/odelaneau/GLIMPSE/blob/master/versions/CHANGELOG.md
