### ISSUE TITLE
GLIMPSE_ligate and GLIMPSE_sample drop each the first variant of input bcf file

### ISSUE THREAD

**Issue by mcieslik-mctp** [odelaneau/GLIMPSE#59]
I believe I ran into an issue where GLIMPSE commands drop the first variant of input.

The files to reproduce are here:
https://drive.google.com/file/d/1MxK7Krn-zv_zb7ThnVDURPrixj2xrIqF/view?usp=sharing

Thank you for your great tool!

I have the following two files generated by GLIMPSE_phase
```
glimpse-chrX-01-tiny.bcf
glimpse-chrX-02-tiny.bcf
```
The header looks like this:
```
##fileformat=VCFv4.2
##FILTER=<ID=PASS,Description="All filters passed">
##fileDate=26/07/2021 - 05:47:58
##source=GLIMPSE_phase v1.1.1
##contig=<ID=chrX>
##INFO=<ID=RAF,Number=A,Type=Float,Description="ALT allele frequency in the reference panel">
##INFO=<ID=AF,Number=A,Type=Float,Description="ALT allele frequency computed from DS/GP field across target samples">
##INFO=<ID=BUF,Number=A,Type=Integer,Description="Is it a variant site falling within buffer regions? (0=no/1=yes)">
##FORMAT=<ID=GT,Number=1,Type=String,Description="Unphased genotypes">
##FORMAT=<ID=DS,Number=1,Type=Float,Description="Genotype dosage">
##FORMAT=<ID=GP,Number=3,Type=Float,Description="Genotype posteriors">
##FORMAT=<ID=HS,Number=1,Type=Integer,Description="Sampled haplotype pairs packed into intergers (max: 15 pairs, see NMAIN header line)">
##NMAIN=15
##FPLOIDY=-2
##INFO=<ID=AC,Number=A,Type=Integer,Description="Allele count in genotypes">
##INFO=<ID=AN,Number=1,Type=Integer,Description="Total number of alleles in called genotypes">
```
We can count the number of unique records
```
bcftools index --nrecords glimpse-chrX-01-tiny.bcf # 88926
bcftools isec -C glimpse-chrX-02-tiny.bcf glimpse-chrX-01-tiny.bcf # 43497
```
For a total of 132423 variants

If we run GLIMPSE_ligate, and count
```
GLIMPSE_ligate --input file_list.txt -O ligated.bcf --thread 8
bcftools index --nrecords ligated.bcf
```
We get 132422.

After running GLIMPSE_sample
```
GLIMPSE_sample --solve --input ligated.bcf --output phased.bcf --thread 8
bcftools index --nrecords phased.bcf
```
And count the number of variants, we get 132421.

We can see what is missing:

```
bcftools isec -C glimpse-chrX-01-tiny.bcf ligated.bcf
chrX	2781514	C	A	10
bcftools isec -C glimpse-chrX-01-tiny.bcf phased.bcf
chrX	2781514	C	A	10
chrX	2781518	A	G	10
```
Which are the first two variants in the first bcf file
```
bcftools view glimpse-chrX-01-tiny.bcf | grep -v '#' | cut -f 1-4 | head -n5
chrX	2781514	.	C
chrX	2781518	.	A
chrX	2781584	.	A
chrX	2781604	.	G
chrX	2781635	.	G
```

**Comment by srubinacci** [comment]
Hi,
Sorry for the delay. 
Are you sure these two first variants are not labelled as "BUF" in the INFO field?

**Comment by mcieslik-mctp** [comment]
The input files `glimpse-chrX-01-tiny.bcf` and `glimpse-chrX-02-tiny.bcf` have 88926 and 50947 variants labeled as 'BUF', but the out `ligated.bcf` and `phased.bcf` have none.

**Comment by srubinacci** [comment]
Indeed, the ligated output should not have any variant labelled as BUF.
GLIMPSE_phase outputs also buffer variants in the output file. The purpose of the ligation step is to use the overlapping data of the buffer to provide good phasing between connected regions. Therefore, variants that are labelled as BUF are only internally used for the ligation step, and are reported in output only once.

**Comment by mcieslik-mctp** [comment]
Not sure if it matters but the two variants that are lost are not even in the buffered region used for ligation.

In the schematic below each letter represents a variant, the first two variant are lost (LL) all the bufferend variants BBBs are preserved.
```
LL---BBB
     BBB----
```
So it is something that affects only seen for the first variant in the first chunk.

**Comment by srubinacci** [comment]
Thank you for reporting this problem. 
I had a look at the data, and indeed it seems a small bug in glimpse ligate / sample (only visible on chrX with samples of mixed ploidy).

Can I ask you to try the code attached and tell me if everything goes as expected?
https://drive.google.com/file/d/1GR1DuwHcbJYtGJzF3-n2B2OB394q57nl/view?usp=sharing

**Comment by mcieslik-mctp** [comment]
Thank you! I compiled the fix and can confirm that the output using the test dataset:
- has the 2 missing variants
- is otherwise identical
- 
I will continue using this patched version and report if there are any errors.

**Comment by srubinacci** [comment]
Thanks.  Will add this patch to the next version.
