### ISSUE TITLE
Best practices on chrX imputation with GLIMPSE

### ISSUE THREAD

**Issue by PengZhangJHU** [odelaneau/GLIMPSE#60]
Hi Simone and everyone,

I don't see discussions on GLIMPSE imputation on chrX. Do you have some recommendations on your current best practices for chrX imputation? For example, does GLIMPSE require imputation of males and females separately for chrX? Do you split it into three independent pieces (e.g. PAR1, nonPAR, PAR2) first and treat them as three different chromosomes for imputation? 

If anyone has some experiences on this topic, please also share, thank you!

**Comment by PengZhangJHU** [comment]
I just found there's already a tutorial here, so I'll try that first, thanks:
https://odelaneau.github.io/GLIMPSE/tutorial_chrX.html

**Comment by c5creative** [comment]
Just for the record, the above tutorial is still available at https://github.com/odelaneau/GLIMPSE/blob/glimpse1/docs/tutorial_chrX.html.
