### ISSUE TITLE
Reference Genome

### ISSUE THREAD

**Issue by batelz** [odelaneau/GLIMPSE#61]
Hi,
I'm trying to run GLIMPSE on the rest of the chromosomes for NA12878, for example chromosome 21.
I keep getting the following error when trying to create the validation dataset.
`samtools view -T ../genome_reference/chr21.fa.gz -bo GLIMPSE_validation/${ind}.chr$21.bam ${ind}.final.cram chr21`

```
error:
[W::find_file_url] Failed to open reference "http://www.ebi.ac.uk/ena/cram/md5/974dc7aec0b755b19f031418fdedf293": Input/output error
bgzf_read() on reference file: Success
[E::cram_decode_slice] Unable to fetch reference #20:5010011-5233946

[E::cram_next_slice] Failure to decode slice
[main_samview] retrieval of region "chr21" failed due to truncated file or corrupt BAM index file
```

I think the reference genome is not aligned with the CRAM file.
Though I downloaded it from the 1000 genome resources.
Can you please share a link to the directory you used as a reference genome?
and maybe add a couple of words on how you made sure it is aligned with the CRAM files?

Thank you,

Batel

**Comment by srubinacci** [comment]
Hi,

I actually think that samtools is trying to download the reference genomes indicated in the cram file, but it fails (probably it did not dowload it correctly, therefore the truncation error?).

if you look there: http://www.ebi.ac.uk/ena/cram/md5/974dc7aec0b755b19f031418fdedf293 it seems a valid fasta file.
I would maybe try to download it, index it and the use this as my fasta.
