### ISSUE TITLE
Add GLIMPSE to bioconda

### ISSUE THREAD

**Issue by nh13** [odelaneau/GLIMPSE#63]
Just a heads up that I'm working on a recipe to add GLIMPSE to bioconda: https://github.com/bioconda/bioconda-recipes/pull/29881.  Help is welcome!

**Comment by srubinacci** [comment]
Thank you for this.
I have seen few pull requests connected to it. I will have a look at them in the next few days.

**Comment by LouisLeNezet** [comment]
Hi,
I saw that glimpse-bio is available now on bioconda.
Is there a plan for Glimpse 2 ?
I can help on that if necessary as I will need this package.
Best regards,
Louis

**Comment by LouisLeNezet** [comment]
Hi,
I'm working on a Glimpse2 Bioconda recipe.
I have a small problem, `__COMMIT_ID__` and `__COMMIT_DATE__` in `ligater_parameters` are missing a define when it tried to compile.
@srubinacci or @odelaneau Do you have an idea why ?
Here is the link to my PR in [bioconda](https://github.com/bioconda/bioconda-recipes/pull/38994)
Thanks for your help !

**Comment by srubinacci** [comment]
Refer to the more recent:
https://github.com/odelaneau/GLIMPSE/issues/122
