### ISSUE TITLE
Clarification on error.spl output

### ISSUE THREAD

**Issue by gibberwocky** [odelaneau/GLIMPSE#65]
Hi

Not really an issue, but hopefully you can clarify something for me. 

Looking at the 'error.spl.txt.gz' output, there are fields for 'non_reference_discordanc_rate_percent', 'best_gt_rsquared' and 'imputed_ds_rsquared'. If I wanted to summarise a sample's overall imputation concordance, so not stratified by MAF bin, should I be looking at one of these fields? and what does 'ds' mean in 'imputed_ds_rsquared'?

Thanks in advance

D

**Comment by srubinacci** [comment]
Hi,
The file outputs sample-level concordance rates. 

> If I wanted to summarise a sample's overall imputation concordance, so not stratified by MAF bin, should I be looking at one of these fields?
yes, indeed.

> and what does 'ds' mean in 'imputed_ds_rsquared'?
It's means imputed dosage (the  expected value of the genotype probabilities), instead the of the best-guess genotype (imputed_gt_rsquared).

Hope this helps, 

Simone

**Comment by gibberwocky** [comment]
Great thanks.
