### ISSUE TITLE
Imputation on whole genome

### ISSUE THREAD

**Issue by wrosan** [odelaneau/GLIMPSE#67]
Does glimpse allow imputation on whole-genome or do we have to partition the ref sites VCF to single chromosome and run separate imputation for each chromosome?

**Comment by donthuanalyst** [comment]
I also have the question. Any answer would be greatly appreciated. Thank you

**Comment by srubinacci** [comment]
Hi, 
Imputation is always performed in small chunks of few Mb. However, if you have a reference file containing multiple chromosomes, this should not be a problem, as GLIMPSE is designed to work on indexed VCF files, therefore it would have random access in any region of the chromosome. No splitting would be required.
So, GLIMPSE would need to perform imputation on its small chunks, but the referece/target input VCF files could contain larger regions and even difference chromosomes. The specification of the region to impute is defined using the --region parameters (for glimpse_phase --input-region --output-region).
Hope that answer your questions.

**Comment by donthuanalyst** [comment]
That is good to know that we do not need to split the genome by chromosome to run GLIMPSE. In this case what should I need to provide to --region parameter which expects a chromosome name/number.

**Comment by srubinacci** [comment]
Exactly. This for GLIMPSE chunk for example.
For GLIMPSE phase, you will need to specify smaller regions (defined by GLIMPSE chunk)

**Comment by wrosan** [comment]
Thank you so much for your quick response and for making us clear on the imputation process.

**Comment by donthuanalyst** [comment]
I am working with a honey bee genome and it has about 300 scaffolds and are not assembled to chromosomes. 

Do I need to run glimpse_chunk 300 times each time for each scaffold and generate 300 chunks.txt files? Do you have any script or set of commands to efficiently run glimpse_chunk and other downstream steps efficiently without manually running 300 times?

One of the input files for glimpse_phase is a genetic map. Could you please let us know what exactly is the format for the genetic map? How many columns and what information is required for each column, etc? I will then have to figure out how to create a genetic map.

We greatly appreciate any information you can provide. Thank you so much.

**Comment by srubinacci** [comment]
You'll need to run GLIMPSE_chunk for each one of your chromosomes/scaffold/contigs. Once these chunks have been derived, you can simply concatenate these files and run imputation in parallel by reading different lines of this file (there're many ways to do this).

The genetic map is relatively straighforward. As you have probably noted from the provided maps, the files have three columns: the first one is the genetic position, the second the chromosome and the third is the distance in cM. If a map is not present for your organism, you can allow constant recombination by omitting the parameter.

**Comment by donthuanalyst** [comment]
Hello Simone,

Thank you very much for answering my questions. It was very helpful to
resolve the problems I was experiencing.

Thank you for clarifying that we need to run GLIMPSE_chunk for each one of
the scaffolds/chromosomes/contigs.

We are still unclear as to how to run multiple times for all the scaffolds
and how to concatenate the files generated for all the scaffolds.

We would appreciate it if you could provide us with the scripts/commands
that you used to concatenate all the files from different scaffolds at
different steps.

Thank you very much for your help.

Kiran

**Comment by donthuanalyst** [comment]
We are thankful to you for answering our questions.

The follow up question is about scripts or unix commands that we can use to run Glimpse multiple times for multiple scaffolds. 

Yes we are running our work on an HPC cluster run by SLURM. If you can provide SLURM scripts or commands that will be very helpful. 

The part I am trying to get help with is not included in the tutorial. In the tutorial it was mentioned how to run Glimpse for one chromosome. 

In the tutorial at step 1 we generate sites files in tsv and vcf format for each scaffold. We use those sites files to generate genotype likelihoods in step 3 for each scaffold. At step 4 (Glimpse_chunk) we again generate multiple files for multiple scaffolds.  At step 5 (Glimpse_phase) we generate multiple files for multiple scaffolds. 

We need to have a SLURM script or commands to merge files for different scaffolds into a single file for the entire genome after running step 1, step 3, step 4 and step 5. This part was not mentioned in the tutorial. Could you please help me with running different steps of the tutorial for all different scaffolds in an automated manner and generate a final single file with results from all the scaffolds.

Thank you very much for your help.

Kiran

**Comment by srubinacci** [comment]
Hi,

> The follow up question is about scripts or unix commands that we can use to run Glimpse multiple times for multiple scaffolds.

Different scaffolds/chromosomes are completely independent and therefore imputation can logically run completely independently (e.g. in parallel on a cluster). At the end of the ligation step you'll always get N files, one per chromosome/scaffold.

How you run several imputation on the whole genome is just a matter of looping over your chromosomes. 

As I understand you have many scaffolds. The easiest way to manage this situation is to concatenate all your chunk files (the result of GLIMPSE_chunk) into a single file. Let's call it chunks.txt and suppose this file has M lines (N <= M of course). Now our file has all the chunks for all the scaffolds, we will need to run M imputation jobs (using GLIMPSE_phase), and ligate the output into N files (using GLIMPSE_ligate). 

So we need to run GLIMPSE phase from these regions. The columns of the chunks.txt file help us to know the chromosome name and the ID of the chunk we are imputing.
I post you an example here of how you could run GLIMPSE_phase. There are of course many assumptions here (running times for SLURM, locations of the files, etc), and it requires the use of job arrays, hope you are familiar with them.

`#!/bin/bash

#SBATCH --array=1-1000 #######CAREFUL: here it is 1-M
#SBATCH --job-name phase
#SBATCH --partition cpu
#SBATCH --nodes 1
#SBATCH --ntasks 1
#SBATCH --cpus-per-task 1
#SBATCH --export=NONE
#SBATCH --mem 15G
#SBATCH --output=log/phase_%A_%a.out
#SBATCH --error=log/phase_%A_%a.err
#SBATCH --time=08:00:00


mkdir -p log

echo "START IMPUTATION v1.1.1-${SLURM_ARRAY_TASK_ID}";

PDIR=/work/srubinac/test

DATA2=$(cat ${PDIR}/step0_chunks/output/chunks.txt | head -n ${SLURM_ARRAY_TASK_ID} | tail -n 1) # we take the n-th line of the file
# now we get the colums
IDC=$(echo ${DATA2} | cut -d" " -f1)
CHR=$(echo ${DATA2} | cut -d" " -f2)
IRG=$(echo ${DATA2} | cut -d" " -f3)
ORG=$(echo ${DATA2} | cut -d" " -f4)
REGS=$(echo ${ORG} | cut -d":" -f 2 | cut -d"-" -f1)
REGE=$(echo ${ORG} | cut -d":" -f 2 | cut -d"-" -f2)
printf -v IDG "%02d" ${IDC}

REF=1000GP

BIN=/work/srubinac/bin/GLIMPSE-v1.1.1/phase/bin/GLIMPSE_phase
RP=/work/srubinac/data/panels/${REF}_chr${CHR}.bcf
GLS=/work/srubinac/data/gls/eur_1.0x_gls.bcf
OUD=${PDIR}/step1_phase/output/v1.1.1/chr${CHR}/glimpse_phase_${IDG}.bcf
OUL=${PDIR}/step1_phase/output/v1.1.1/chr${CHR}/log/glimpse_phase_${IDG}.log
mkdir -p ${PDIR}/step1_phase/output/v1.1.1/chr${CHR}
mkdir -p ${PDIR}/step1_phase/output/v1.1.1/chr${CHR}/log

${BIN} --input ${GLS} --input-region ${IRG} --output-region ${ORG} --output ${OUD} --reference ${RP} --thread 4 --log ${OUL}

echo "END IMPUTATION v1.1.1-${SLURM_ARRAY_TASK_ID}";`

Once imputation is finished, you can ligate your jobs in a similar way, I think you got the logic now. 
Simone.

**Comment by donthuanalyst** [comment]
Hello Simone,

Thank you so much for taking time to answer my questions. However, the
question I asked regarding the linking of the steps that need to be done on
all scaffolds was not answered.

Below I outlined all the steps in the GLIMPSE workflow listed in the
tutorial. I have indicated those that need to be run for each scaffold
namely steps 1 through 4. My question is whether in the writing of your
program you prepared a script that allows automated running of steps 1
through 4 for each scaffold. This is the script we are looking for. We will
greatly appreciate it if you could provide this to us.

Thank you very much for your help throughout this process of my learning
how to run GLIMPSE.

1. Extract variable positions in reference panel - run this for each
scaffold


2. Convert the above output sites file to TSV format and index the file
using tabix  - run for each scaffold


3. Computing GLs for a single individual at specific positions - run for
each scaffold


4. Split the scaffold into chunks - run for each scaffold


5. Run Glimpse_phase for the concatenated chunks generated from step 4 -
run for each individual line in the chunks file


6. Ligate chunks from different scaffolds

  6.a. Generate a single VCF/BCF file with imputed chunks from all the
scaffolds


7. For the VCF/BCF file generated in step 6, convert unphased genotypes
into haplotypes using GLIMPSE_sample


8. Run GLIMPSE_concordance to check imputation accuracy


Best wishes,

Kiran

**Comment by srubinacci** [comment]
Unfortunately I do not have a pipeline that covers the steps 1-3 above in an automated manner. Should be pretty easy to implement though, as it is just a matter of looping across chromosomes/scaffolds.

If it helps, I do have something for steps 4-6,8. The way I implemented it is very simple. I have four folders, step0_chunk, step1_phase, step2_ligate and step3_concordance. Each of these folders has two subfolders, name commands and output. The command folder contains a script I run, similarly to the script I posted above (for phase).

The wrapper is straightforward and can be simply:
<details>

<summary> wrapper_script.sh </summary>

```
#! /bin/bash

for CHR in 20; do # all autosomes here as {1..22} for example
	declare -a MET_PAR=("${CHR} v1.1.1 ") # running glimpse v1.1.1

	cd step0_chunk/commands # location of the chunk folder
	jid0=$(sbatch -W step0.chunk.sh --array=1-1 "${MET_PAR[@]}" | sed 's/Submitted batch job //') #note the -W, we wait until it ends before moving on.

	NCK=$(cat ../output/chunks_chr${CHR}.txt | wc -l) # we count the chunks for this chromosome, so we can call a job array for our next sbatch command
	cd ../../step1_phase/commands # location of the phase folder
	jid1=$(sbatch --dependency=afterok:${jid0} --array=1-${NCK} step0.phase.job.chunks.sh "${MET_PAR[@]}" | sed 's/Submitted batch job //')
	cd ../../step2_ligate/commands # location of the ligation folder
        jid2=$(sbatch --dependency=afterok:${jid1} --array=1-1 step0_ligate.sh "${MET_PAR[@]}" | sed 's/Submitted batch job //')
        cd ../../step3_concordance/commands # location of the concordance folder
	jid3=$(sbatch --dependency=afterok:${jid2} --array=1-1 step0_concordance.sh "${MET_PAR[@]}" | sed 's/Submitted batch job //')
done
```
</details>

Now, as you can see step0.chunks.sh produces a file called step0_chunk/outout/chunks_chr${CHR}.txt that contains the chunks for that specific chromosome. By using job arrays I run step0.phase.job.chunks.sh, that reads a single line of the previous file and runs imputation. The exact number of jobs for the array is given by the variable NCK. 
The pipeline uses job dependencies, so it runs things in the right order.
Each of these scripts knows what chromosome and GLIMPSE version to use, thanks to the variable called MET_PAR. This is actually an array (as it would allow more complex things) and it is simply read like follows for each of the sbatch scripts:

<details>

<summary> script_read_var.sh </summary>

```
#! /bin/bash

arr=("$@")
for ARG in "${arr[@]}"; do
	CHR=$(echo "${ARG} " | cut -f1 -d" ")
	MET=$(echo "${ARG} " | cut -f2 -d" ")

 	#do something with these variables, e.g. we now can point to the right reference panel/map as we know the chromosome, etc.

done
```
</details>

I believe that writing a wrapper for steps 1-3 similarly to the scripts above will take you now just few minutes. If there are too many contigs in your file, my suggestion is to put them in a file (one scaffold per line) and read them one by one (bcftools index --stats will produce exactly this list).

Best wishes,

Simone
