### ISSUE TITLE
ERROR: Failed to open file

### ISSUE THREAD

**Issue by donthuanalyst** [odelaneau/GLIMPSE#68]
Hello,

Even though the input file do exist glimpse is giving the "Failed to open the file" error.

Could you please help me to fix this error.

Thank you.

<pre>
GLIMPSE_chunk --input ../../data/refPanelData/Harpur_sites.vcf.gz  --window-size 2000000 --buffer-size 200000 --region NC_037638.1 --output chunks.NC_037638.1.txt

[GLIMPSE] Split chromosomes into chunks
  * Author        : Simone RUBINACCI & Olivier DELANEAU, University of Lausanne
  * Contact       : simone.rubinacci@unil.ch & olivier.delaneau@unil.ch
  * Version       : 1.1.1
  * Run date      : 10/08/2021 - 08:07:35

Files:
  * Input VCF      : [../../data/refPanelData/Harpur_sites.vcf.gz]
  * Chromosome     : [NC_037638.1]
  * Output file    : [chunks.NC_037638.1.txt]

Parameters:
  * Seed             : 15052011
  * #Threads   : 1
  * Min. Window size : 2000000bp / 1000 variants
  * Min. Buffer size : 200000bp / 100 variants

Reading input files
  * Main      : [../../data/refPanelData/Harpur_sites.vcf.gz]

ERROR: Failed to open file: ../../data/refPanelData/Harpur_sites.vcf.gz
</pre>

**Comment by srubinacci** [comment]
Hi,
Are you sure the region/chromosome in your Harpur_sites.vcf.gz is exactly the one you defined with the --region parameter?
GLIMPSE will attempt to open the file using the index (tbi or csi format) and if that does not match, it can create problems.

If everything you think is ok from your side, I can maybe ask to share (even partially) the Harpur_sites.vcf.gz file (only the sites), and I can quickly have a look..
