### ISSUE TITLE
Step 7 and 8 in the tutorial

### ISSUE THREAD

**Issue by donthuanalyst** [odelaneau/GLIMPSE#70]
Hello Simone,

https://odelaneau.github.io/GLIMPSE/tutorial_b38.html

I would appreciate it if you could assist me in understanding the instructions for step 7 and 8 of glimpse tutorial.

It is not clear to me what the goal is for step 7. Is it convert genotypes to haplotypes?

Step 8:

You have mentioned concordance.lst file as input. Can you please provide an example file or let me know how this file should be constructed?

Thank you very much

**Comment by srubinacci** [comment]
Hi,

Yes, the output of GLIMPSE (after the ligation process) are unphased genotypes. The sampling step, provides haplotype-level data. 

The concordance.lst is a simple file containing four columns (space separated): chrID (or scaffold/contig ID in your case), a VCF file containing allele frequency of your population for each variant (in the FORMAT/AF field), the validation file (in our case computed with bcftools from high-coverage data, having FORMAT/DP, FORMAT/PL defined) and finally the imputed file (output of the ligation step).

An example is provded in the test folder.
Best wishes,

Simone
