### ISSUE TITLE
"ERROR: States for individual 0 are zero. Error during selection" and other issues

### ISSUE THREAD

**Issue by nh13** [odelaneau/GLIMPSE#72]
I am testing GLIMPSE on some small datasets to understand the different tools and workflows and I am getting some unexpected behavior. The input VCF is a single sample with variant calls at two (2) sites with het calls at both sites. The reference panel is three samples with variant calls at eleven (11) sites, including those in the input VCF. The three samples have hom-ref, het, and hom-alt genotypes respectively across all the variants. Thus, I would expect that after imputation and phasing, the input sample to have het calls at all sites.

Likely it is my understanding of the input format(s) (e.g. does the FORMAT/PS need to be set in the reference panel?) or the tool.  Thank-you for your help in advance.

#### Input VCFs

<details>

<summary>Input VCF</summary>

```
##fileformat=VCFv4.2
##FILTER=<ID=PASS,Description="All filters passed">
##contig=<ID=chr22>
##INFO=<ID=RAF,Number=A,Type=Float,Description="ALT allele frequency in the reference panel">
##INFO=<ID=AF,Number=A,Type=Float,Description="ALT allele frequency computed from DS/GP field across target samples">
##INFO=<ID=INFO,Number=A,Type=Float,Description="IMPUTE info quality score for diploid samples">
##INFO=<ID=BUF,Number=A,Type=Integer,Description="Is it a variant site falling within buffer regions? (0=no/1=yes)">
##FORMAT=<ID=AB,Number=1,Type=Float,Description="Allele balance for each het genotype">
##FORMAT=<ID=AD,Number=.,Type=Integer,Description="Allelic depths for the ref and alt alleles in the order listed">
##FORMAT=<ID=DP,Number=1,Type=Integer,Description="Approximate read depth (reads with MQ=255 or with bad mates are filtered)">
##FORMAT=<ID=GQ,Number=1,Type=Integer,Description="Genotype Quality">
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
##FORMAT=<ID=PL,Number=G,Type=Integer,Description="Normalized, Phred-scaled likelihoods for genotypes as defined in the VCF specification">
##NMAIN=10
##FPLOIDY=2
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	HG00556
chr22	10519276	22:10519276:G:C	G	C	.	PASS	.	GT:ab:AD:DP:GQ:PL	0/1:0.73:58,22:80:99:469,0,1882
chr22	10524872	22:10524872:G:C	G	C	.	PASS	.	GT:ab:AD:DP:GQ:PL	0/1:0.73:58,22:80:99:469,0,1882
```

</details>

<details>

<summary>Reference VCF</summary>

```
##fileformat=VCFv4.1
##FILTER=<ID=PASS,Description="All filters passed">
##FORMAT=<ID=GT,Number=1,Type=String,Description="Phased Genotype">
##contig=<ID=chr22>
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	HG02477	HG02010	HG02481
chr22	10519276	22:10519276:G:C	G	C	.	PASS	.	GT	1|1	0|1	0|0	
chr22	10519389	22:10519389:T:C	T	C	.	PASS	.	GT	1|1	0|1	0|0
chr22	10519413	22:10519413:C:G	C	G	.	PASS	.	GT	1|1	0|1	0|0	
chr22	10519515	22:10519515:T:C	T	C	.	PASS	.	GT	1|1	0|1	0|0
chr22	10524872	22:10524872:G:C	G	C	.	PASS	.	GT	1|1	0|1	0|0
chr22	10524880	22:10524880:C:T	C	T	.	PASS	.	GT	1|1	0|1	0|0
chr22	10525545	22:10525545:G:A	G	A	.	PASS	.	GT	1|1	0|1	0|0
chr22	10525647	22:10525647:G:A	G	A	.	PASS	.	GT	1|1	0|1	0|0
chr22	10526163	22:10526163:A:T	A	T	.	PASS	.	GT	1|1	0|1	0|0
chr22	10526174	22:10526174:T:A	T	A	.	PASS	.	GT	1|1	0|1	0|0
chr22	10526217	22:10526217:A:G	A	G	.	PASS	.	GT	1|1	0|1	0|0
```

</details>

#### Attempt 1: ERROR: States for individual 0 are zero. Error during selection.

I first ran the most simple command line to impute the variants for the single sample.  
 
```console
GLIMPSE_phase \
    --input testing.vcf.gz \
    --reference training.vcf.gz \
    --input-region chr22:1-411566216 \
    --output-region chr22:1-411566216 \
    --output phased.vcf
```

The error was `ERROR: States for individual 0 are zero. Error during selection.` (the full log is specified below). This error is not intuitive, given my expectation that all sites from the reference panel should be phased, and doesn't tell me how to fix the error.

I then tried adding  the `--impute-reference-only-variants` option, which phases correctly all the input sample's variants.  The manually strongly urges the user not to use this option, so I'd rather not, but at least I don't get an error message. Why?

<details>

<summary> log </summary>

```
[GLIMPSE] Phase and impute low coverage sequencing data
  * Author        : Simone RUBINACCI & Olivier DELANEAU, University of Lausanne
  * Contact       : simone.rubinacci@unil.ch & olivier.delaneau@unil.ch
  * Version       : 1.1.1
  * Run date      : 13/08/2021 - 10:55:11

Files:
  * Input VCF     : [testing.vcf.gz]
  * Reference VCF : [training.vcf.gz]
  * Output VCF    : [phased.vcf]
  * Input region  : [chr22:1-411566216]
  * Output region : [chr22:1-411566216]

Parameters:
  * Seed       : 15052011
  * Input      : FORMAT/PL field for genotype likelihoods
  * #Threads   : 1
  * #Burnin    : 10
  * #Main      : 10
  * PBWT depth : 2
  * PBWT modulo: 8
  * HMM     : Constant recombination rate of 1cM per Mb
  * Ploidy     : All samples are diploids in this region
  * Init K     : 1000

Initialization:

Parsing specified genomic regions
  * Input region  [chr22:1-411566216]
  * Output region  [chr22:1-411566216]
  * #samples = 1 [0 haploids/ 1 diploid]
  * VCF/BCF scanning [Reg=chr22:1-411566216 / L=2 (Li= 2 (100%) - Lm= 0 (0%))] (0.00s)
[W::vcf_parse_format] FORMAT 'ab' at chr22:10519276 is not defined in the header, assuming Type=String
  * VCF/BCF scanning [Nm=1 (Nmh=0 - Nmd=1) / Nr=3 (Nrh=0 - Nrd=3)]
  * VCF/BCF parsing done (0.00s)
  * cM constant [1cM=1Mb] (0.00s)
  * Region spans 5597 bp and 0.01 cM

Initializing iteration
  * HMM imputation [#states=6.0 / %poly=100.0%] (0.00s)

Burn-in iteration [1/10]
  * HAP update (0.00s)
  * PBWT building & selection (0.00s)
  

ERROR: States for individual 0 are zero. Error during selection. 
```
</details> 

#### Attempt 2: Unexpected imputed homozygous reference variants using only a single variant

Next, if I remove the `chr22:10524872` site from the input VCF (not the reference panel), and use `--impute-reference-only-variants`, since I get the previously described error, the input variants from `chr22:10524872` onwards are imputed as hom-ref.  Since all the variants in the reference panel are phased in one block, I would have expected the input sample to have been imputed as het-ref.  Why?

#### Attempt 3: Unexpected imputed homozygous reference variants using a genetic map

If I use `--impute-reference-only-variants`, since I get the previously described error, and we specify the genetic map for chr22 ([hg38](https://github.com/odelaneau/GLIMPSE/tree/master/maps/genetic_maps.b38)) then only `chr22:10519276` and `chr22:10524872` are het as expected, with the rest unexpectedly hom-ref.  This is really confusing, since without the genetic map option I get all the variants imputed correctly.  What is it about providing the genetic map that has this issue?

**Comment by srubinacci** [comment]
Hi,

I understand that your idea is to look in details a very small example and monitor what is happening in details. However, the number of variants is definitively too little to have any meaningful results and you will end up running the selection on a single variant. This causes the "Error during selection." problem.

You might need to increase the number of variants to _at least_ few hundreds at least and increase your reference panel to at least 50 samples. In general, I would just do these tests on a 1Mb region and on a large panel (e.g. full 1000GP).

**Comment by nh13** [comment]
@srubinacci thank-you for the response!  

I would love for the software to be able to impute and phase the contrived toy problem I suggested as it is completely doable by a human eye and unambiguous in what the result should be.

Nonetheless, I agree it is completely reasonable for us to test using both a larger subset of the reference samples (e.g. full 1KG) as well as a larger region.

**Comment by srubinacci** [comment]
Hi,
Yes, I totally agree it would be useful. However, the results won't have much sense, as the HMM still requires to run on more than three variants. Maybe you can just take like 50 reference samples and few hundred variants if you want to visually inspect what is the behavior of the software.

Best wishes,

Simone

**Comment by Matteo-Paini** [comment]
Hi, 

I'm using GLIMPSE2 to impute variants from a lcs-wgs of a Horse sample. To be sure, i followed the instructions reported on the [tutorial](https://odelaneau.github.io/GLIMPSE/docs/tutorials/getting_started/#5-impute-and-phase-a-whole-chromosome). Everything works until the Imputation step, at which i have the same problem "ERROR: States for individual 0 are zero. Error during selection." 

[The reference panel used is the whole chromosome 1 with 53 samples](http://gong_lab.hzau.edu.cn/Animal_ImputeDB/#!/download_horse). Maybe the fact that is not a human reference panel could be a problem for the software (the name of the chromosome 1 in the vcf is NC_009144.3)?

Thank you in advance,
Matteo

**Comment by srubinacci** [comment]
Hi, I think you are getting the same error as here: https://github.com/odelaneau/GLIMPSE/issues/142 
The error has been fixed in the latest commit. Are you able to compile the latest branch?
I am going to produce a new release as soon as possible.

**Comment by Matteo-Paini** [comment]
> Hi, I think you are getting the same error as here: #142 The error has been fixed in the latest commit. Are you able to compile the latest branch? I am going to produce a new release as soon as possible.
> 
> A recent docker image is available here: https://drive.switch.ch/index.php/s/hZN8NtTtqSGlrSF

HI @srubinacci, 
thank you for your fast response. The docker image worked perfectly, thank you so much!
