### ISSUE TITLE
Glimpse is comparing two different chromosome coordinates and throwing error

### ISSUE THREAD

**Issue by donthuanalyst** [odelaneau/GLIMPSE#74]
Hello Simone,

I am getting the following error with Glimpse.

ERROR: Wrong order in your genetic map file 27595808bp / 505.70000cM > 431046bp / 0.00000cM

As you can see in the following map file glimpse is comparing two different chromosome coordinates and throwing error.  Could you please fix this issue with glimpse.

Thank you so much for your help.
Kiran

**Map file**
<pre>
27320919        NC_037638.1     498
27335789        NC_037638.1     498
27529200        NC_037638.1     505.7
27584516        NC_037638.1     505.7
27595808        NC_037638.1     505.7
431046  NC_037639.1     0
495790  NC_037639.1     2.6
720310  NC_037639.1     7.7
787365  NC_037639.1     7.7
869964  NC_037639.1     8.8
2028915 NC_037639.1     8.8
2514758 NC_037639.1     8.8
2610289 NC_037639.1     8.8
2615661 NC_037639.1     8.8
</pre>

**Command used to run glimpse**
<pre>
[rdonthu@node044 glimpse]$ while IFS="" read -r LINE || [ -n "$LINE" ]; do printf -v ID "%02d" $(echo $LINE | cut -d" " -f1); IRG=$(echo $LINE | cut -d" " -f3); ORG=$(echo $LINE | cut -d" " -f4); OUT=SRR5580846.1x.${ID}.bcf; GLIMPSE_phase --input ${VCF} --reference ${REF} --map ${MAP} --input-region ${IRG} --output-region ${ORG} --output ${OUT}; bcftools index -f ${OUT}; done < test1.txt

[GLIMPSE] Phase and impute low coverage sequencing data
  * Author        : Simone RUBINACCI & Olivier DELANEAU, University of Lausanne
  * Contact       : simone.rubinacci@unil.ch & olivier.delaneau@unil.ch
  * Version       : 1.1.1
  * Run date      : 17/08/2021 - 02:57:22

Files:
  * Input VCF     : [../bcftools_GenLhds/SRR5580846.GLs.vcf.gz]
  * Reference VCF : [../../data/refPanelData/Harpur_joint.filtered.filByDPGQ.filBymafMono.QCFailRem.16ChrsOnly.phasedimputed.vcf.gz]
  * Genetic Map   : [../../data/HB_genetic_map/gen_map_correctedCumcM.txt]
  * Output VCF    : [SRR5580846.1x.00.bcf]
  * Input region  : [NC_037638.1:4947-3683443]
  * Output region : [NC_037638.1:4947-3483392]

Parameters:
  * Seed       : 15052011
  * Input      : FORMAT/PL field for genotype likelihoods
  * #Threads   : 1
  * #Burnin    : 10
  * #Main      : 10
  * PBWT depth : 2
  * PBWT modulo: 8
  * HMM        : Recombination rates given by genetic map
  * Ploidy     : All samples are diploids in this region
  * Init K     : 1000

Initialization:

Parsing specified genomic regions
  * Input region  [NC_037638.1:4947-3683443]
  * Output region  [NC_037638.1:4947-3483392]
  * #samples = 1 [0 haploids/ 1 diploid]
  * VCF/BCF scanning [Reg=NC_037638.1:4947-3683443 / L=164308 (Li= 164308 (100%) - Lm= 0 (0%))] (0.94s)
  * VCF/BCF scanning [Nm=1 (Nmh=0 - Nmd=1) / Nr=40 (Nrh=0 - Nrd=40)]
  * VCF/BCF parsing done (2.25s)

ERROR: Wrong order in your genetic map file 27595808bp / 505.70000cM > 431046bp / 0.00000cM
[E::hts_open] fail to open file 'SRR5580846.1x.00.bcf'
Segmentation fault
</pre>

**Comment by srubinacci** [comment]
Hi, 
Yes, the error is exacly that. I think that the best way to fix this problem is actually for you to split your map file into different contigs/scaffolds, similarly to the files provided [here](https://github.com/odelaneau/GLIMPSE/tree/master/maps/genetic_maps.b38).
In that way there's no need to change the source code. Also, having separate map files for different chromosomes is a standard for imputation, as it is usually run in parallel.
Best wishes,

Simone

**Comment by donthuanalyst** [comment]
Hello Simone,

Thank you for your quick response.

Do you have a wrapper script to run these steps in a automated manner for all the scaffolds?

Kiran

**Comment by srubinacci** [comment]
I replied in the other thread, so I close this one.
