### ISSUE TITLE
constant map parameters

### ISSUE THREAD

**Issue by wrosan** [odelaneau/GLIMPSE#75]
I noticed that the constant recombination rate is set to 1Mb = 1cM. Is there a way to change the parameters of constant recombination rate, without using a genetic map.

**Comment by srubinacci** [comment]
Unfortunately not, it would be an easy edit, but we just set it it 1Mb = 1cM for now.
However, it is pretty straightforward to create your own map, as you will just need two lines in the file, I think this would be the easiest way to proceed.
