### ISSUE TITLE
Allele frequency file for concordance step

### ISSUE THREAD

**Issue by donthuanalyst** [odelaneau/GLIMPSE#76]
Hello Simone,

Could you please let me know what program you have used to generate the following allele frequency file. 
https://github.com/odelaneau/GLIMPSE/blob/master/tutorial/GLIMPSE_validation/gnomad.genomes.r3.0.sites.chr22.isec.bcf

I tried to calculate allele frequencies using vcftools --freq The output format from the VCFtools is different from the file above.

**Allele frequencies calculated using VCFtools**
<pre>
NC_037638.1     4517    2       140     A:0.9   G:0.1
NC_037638.1     4524    2       140     G:0.9   A:0.1
NC_037638.1     4560    2       140     G:0.928571      A:0.0714286
NC_037638.1     4587    2       140     A:0.992857      G:0.00714286
NC_037638.1     4660    2       140     TA:1    T:0
NC_037638.1     4663    2       140     TA:1    T:0
NC_037638.1     4696    2       140     G:0.992857      A:0.00714286
NC_037638.1     4700    2       140     A:0.992857      G:0.00714286
NC_037638.1     4817    2       140     A:0.985714      C:0.0142857
NC_037638.1     4818    2       140     T:0.985714      C:0.0142857
NC_037638.1     4823    2       140     A:0.985714      T:0.0142857
NC_037638.1     5037    2       140     G:0.921429      A:0.0785714
NC_037638.1     5041    2       140     A:0.992857      C:0.00714286
NC_037638.1     5087    2       140     GA:0.978571     G:0.0214286
NC_037638.1     5173    2       140     A:0.0142857     G:0.985714
NC_037638.1     5211    2       140     A:0.985714      ACCTTTCTT:0.0142857
NC_037638.1     5212    2       140     A:0.985714      T:0.0142857
NC_037638.1     5292    2       140     ATTTTTTTCCTCTT:0.935714 A:0.0642857
</pre>

**Comment by srubinacci** [comment]
Hi,
The file provided with the tutorial has been generated by GNOMAD from high-coverage data of ~80k people for different human populations. 
One way compute allele frequencies in the AF tag from the GT field would be to use [bcftools plugins](http://samtools.github.io/bcftools/bcftools.html#plugin):

```
# Calculate AF with bcftools +fill-tags plugin

bcftools +fill-tags \
        1000GP_filtered_chr1.vcf.gz \
        -Oz -o 1000GP_AF_chr1.vcf.gz -- -t AF
```

Best wishes, 
Simone

**Comment by donthuanalyst** [comment]
Hello Simone,

Thank you for providing information on how to generate allele frequency file.

Best wishes,
Kiran
