### ISSUE TITLE
BCFtools to compute genotype likelihoods

### ISSUE THREAD

**Issue by wentaohan** [odelaneau/GLIMPSE#78]
Hi Simone, I have a question about using bcftools to compute genotype likelihoods. 

bcftools mpileup -f ../reference/chr1.fa.gz -I -E -a 'FORMAT/DP' -T ../4_panel_sites_new/chr1.haps.sites.tsv.gz -r chr1 1-14_.sort.bam-new.markdup.bam -Ou | bcftools call -Aim -C alleles -T ../4_panel_sites_new/chr1.haps.sites.tsv.gz -Oz -o 1-14_chr1.vcf.gz

ERROR:
“The reference alleles are not compatible at chr1:2268 .. C vs T”

**Comment by srubinacci** [comment]
Hi,

I think when using call, the targets file needs to be a tsv like the one detailed at then end of this section:
http://samtools.github.io/bcftools/bcftools.html#common_options
This tsv also needs to be bgzipped/tabixed.

However, when using mpileup (first command), the file should be a vcf.gz (or a bed) file. Would that sould the problem?

**Comment by wentaohan** [comment]
Hi Simone, I am sorry for my mistake, but I didn’t solve the problem and got the same error.  

Here are few lines from my vcf.gz and tsv.gz files:

vcd.gz
##fileformat=VCFv4.1
##FILTER=<ID=PASS,Description="All filters passed">
##fileDate=31072021_13h35m20s
##source=SHAPEIT2.v904
##log_file=shapeit_31072021_13h35m20s_0ca2f628-b6a8-4c90-a774-ce5c446dcbd3.log
##contig=<ID=chr1>
##bcftools_viewVersion=1.8+htslib-1.8
##bcftools_viewCommand=view -m 2 -M 2 -v snps -Ob -o chr1.haps.bcf chr1.haps.vcf.gz; Date=Tue Aug 31 10:08:42 2021
##bcftools_viewCommand=view -G -m 2 -M 2 -v snps -Oz -o ../4_panel_sites_new/chr1.haps.sites.vcf.gz chr1.haps.bcf; Date=Tue Aug 31 10:17:03 2021
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO
chr1	1295	.	T	C	.	PASS	.
chr1	1335	.	C	T	.	PASS	.
chr1	1364	.	G	A	.	PASS	.
chr1	1369	.	A	C	.	PASS	.
chr1	1370	.	A	C	.	PASS	.
chr1	1395	.	T	A	.	PASS	.
chr1	1406	.	T	C	.	PASS	.
chr1	1421	.	A	G	.	PASS	.
chr1	2268	.	C	T	.	PASS	.
chr1	2321	.	C	T	.	PASS	.

tsv.gz
chr1	1295	T,C
chr1	1335	C,T
chr1	1364	G,A
chr1	1369	A,C
chr1	1370	A,C
chr1	1395	T,A
chr1	1406	T,C
chr1	1421	A,G
chr1	2268	C,T
chr1	2321	C,T
chr1	2323	A,T
chr1	2382	G,T
chr1	2466	A,G
chr1	2472	A,G
chr1	2521	C,T
chr1	2541	A,G
chr1	2548	A,T

Thank you so much for your help!
Best wishes,
Wentao Han

**Comment by wentaohan** [comment]
Hi Simone, I am sorry for my mistake, but I didn’t solve the problem and got the same error.

Here are few lines from my vcf.gz and tsv.gz files:

vcf.gz
##fileformat=VCFv4.1
##FILTER=<ID=PASS,Description="All filters passed">
##fileDate=31072021_13h35m20s
##source=SHAPEIT2.v904
##log_file=shapeit_31072021_13h35m20s_0ca2f628-b6a8-4c90-a774-ce5c446dcbd3.log
##contig=<ID=chr1>
##bcftools_viewVersion=1.8+htslib-1.8
##bcftools_viewCommand=view -m 2 -M 2 -v snps -Ob -o chr1.haps.bcf chr1.haps.vcf.gz; Date=Tue Aug 31 10:08:42 2021
##bcftools_viewCommand=view -G -m 2 -M 2 -v snps -Oz -o ../4_panel_sites_new/chr1.haps.sites.vcf.gz chr1.haps.bcf; Date=Tue Aug 31 10:17:03 2021
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO
chr1	1295	.	T	C	.	PASS	.
chr1	1335	.	C	T	.	PASS	.
chr1	1364	.	G	A	.	PASS	.
chr1	1369	.	A	C	.	PASS	.
chr1	1370	.	A	C	.	PASS	.
chr1	1395	.	T	A	.	PASS	.
chr1	1406	.	T	C	.	PASS	.
chr1	1421	.	A	G	.	PASS	.
chr1	2268	.	C	T	.	PASS	.
chr1	2321	.	C	T	.	PASS	.

tsv.gz
chr1	1295	T,C
chr1	1335	C,T
chr1	1364	G,A
chr1	1369	A,C
chr1	1370	A,C
chr1	1395	T,A
chr1	1406	T,C
chr1	1421	A,G
chr1	2268	C,T
chr1	2321	C,T
chr1	2323	A,T
chr1	2382	G,T
chr1	2466	A,G
chr1	2472	A,G
chr1	2521	C,T
chr1	2541	A,G
chr1	2548	A,T

Thank you so much for your help!
Best wishes,
Wentao Han

**Comment by srubinacci** [comment]
Hi, 
Your files seem correct from what you report. I am not sure what it could be the error, you might need to ask samtools/bcftools about this problem.
I found a similar problem reported [here](https://github.com/samtools/bcftools/issues/239) and it suggested that the tsv was not compressed and indexed. I assume yours is, so I am not sure this helps.
If you struggle with this (maybe after you asked the bcftools team), feel free to send me and email with your bam and tsv.gz/vcf.gz (+indeces) files, I can give a quick look at the data.

**Comment by wentaohan** [comment]
Hi Simone,

Hope everything is well in your side. Sorry to disturb you again. You may wish to view it by using the following link: https://we.tl/t-95QDdWoxPD

Thank you very much in advance for your help!

Yours sincerely!

Wentao Han













--

Wentao Han

College of Marine Life Science Ocean University of China

5 Yushan Road, Qingdao, 266003, P.R. China

Tel: 156 8911 5465

Email: ***@***.***; ***@***.***

ResearchGate




At 2021-09-01 21:42:11, "Simone Rubinacci" ***@***.***> wrote:

Hi,
Your files seem correct from what you report. I am not sure what it could be the error, you might need to ask samtools/bcftools about this problem.
I found a similar problem reported here and it suggested that the tsv was not compressed and indexed. I assume yours is, so I am not sure this helps.
If you struggle with this (maybe after you asked the bcftools team), feel free to send me and email with your bam and tsv.gz/vcf.gz (+indeces) files, I can give a quick look at the data.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by srubinacci** [comment]
Hi,
There is some problem with your bam file in the data you sent me. 
```samtools quickcheck 1-14_.sort.bam-new.markdup.bam
1-14_.sort.bam-new.markdup.bam was missing EOF block when one should be present.
```
I bet it is a problem during the upload.

**Comment by wentaohan** [comment]
Hi Simone,

I checked the BAM file carefully and I got the same error again. I was wondering if you could please check the pipelines for obtaining BAM files?

Thank you very much in advance for your help!

Yours sincerely!

Wentao Han




for i in `ls *forward_paired.fq.gz`;do bwa mem ../reference/index/genome.fa $i ${i%%forward_paired.fq.gz}reverse_paired.fq.gz -t 10 >./${i%%.forward_paired.fq.gz}.sam;done
for i in `ls *sam`;do samtools sort  -n -@ 10 $i > ${i%%.sam}.sort.bam;done
for i in `ls *sort.bam`;do samtools fixmate -m $i ${i%%.bam}.fixmate.bam;done
for i in `ls *fixmate.bam`;do samtools sort -@ 10 $i -o${i%%.fixmate.bam}.positionsort.bam;done
for i in `ls *positionsort.bam`;do samtools markdup -r $i ${i%%.positionsort.bam}.markdup.bam;done
for i in `ls *markdup.bam`;do samtools index -@ 10 $i;done















--

Wentao Han

Yellow Sea Fisheries Research Institute, Chinese Academy of Fishery Sciences,

Qingdao, 266071, China.

Tel: 156 8911 5465

E-mails:  ***@***.***; ***@***.***




At 2021-09-02 00:18:03, "Simone Rubinacci" ***@***.***> wrote:

Hi,
There is some problem with your bam file in the data you sent me.

1-14_.sort.bam-new.markdup.bam was missing EOF block when one should be present.


I bet it is a problem during the upload.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by srubinacci** [comment]
Unfortunately I do not have the time to check the steps you run to generate the BAM file. I think you should contact bwa mem/samtools authors instead.

I just know that running samtools quickcheck did not work in the version you uploaded.
