### ISSUE TITLE
Scaffold/chr name is same for all SNPs after ligate step

### ISSUE THREAD

**Issue by donthuanalyst** [odelaneau/GLIMPSE#79]
Hello Simone

I tried running GLIMPSE_ligate in the following way. Even though there were other scaffolds listed in the list_files_imputed.txt, the output file generated does not contain other scaffold Ids. Even though the SNPs from other scaffolds are listed the scaffold name is shown as the first scaffold (NC_037638.1) only for all the SNPs.

It looks like there is bug in the GLIMPSE_ligate module. Could you please check.

Thank you,
Kiran

**GLIMPSE_ligate step ran using the following command**
<pre>
LST=list_files_imputed.txt
ls *imputed*bcf >${LST}
OUT=All_scaffs.imputed.merged.bcf
GLIMPSE_ligate --input ${LST} --output ${OUT}
</pre>

**Few lines from list_files_imputed.txt**
<pre>
$ more list_files_imputed.txt
NC_037638.1.1x.imputed.0.bcf
NC_037638.1.1x.imputed.1.bcf
NC_037638.1.1x.imputed.2.bcf
NC_037638.1.1x.imputed.3.bcf
NC_037638.1.1x.imputed.4.bcf
NC_037638.1.1x.imputed.5.bcf
NC_037638.1.1x.imputed.6.bcf
NC_037638.1.1x.imputed.7.bcf
NC_037639.1.1x.imputed.0.bcf
NC_037639.1.1x.imputed.1.bcf
NC_037639.1.1x.imputed.2.bcf
NC_037639.1.1x.imputed.3.bcf
NC_037640.1.1x.imputed.0.bcf
NC_037640.1.1x.imputed.1.bcf
NC_037640.1.1x.imputed.2.bcf
NC_037640.1.1x.imputed.3.bcf
NC_037641.1.1x.imputed.0.bcf
NC_037641.1.1x.imputed.1.bcf
NC_037641.1.1x.imputed.2.bcf
NC_037641.1.1x.imputed.3.bcf
NC_037642.1.1x.imputed.0.bcf
NC_037642.1.1x.imputed.1.bcf
NC_037642.1.1x.imputed.2.bcf
NC_037642.1.1x.imputed.3.bcf
NC_037643.1.1x.imputed.0.bcf
NC_037643.1.1x.imputed.1.bcf
NC_037643.1.1x.imputed.2.bcf
NC_037643.1.1x.imputed.3.bcf
NC_037643.1.1x.imputed.4.bcf
</pre>

**Comment by srubinacci** [comment]
Hi,
I am not sure I understand correctly, but from what I get from your message it does not seem to be an error to me. GLIMPSE ligate is useful (and meant) only to ligate chunks on the same chromsome/contig. To ligate chunks across different chromosomes/contigs you can simply use bcftools concat.
