### ISSUE TITLE
impute on multiple samples

### ISSUE THREAD

**Issue by chvbs2000** [odelaneau/GLIMPSE#82]
We are trying to run glimpse on multiple samples simultaneously, and we are not sure how to implement imputation on multiple sample, we have one vcf.gz have containing multiple samples (multiple columns). it would be helpful if you could provide more information on the following questions:
 
1. how does **list.txt** generated in step 3.3?
2. how could we impute and ligate this multiple-sampled vcf in GLIMPSE_phase and GLIMPSE_ligate? Thanks.

**Comment by srubinacci** [comment]
Hi,
the list.txt file is just a file having multiple vcf/bcf filenames containing genotype likelihoods. So you can create a single genotype likelihood file per bam file and merge them later.

An alternative and more efficient approach would be to run the calling step directly using bcftools mpilup with the --bam-list option (as described here: https://samtools.github.io/bcftools/bcftools.html#mpileup
in that case --bam-list is a list of bam files (one sample per bam file)

You will run glimpse normally using this multi-sample genotype likelihood vcf/bcf file as input. GLIMPSE will automatically detect multiple samples, and that will be transparent to you during the imputation/ligation step.

Hope this help,

Simone
