### ISSUE TITLE
Imputation with reference panels from multiple resources

### ISSUE THREAD

**Issue by PengZhangJHU** [odelaneau/GLIMPSE#83]
Hi Simone,

We are interested in imputing some variants that are not in the current 1KG reference panel, so we want to check with you the possibility of adding some external samples (VCF) to the 1KG reference. 
1) Is it possible for Glimpse to point to two reference panels for the imputation (GLIMPSE_IMPUTE) step?
 if not, 2) Do you think it's okey to use one from merging the the two VCF files without joint calling them? 
Any suggestions? Thanks!

**Comment by srubinacci** [comment]
Hi 
Sorry for the delay. 
No, unfortunately we cannot point to two reference panels. However, the concept of metaimputation, that was recently introduced by a paper in AJHG is something we can work on in the next release.
