### ISSUE TITLE
Concordance check of male chrX with GLIMPSE_concordance

### ISSUE THREAD

**Issue by PengZhangJHU** [odelaneau/GLIMPSE#84]
Hi Simone,

1) I noticed that GLIMPSE imputed genotypes are in diploid format for non-PAR region in males, but my validation dataset has it in haploid format. Is there a way to address this?
2) Assume both are in haploid format, do you need to specify the FPLOIDY in the VCF header for the GLIMPSE_concordance to work? Can you share a header with us that worked for you? 

Thank you!

**Comment by srubinacci** [comment]
Non-par region of the genome is has ploidy=1 for males and ploidy=2 for females.
Have you followed chrX tutorial?
https://odelaneau.github.io/GLIMPSE/tutorial_chrX.html
