### ISSUE TITLE
odd makefile - support in easybuild

### ISSUE THREAD

**Issue by cmeesters** [odelaneau/GLIMPSE#85]
Hi,

nice to see imputation reaching beyond GWAS. 

Whilst installing GLIMPSE using the easybuild build framework for HPC systems, I noticed that all makefiles show hard coded reference to their dependencies. That is most unusual, because such "standard paths" are by no means standard: They may differ from system to system. Also, if the library can be recognized by the linker, by means of LD_LIBRARY_PATH, simple dynamic linking will do. 

I have attached the patch, I employed for reference. (It bears the suffix 'txt', because oddly github does not the suffix '.patch', even if it is text, only.)

There are a couple of PRs with regard to the makefile (and bioconda) already. I would like to support your software for easybuild, perhaps a version update might consider such changes? That would be great.

Kind regards,
Christian
[GLIMPSE-1.1.1_dynamic_linking.txt](https://github.com/odelaneau/GLIMPSE/files/7309259/GLIMPSE-1.1.1_dynamic_linking.txt)

**Comment by srubinacci** [comment]
Hi,
The program changed quite drastically and this became out of date (especially the bioconda part). Please feel free to open another issue or reopen if necessary.
