### ISSUE TITLE
map file behaviour changes by argument

### ISSUE THREAD

**Issue by tristanpwdennis** [odelaneau/GLIMPSE#86]
Hi!

I am imputing some low-coverage data. I have a genetic map (see below for an example line). I think I have accidentally stumbled on some strange behaviour. I noticed when I specify the (incorrect, it has 4 columns vs the 3 we want) map with `--map <mapfile>`, the software enforces the 3 column format given in the documentation with this error:

`ERROR: Parsing line 0 : incorrect number of columns, observed: 4 expected: 3`

However,  when I was running the software a different time, I specified the map - apparently incorrectly - with `map=<mapfile>`, and it seems to be running correctly.

Not sure if this is meant to happen or not, but thought I'd let you know just in case it was useful.

Thanks, Tristan

 - example line here
`3L       1815119 0.500   0.000`

**Comment by srubinacci** [comment]
Hi, 
We provide maps for humans here: https://github.com/odelaneau/GLIMPSE/tree/master/maps, so you can see the format that GLIMPSE expects. As you can see, the format is very simple:

`pos	chr	cM
55550	1	0
82571	1	0.080572
88169	1	0.092229
285245	1	0.439456
629218	1	1.478148
629241	1	1.478214
630053	1	1.480558
632942	1	1.488889
633147	1	1.489481
`
If you are imputing human data, you can just use one of the provided maps. In the case you are not, I think it won't be too difficult for you to translate your map to this format.

Hope this helps,

Simone
