### ISSUE TITLE
Imputation of high-coverage WGS data and CHM13

### ISSUE THREAD

**Issue by gevro** [odelaneau/GLIMPSE#88]
Hi,
Will GLIMPSE work to impute the very small number of missed germline variant calls from high coverage whole genome sequencing data?

Also, are you aware of any CHM13-v1 reference panels?

Thanks.

**Comment by srubinacci** [comment]
Hi,
Depending on what you mean with high-coverage (>20x?) and the type of data you have (Illumina short reads?), it's likely that GLIMPSE can work. However, you are in a setting where I am not sure imputation can be very helpful, as  reference panels are not really much better than your data.
Regarding your second question, unfortunately not, I am not aware of CHM13-v1 reference panels.

Best wishes,
Simone

**Comment by JosephLalli** [comment]
@srubinacci Just wanted to readdress this point. With high-coverage short read data, phasing and imputation would typically be performed with a tool like ShapeIt4 or Beagle. However, as far as I can tell, neither tool handles de novo variants well.

If I have a called, high-quality variant in my sample that is not present in the reference panel, both ShapeIt4 and Beagle simply drop the variant. My impression is that GLIMPSE will attempt to phase the variant, which is my desired behavior.

Do I have that right?
