### ISSUE TITLE
Does GLIMPSE only refine genotypes of called variants or does it add missing variants?

### ISSUE THREAD

**Issue by gevro** [odelaneau/GLIMPSE#89]
Hi,
I ran GLIMPSE on low-coverage WGS variant calls per the tutorial. However, the final output does not contain any new variants relative to the input variant calls. Does GLIMPSE impute missing variants, or does it only refine genotypes of called variants?

Thanks.

**Comment by gevro** [comment]
I think I understand the issue-- GLIMPSE needs an input where there was a forced genotyping step at all sites of the reference in order to get a PL value for those sites.

**Comment by GabrielCabas** [comment]
Hi, how did you fixed this issue? 
Thanks
