### ISSUE TITLE
odd std::bad_alloc error

### ISSUE THREAD

**Issue by ltcrod** [odelaneau/GLIMPSE#90]
Hi, 

I've been using GLIMPSE for quite some time without basically any issues. 
Yet, lately I'm encountering the following error I'm reporting here while running the GLIMPSE_phase part: 

```
[GLIMPSE] Phase and impute low coverage sequencing data
  * Author        : Simone RUBINACCI & Olivier DELANEAU, University of Lausanne
  * Contact       : simone.rubinacci@unil.ch & olivier.delaneau@unil.ch
  * Version       : 1.0.1
  * Run date      : 11/01/2022 - 13:29:25

Files:
  * Input VCF     : [/path/{file_name}.chr9_MaximumLikelihood.vcf.gz]
  * Reference VCF : [/path/chr9.1kg.phase3.v5a.vcf.gz]
  * Genetic Map   : [/path/GLIMPSE/maps/genetic_maps.b37/chr9.b37.gmap.gz]
  * Output VCF    : [/path/{output_filename}_phased.vcf]
  * Input region  : [9:43611860-66513604]
  * Output region : [9:43811976-66313005]

Parameters:
  * Seed       : 15052011
  * #Threads   : 1
  * #Burnin    : 10
  * #Main      : 10
  * PBWT depth : 2
  * PBWT modulo: 8
  * Init K     : 1000

Initialization:

Parsing specified genomic regions
  * Input region  [9:43611860-66513604]
  * Output region  [9:43811976-66313005]
  * VCF/BCF scanning [Nm=1 / Nr=2504 / L=7 / Reg=9:43611860-66513604] (1.81s)
  * VCF/BCF parsing done (1.78s)
  * GMAP parsing [n=158000] (0.08s)
  * cM interpolation [s=1 / i=6] (0.00s)
  * Region spans 1204376 bp and 0.00 cM

Initializing iteration
  * HMM imputation [#states=1000.0 / %poly=85.7%] (0.00s)

Burn-in 1 iteration [1/10]
  * HAP update (0.00s)
  * PBWT building & selection (0.00s)
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted (core dumped)
```
I'm running it for every chunk of the chromosome, and the other ones do not fail, so I feel pretty clueless about the reason for the error. 
Also, I'm working on a cluster with plenty of available memory, and I've already tried to run it on different systems as, to my knowledge, `std::bad_alloc` is generally a C++ memory allocation error. 
The only real difference with the working ones is that it apparently spans 0.00 cM (?) `Region spans 1204376 bp and 0.00 cM` but I don't see how this could be an issue.
I've also seen the [previous issue on this topic](https://github.com/odelaneau/GLIMPSE/issues/22), but I'm already using the provided map files. 

Do you have any clues on what can be done about it? 

Thanks, and thanks for your work! 

Kindly, 
Luca

**Comment by srubinacci** [comment]
Hi Luca,

There are many things in this log file that suggest there's something wrong in this chunk. Solving these problems likely solves the error you are experiencing too. 
If you look at the number of overlapping markers in the region ((L), there are only 7 markers found. That is not what you should expect using 1000GP if you computed the likelihoods correctly, as a call is provided at each variant. This number should be in the order of thousands. This likely causes problems in the genetic distance reported (0cM)

My guess is that your likelihood file is somewhat not correct in that region, you might want to check this with bcftools, try to intersect it with the reference panels, and count how many markers are in the intersection with bcfttools. 
Additionally, as a suggestion, try to run the latest version of GLIMPSE (v1.1.1) if you're experiencing errors. If there's a bug in the software, maybe it has been already corrected in a newer version (it shouldn't be the case here, though).

Let me know how it goes.

Hope this helps
Best wishes,

Simone
