### ISSUE TITLE
Different DYN_LIBs in makefiles

### ISSUE THREAD

**Issue by sandra-selfdecode** [odelaneau/GLIMPSE#93]
I was unable to install GLIMPSE in a docker image built with buster. I finally determined that the `system: DYN_LIBS` line was causing the problem, because it did not include all of the libraries needed for my system.

When I run `sed -i s'/system: DYN_LIBS=-lz -lpthread -lbz2 -llzma//' */makefile` I'm able to install successfully.

I don't have the same problem in ubuntu, but I wanted to let you know in case it's a problem for anyone else.

**Comment by srubinacci** [comment]
Thank you very much for reporting this. Indeed, most of these dependencies come from htslib and can be disabled at compile time.
So happy to hear it works!

For future reference, if you're not interested in lzma or bz2 (as GLIMPSE would not use it), just specify:
`autoheader && autoconf && ./configure --disable-lzma --disable-bz2 && make libhts.a`
In the compilation of htslib.
Best wishes,

Simone
