### ISSUE TITLE
problem in GLIMPSE_phase step

### ISSUE THREAD

**Issue by felassadi** [odelaneau/GLIMPSE#95]
Hello GitHub community,

I am in new in this field. I am trying to practice imputation using GLIMPSE in order to apply the pipeline on my samples later. So far, I have only been following the tutorial to practice on the sample they are using. 
**the issue**: the GLIMPSE_phase step is not generating vcf/bcf files output, as mentioned in the instructions, although the command runs without errors. All the previous steps worked out well. For the phasing step, I have increased the memory and changed the name of the output file for it to work. The command run well without any error; however, no output files were generated. Thus, I can't move to the next step (ligation).
P.S: please note that I have tried using the static version as well, as I suspected that GLIMPSE was not compiled correctly. However, both static and non-static version are not generating any output.
If you have any advice on why I am facing this, I will appreciate your help.
Thank you!

**Comment by srubinacci** [comment]
Hi.
Thank you for the detailed report. If the program runs, it should be working fine. My guess is that is that there's some problem with the output file you provide.

Can you please share a log? Keep in mind for example that the program won't create new folders (just files in existing folders), therefore if the output file you provide refers to an unknown path, you might end up in the error you're reporting.

**Comment by felassadi** [comment]
Hi Simone,
Thanks a lot for your prompt reply. 
When I changed the name of the output file, it created a new folder inside GLIMPSE/tutorial directory. The file is empty even after running the command successfully; now, I understand from you that it will not work that way. However, the reason why I changed the name of the output file is that I kept getting "segmentation fault" error when running the GLIMPSE-phase command lines, even after increasing the memory to 120 GB. So what would be wrong in that case?
I am not sure what you mean by the log. If you mean the script I am using, I can share it in the next comment.

**Comment by felassadi** [comment]
Hi Simone,

Thanks a lot for your prompt reply and for trying to help.

The problem is solved. It was related to the home directory. The home directory has been recently moved on our HPC, and for some reason, it was not connecting properly with the command line.
