### ISSUE TITLE
Difference in bcftools stats and GLIMPSE concordance in RR discordance counts

### ISSUE THREAD

**Issue by njbernstein** [odelaneau/GLIMPSE#99]
Hi there,

I think bcftools and GLIMPSE_concordance tool counts RR mismatches in different ways but I have been able to track it down:
GLIMPSE_concordance counts. The following table are per VAF bins and even though they VAF bins overlap exactly its clear they are count RR matches and mismatches differently.
```
0  RR_hom_matches  RR_hom_mismatches
1        120154.0               21.0
2         44203.0                8.0
3        101353.0               27.0
4        131009.0               45.0
5        582673.0              379.0
6        549366.0              606.0
7        853225.0             1257.0
8       1323616.0             3429.0
```
bcftools stats
```
0  [4]RR Hom matches  [7]RR Hom mismatches
1           124938.0                5318.0
2            59238.0                1935.0
3           127731.0                3776.0
4           130745.0                3835.0
5           542624.0               11712.0
6           511676.0                4477.0
7           815863.0                6514.0
8          1044497.0                6841.0
9           239088.0                2186.0
```

Most notably this flips the relationship with MAF. As with the GLIMPSE counts RR discordance increases with an increase of AF and with bcftools stats RR discordance decreases with an increase of AF. Happy to provide more info if the above is insufficient.

**Comment by srubinacci** [comment]
Hi,
Thanks for looking and reporting this. I will have a careful look in the next few days. I think a difference might be that bcftools stats works with allele frequencies defined in 0-1, while by default GLIMPSE_concordance uses MAF (0-0.5). 
Will look and maybe ask for a reproducible example.
Thanks

Simone

**Comment by njbernstein** [comment]
Hi there,

I believe you are right. That its a MAF vs alternate AF issue. havent verified it myself though
